### ISSUE TITLE
Add endpoints v2 sample

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/nodejs-docs-samples#104]
Python
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/managed_vms/endpoints

Go
https://github.com/GoogleCloudPlatform/golang-samples/tree/master/docs/managed_vms/endpoints

PHP
https://github.com/GoogleCloudPlatform/php-docs-samples/pull/95

@jmdobry @jonparrott

**Comment by jmdobry** [comment]
Fixed by #105
