### ISSUE TITLE
retry-request 4.0 won't work but 3.3.2 works

### ISSUE THREAD

**Issue by kenakamu** [GoogleCloudPlatform/nodejs-docs-samples#1069]
retry-request 4.0 won't work but 3.3.2 works

**Comment by fhinkel** [comment]
@kenakamu Thanks for opening the issue. For which sample does `retry-request` not work?

**Comment by kenakamu** [comment]
Forgot to mention that. sorry.

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/iot/http_example

**Comment by fhinkel** [comment]
Thanks. @gguuss , could you have a look?

**Comment by gguuss** [comment]
I'm able to reproduce the behavior on Node 10.  I'll update the package / configuration.

**Comment by gguuss** [comment]
This should be [fixed in this PR](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1078).
