### ISSUE TITLE
Finish the endpoints samples

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/nodejs-docs-samples#107]
More TODOs after the bare sample is submitted. https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/105
- [ ] Add a clients to send requests for echo, google_jwt, google_id_token.
- [ ] Add tests.
- [ ] Add error handling. See swagger spec for the error format.

**Comment by ace-n** [comment]
Closing, see #419 and #330.

@jeffmendoza please reopen if more needs to be done.
