### ISSUE TITLE
Node js code for indefinite speech transcription API

### ISSUE THREAD

**Issue by axchanda** [GoogleCloudPlatform/nodejs-docs-samples#1071]
Hi! There is no indefinte transcription hack for node for the Cloud Speech API. 
I would need the node js equivalent for the python version of this: 
[https://github.com/GoogleCloudPlatform/python-docs-samples/blob/speech-continuous/speech/cloud-client/transcribe_streaming_indefinite.py]
Please help us back soon. Thanks!

**Comment by fhinkel** [comment]
Hi @axchanda. All samples areo `nodejs-speech` are [here](https://github.com/googleapis/nodejs-speech/tree/master/samples).
