### ISSUE TITLE
sendCommandToDevice MUST include subfolder otherwise error returned!

### ISSUE THREAD

**Issue by tripflex** [GoogleCloudPlatform/nodejs-docs-samples#1073]
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/5f3c3e068c7d4e4fdf3d548c7df34c9025a3398f/iot/manager/manager.js#L735-L738

Spent numerous hours trying to figure out why the example code was not working, just to figure out that it was due to not having the `subfolder` specified!

**Comment by fhinkel** [comment]
Thanks for reporting this. @gguuss Can you take a look. Thanks

**Comment by gguuss** [comment]
Will do, I'll see if the tests are failing.

**Comment by gguuss** [comment]
Looks like all of the tests including an end-to-end test for the commands feature are passing.

After subscribing using the MQTT example:

```
    node cloudiot_mqtt_example_nodejs.js --projectId=<your-project-id> --registryId=<your-registry-id> --deviceId=<your-device-id> --privateKeyFile=<path/to/your_private_key.pem> --algorithm=<RS256|ES256>
```

I am able to successfully send commands to the device from the manager sample:

```
    node manager.js sendCommand <your-device-id> <your-registry-id> <your-test-message>
```

What is the error you are encountering when running this on your machine?

**Comment by tripflex** [comment]
@gguuss my device is/was subscribed to the wildcard for commands, it would send a 503 internal server error when the call is made, see here:
https://stackoverflow.com/questions/53152073/google-cloud-iot-sendcommandtodevice-from-cloud-funcctions-showing-service-unava/53966108#53966108

and here:
https://stackoverflow.com/questions/53024685/google-cloud-iot-sendcommandtodevice-service-unavailable/53966081#53966081

This may have been specific issue with Firebase Functions though, i'm honestly not sure.  Basically my device is subscribed to wildcard for commands, and then I trigger a firebase function that sends the command.  Looking at the logs in the firebase functions logs it shows the 503 error as detailed in those SO posts.  Once I added a subfolder, it worked without issues ... if subfolder is not specified, would return that error

**Comment by gguuss** [comment]
Reopening.  This is very odd.  Can you provide more information about your environment?  I'm assuming you're running on a Linux Workstation running Node10.

**Comment by tripflex** [comment]
@gguuss it's probably related to Firebase function as that's what is making the actual call, for reference here's the fb function:

```javascript
    sendCommand(deviceId: string, commandMessage?: any, subfolder: string = 'firebase' ) {
        return new Promise((resolve, reject) => {

            const request = {
                name: `${this.registryName}/devices/${deviceId}`,
                binaryData: Buffer.from(JSON.stringify(commandMessage)).toString("base64"),
                subfolder: subfolder
            }

            this.client.projects.locations.registries.devices.sendCommandToDevice( request, (err: any, resp: any) => {
                if (err) {
                    console.log('Could not send command:', request);
                    console.log('Error: ', err);
                    reject(err);
                } else {
                    resolve(resp);
                };
            });
        });
    }
```

As mentioned above, when the `subfolder` param is not included, the 503 error is returned, when it's included (and has a value) it works perfectly fine

**Comment by gguuss** [comment]
This definitely appears to be specific to execution from Firebase. Google Cloud Functions and  local NodeJS works as demonstrated in the sample and documentation.

**Comment by gguuss** [comment]
Just one more update here, folks on the team are aware of the issue. We'll determine why this happens from Firebase. @tripflex - Can you also share the code you're using to subscribe your device to the commands topic?

**Comment by gguuss** [comment]
Friendly ping @tripflex, can you provide more information on how you're subscribing to the commands topic from your device?

**Comment by tripflex** [comment]
@gguuss sorry just now seeing this, i'm subscribing to the wildcard topic using a standard MQTT library, to the topic following this pattern:

`/devices/DEVICEID/commands/#`

**Comment by gguuss** [comment]
Are you seeing any errors? E.g. are you seeing an error when sending the command or subscribing to the wildcard topic?

**Comment by gguuss** [comment]
OK, this seems to be an issue with Firebase and not with the samples themselves. I'll follow up with the right folks from there but will be closing the issue here.
