### ISSUE TITLE
MongoDB URI in nodejs-docs-samples/appengine/mongodb

### ISSUE THREAD

**Issue by kenn44** [GoogleCloudPlatform/nodejs-docs-samples#1135]
The keys.json file is not versionned. So how App Engine get the MONGOGD_URI when the app is deploy?

**Comment by fhinkel** [comment]
You can deploy a `keys.json` file without committing it to git. If you run `gcloud app deploy` all files except those in `.gcloudignore` will be deployed to AppEngine. 

Here are some more resources: 

- [Connect to MongoDB from Node.js on App Engine flexible environment](https://cloud.google.com/community/tutorials/nodejs-mongodb-on-appengine)
-  [Securely storing environment variables in GAE with app.yaml
](https://stackoverflow.com/questions/22669528/securely-storing-environment-variables-in-gae-with-app-yaml)
