### ISSUE TITLE
How to add the environment variables in Windows?

### ISSUE THREAD

**Issue by paulcanning** [GoogleCloudPlatform/nodejs-docs-samples#117]
I cannot figure out how to set the `GOOGLE_APPLICATION_CREDENTIALS` on Windows 10.

The documentation is pretty sparse.

I have Node setup OK, and cloned this repo.

I get the following error when running the command `node recognize "resources/quit.raw"`

> Got audio file!
> Loading speech service...
> { [Error: Google Cloud Speech API has not been used in project google.com:cloudsdktool before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/speech.googleapis.com/overview?project=google.com:cloudsdktool then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.]
>   code: 403,
>   errors:
>    [ { message: 'Google Cloud Speech API has not been used in project google.com:cloudsdktool before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/speech.googleapis.com/overview?project=google.com:cloudsdktool then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.',
>        domain: 'global',
>        reason: 'forbidden' } ] }

Why is it looking at the wrong project?

How do I set it to look at my project (I have a google project with speech api enabled)

**Comment by Hgergely** [comment]
Hey Paul

I could get it working however not on windows 10 but it should not make any
difference
Have you run this line ?

export GOOGLE_APPLICATION_CREDENTIALS=/path/to/service_account_file.json

and created the right file for your application? if not go to

https://cloud.google.com/speech/docs/auth-template/cloud-api-auth#using_the_console_name_short

link which explains just fine how to do that. it works.

Counter question :

Do you have any idea when they will add wrapper for the streaming version too?

Cheers

Greg.

**Comment by paulcanning** [comment]
`export` is not a Windows command. (docs only cater for linux)

I got it working by manually adding the env variables in Windows (control panel, system, environment variables)

**Comment by Hgergely** [comment]
Also check this out
http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows

greg

**Comment by jmdobry** [comment]
> Why is it looking at the wrong project?

Make sure your `GCLOUD_PROJECT` environment variable is set to your Google project ID.

Command prompt:

```
set GCLOUD_PROJECT=your-project-id
set GOOGLE_APPLICATION_CREDENTIALS=/path/to/service_account_file.json
```

Powershell:

```powershell
$env:GCLOUD_PROJECT="your-project-id"
$env:GOOGLE_APPLICATION_CREDENTIALS="/path/to/service_account_file.json"
```

**Comment by jmdobry** [comment]
The README no has instructions for setting environment variables in windows.

**Comment by sonanhson** [comment]
Hi jmdobry,

I know this post quite old. But I have the same problem about setting environment variable as below:
I want to use Google cloud vision API on Python. I have created a service account for authentication.
Based on the instruction of **jmdobry** in this post, I use the environment variable with the following commands in cmd:

set GCLOUD_PROJECT=my-project-id
set GOOGLE_APPLICATION_CREDENTIALS=C:/Python install/Google API/filename.JSON

Then, I run the following Python code to test the first API request:

_import io
import os

# Imports the Google Cloud client library
from google.cloud import vision
from google.cloud.vision import types

# Instantiates a client
client = vision.ImageAnnotatorClient()

# The name of the image file to annotate
file_name = os.path.join(
    os.path.dirname(__file__),
    'C:/Python install/Python Test/Photos Testing/Lobstersize.jpg')

# Loads the image into memory
with io.open(file_name, 'rb') as image_file:
    content = image_file.read()

image = types.Image(content=content)

# Performs label detection on the image file
response = client.label_detection(image=image)
labels = response.label_annotations

print('Labels:')
for label in labels:
    print(label.description)_

But, it shows an error as below:

_Traceback (most recent call last):
  File "GoogleAPI.py", line 9, in <module>
    client = vision.ImageAnnotatorClient()
  File "C:\Python install\lib\site-packages\google\cloud\vision_v1\gapic\image_annotator_client.py", line 135, in __init
__
    ssl_credentials=ssl_credentials)
  File "C:\Python install\lib\site-packages\google\gax\grpc.py", line 106, in create_stub
    credentials = _grpc_google_auth.get_default_credentials(scopes)
  File "C:\Python install\lib\site-packages\google\gax\_grpc_google_auth.py", line 62, in get_default_credentials
    credentials, _ = google.auth.default(scopes=scopes)
  File "C:\Python install\lib\site-packages\google\auth\_default.py", line 292, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICA
TION_CREDENTIALS or
explicitly create credential and re-run the application. For more
information, please see
https://developers.google.com/accounts/docs/application-default-credentials._

Please help me this issue.

Thank you very much.

Son.

**Comment by Sakthi-G33k** [comment]
Hi sonsnhson, I also have the same problem. I have tried setting the environment variable through the above commands and directly through control panel, but the same error persists. Is there any solution to this problem? Is there any other way I can get the vision API up and running locally?

**Comment by Sakthi-G33k** [comment]
Hi @sonanhson, I found the solution, use the following code to add the environment variable, it works. But I don't know yet why the other approaches don't work.

import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "path_to_your_.json_credential_file"

This will also be useful when you are switching between projects that need different credentials.

**Comment by Annushka34** [comment]
it helped me)

**Comment by rajeshray02** [comment]
Hi All,
I need your valuable suggestion, I am using google API(Google.Cloud.Speech.V1) for voice dictation and using C# as code behind. Below is the part of Code:

var speech = SpeechClient.Create();
            var response = speech.Recognize(new RecognitionConfig()
            {
                Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
                SampleRateHertz = 16000,
                LanguageCode = "en",
            }, RecognitionAudio.FromFile("audio.raw"));
            foreach (var result in response.Results)
            {
                foreach (var alternative in result.Alternatives)
                {
                    Console.WriteLine(alternative.Transcript);
                }
            }

but I'm getting exception "Status(StatusCode=PermissionDenied, Detail="Cloud Speech API has not been used in project 19063669187 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/speech.googleapis.com/overview?project=19063669187 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.")". 

As one suggestion is given by  Hgergely is to run the below code:

export GOOGLE_APPLICATION_CREDENTIALS=/path/to/service_account_file.json

But where I have to run this line of code. I did run in cmd but didn't work. In code behind 'export' keyword is not acceptable.

Please do provide your valuable suggestion with clear details.
Thanks...

**Comment by vik-zoonga** [comment]
@rajeshray02 use this from command line: 
set GOOGLE_APPLICATION_CREDENTIALS=/path/to/service_account_file.json

**Comment by epebojot** [comment]
> > Why is it looking at the wrong project?
> 
> Make sure your `GCLOUD_PROJECT` environment variable is set to your Google project ID.
> 
> Command prompt:
> 
> ```
> set GCLOUD_PROJECT=your-project-id
> set GOOGLE_APPLICATION_CREDENTIALS=/path/to/service_account_file.json
> ```
> 
> Powershell:
> 
> ```powershell
> $env:GCLOUD_PROJECT="your-project-id"
> $env:GOOGLE_APPLICATION_CREDENTIALS="/path/to/service_account_file.json"
> ```

After all the struggles, I didn't include the $ dollar sign

**Comment by ansh-mehta** [comment]
> `export` is not a Windows command. (docs only cater for linux)
> 
> I got it working by manually adding the env variables in Windows (control panel, system, environment variables)

I am setting it manually, still, I get the same error.

**Comment by JDanielHarvey** [comment]
Still struggling with this myself but @sakthigeek solutions seems to have worked by setting it explicit. Interested to see if anyone else found a solution on Windows by setting it via CMD/PowerShell or through the UI of the control panel

**Comment by MDiakhate12** [comment]
For Windows CMD:
set GCLOUD_PROJECT=foobar
set GOOGLE_APPLICATION_CREDENTIALS=path/to/your/file.json

Important! 
I was really struggling with it since I noticed that the problem was due to double quotes
DON'T USE Double quotes!
