### ISSUE TITLE
Add engines field to package.json for samples

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/nodejs-docs-samples#12]
We recently added support for engines in package.json:
http://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html

Should we pin down the supported nodejs version in each sample?

**Comment by jmdobry** [comment]
Do we have a list of the available Node versions?

**Comment by jmdobry** [comment]
Found it: https://storage.googleapis.com/gae_node_packages

**Comment by jmdobry** [comment]
Closed by #17
