### ISSUE TITLE
getApplicationDefault is undefined. 

### ISSUE THREAD

**Issue by neoadventist** [GoogleCloudPlatform/nodejs-docs-samples#121]
running the `create_custom_metric` on line  https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/monitoring/create_custom_metric.js#L218 

the object google.auth looks like 

`{ Compute: [Function], JWT: [Function], OAuth2: [Function] }`

no `getApplicationDefault` function

I'm supplying a project id, is there something i'm doing wrong here? 

Thanks.

**Comment by neoadventist** [comment]
trying to use this with stackdriver.

**Comment by jmdobry** [comment]
Can you post your error? And did you set the `GCLOUD_PROJECT` and `GOOGLE_APPLICATION_CREDENTIALS` environment variables? See https://github.com/GoogleCloudPlatform/nodejs-docs-samples#prerequisites

**Comment by neoadventist** [comment]
@jmdobry yeah got it working now. I did not have the `GOOGLE_APPLICATION_CREDENTIALS` env set. now i'm trying to get the custom metric to be visible on a dashboard. Do you know where I can go to for that?

**Comment by jmdobry** [comment]
Have you looked through https://app.google.stackdriver.com/ for your custom metric? You might have to write some data to the custom metric before it will show up. You also might have to create a new dashboard or alert targeting the metric. @waprin probably knows more.

**Comment by neoadventist** [comment]
There are a thousand sub-menus, but I can't find the metric when I try to add a graph. 
![Uploading custom metrics.png…]()

**Comment by neoadventist** [comment]
![gcloud_custom_metrics](https://cloud.githubusercontent.com/assets/3851190/15912242/f59dedaa-2d87-11e6-94dc-cf9bc2a2f90e.png)

**Comment by waprin** [comment]
You should see "Custom Metrics" as an option under "Resource Type". If you don't, you probably haven't successfully created any custom metric descriptors.

**Comment by neoadventist** [comment]
@waprin any documentation to show me on how to do that?

**Comment by neoadventist** [comment]
so I can successfully create it under the code but not see it in the UI until i make a descriptor?

**Comment by waprin** [comment]
You are creating a metric descriptor, you create metrics when you actually write values to it. As soon as you create it you should be able to see it, one guess at your problem is by default the sample code deletes the metric descriptor after creating it. This was in the interest of keeping projects cleaned up, check to make sure you've commented that part out.

**Comment by waprin** [comment]
Unfortunately I agree the docs no the UI are a bit sparse, working on improving that now but nothing's ready yet.

**Comment by neoadventist** [comment]
@waprin yeah I commented that part out. Company tasked me to see if moving to google cloud to monitor our aws infrastructure would be a good fit. If I could figure this part out then I could move forward with the whole thing.

**Comment by neoadventist** [comment]
```
Created custom metric { name: 'projects/hopskipdrive-1138/metricDescriptors/custom.googleapis.com/custom_measurement',
  labels: [ { key: 'environment', description: 'An abritrary measurement' } ],
  metricKind: 'GAUGE',
  valueType: 'INT64',
  unit: 'items',
  description: 'An arbitrary measurement.',
  displayName: 'Custom Metric',
  type: 'custom.googleapis.com/custom_measurement' }
Wrote time series {}
Reading metric type custom.googleapis.com/custom_measurement
Time series { timeSeries:
   [ { metric: [Object],
       resource: [Object],
       metricKind: 'GAUGE',
       valueType: 'INT64',
       points: [Object] } ] }
null [ { name: 'projects/hopskipdrive-1138/metricDescriptors/custom.googleapis.com/custom_measurement',
    labels: [ [Object] ],
    metricKind: 'GAUGE',
    valueType: 'INT64',
    unit: 'items',
    description: 'An arbitrary measurement.',
    displayName: 'Custom Metric',
    type: 'custom.googleapis.com/custom_measurement' },
  {},
  { timeSeries: [ [Object] ] } ]
```

Is the output, can't see it in the UI though.

**Comment by waprin** [comment]
Have you tried refreshing the UI page? I needed to (some of these single-page apps don't always pickup backend changes correctly without a refresh, though they of course should).

It's working on my end, hard to say if you're making a small mistake or if there is a subtle problem on our end:

`(logging)waprin-macbookpro:monitoring waprin$ node create_custom_metric.js bill-stackdriver-experiment custom_metric3
Created custom metric { name: 'projects/bill-stackdriver-experiment/metricDescriptors/custom.googleapis.com/custom_metric3',
  labels: [ { key: 'environment', description: 'An abritrary measurement' } ],
  metricKind: 'GAUGE',
  valueType: 'INT64',
  unit: 'items',
  description: 'An arbitrary measurement.',
  displayName: 'Custom Metric',
  type: 'custom.googleapis.com/custom_metric3' }
Wrote time series {}
Reading metric type custom.googleapis.com/custom_metric3
Time series { timeSeries: 
   [ { metric: [Object],
       resource: [Object],
       metricKind: 'GAUGE',
       valueType: 'INT64',
       points: [Object] } ] }
`

![screen shot 2016-06-08 at 3 10 51 pm](https://cloud.githubusercontent.com/assets/1075173/15912802/581044ee-2d8b-11e6-9f64-12acb252b13b.png)

**Comment by neoadventist** [comment]
@waprin ahhh! Should it matter if I'm using a service account or not? I'm not getting Custom Metrics as a resource type at all. How can I verify i'm looking at the correct project id?

**Comment by waprin** [comment]
Based on your output your project id should be hopskipdrive-1138 which should match the project-id in the top right corner of the console.

I would recommend using service accounts, we have other ways of auth but it's by far the approach least likely to give you problems as long as the GOOGLE_APPLICATION_CREDENTIALS is correctly set.

Are you trying to use a Google Cloud project to create a metric in the same Google Cloud project? If you're trying to do cross-project monitoring, things might have to be slightly different.

**Comment by neoadventist** [comment]
Yeah it was a mistake. `gcloud` isn't required if i set the GOOGLE_APPLICATION_CREDENTIALS properly?

**Comment by neoadventist** [comment]
![gcloud_custom_mesurement](https://cloud.githubusercontent.com/assets/3851190/15913589/c3607a1c-2d8f-11e6-8c65-f01ed99097a7.png)

**Comment by jmdobry** [comment]
> `gcloud` isn't required if i set the GOOGLE_APPLICATION_CREDENTIALS properly?

`gcloud` is one of two Node.js client libraries that supports Google Cloud Platform services. However, `gcloud` does not yet support the Monitoring API, so you're limited to the `googleapis` libraries to interact with the Monitoring API (for now). Both `gcloud` and `googleapis` can use the `GOOGLE_APPLICATION_CREDENTIALS` environment variable in order to authenticate requests.
