### ISSUE TITLE
App engine hello world example too many dependencies

### ISSUE THREAD

**Issue by randomekek** [GoogleCloudPlatform/nodejs-docs-samples#1247]
Hello, the hello app engine hello world seems to depend on express. Please remove the dependency, as hello world should always be as succinct as possible for pedagogical purposes!

Is google-cloud/nodejs-repo-tools even strictly necessary?

```
const http = require('http');
const PORT = process.env.PORT || 8080;

const server = http.createServer((request, response) => {
  console.log(request.url);
  response.end('Hello Node.js Server!');
});

server.listen(PORT, err => {
  console.log(`App listening on port ${PORT}`);
  console.log('Press Ctrl+C to quit.');
});
```

**Comment by fhinkel** [comment]
I agree, `npm install` takes a long time considering this is just hello-world. 

We use `@google-cloud/nodejs-repo-tools` for the tests. We're in the process of simplifying this.

**Comment by QuantumInformation** [comment]
Also points to deprecated  npm install -g @google-cloud/functions-emulator
 and doesn't inform you how to set the project: ie

```
➜  helloworld git:(master) gcloud functions deploy helloGET --runtime nodejs8 --trigger-http

ERROR: (gcloud.functions.deploy) Error parsing [name].
The [function] resource is not properly specified.
Failed to find attribute [project]. The attribute can be set in the following ways:
- provide the argument [--project] on the command line
- set the property [core/project]
➜  helloworld git:(master)
```

**Comment by QuantumInformation** [comment]
But thanks for these examples, glad I don't have to depend on Serverless framework now, just another layer than can go wrong.

**Comment by grant** [comment]
@ace-n, can you look at the `@google-cloud/functions-emulator` dependency? Is that effort tracked somewhere?

**Comment by ace-n** [comment]
The closest thing to a tracking issue is (Google internal) b/134942934, but given the fragmentation of this work (lots of minor changes in many places) fully tracking each piece of it would add (IMHO) significant overhead. (Once we've fully updated the `functions` tests [which I'm working on doing this week], it would probably only take 1-2 reasonable-sized PRs.)

This is also _vaguely_ on my radar. My task queue is currently **100% full** however, so it'll likely be at least a few weeks before I have time to look at this. (You're welcome to beat me to it, of course.)

**Comment by fhinkel** [comment]
I'm working on removing `nodejs-repo-tools` for testing `hello-world`
