### ISSUE TITLE
update to v1beta1

### ISSUE THREAD

**Issue by vsaase** [GoogleCloudPlatform/nodejs-docs-samples#1258]
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/eb19c2311c75754213a891ec8b58d0308d4e0170/healthcare/dicom/dicom_stores.js#L251

i can't get this to work at the moment (permission denied response from server), maybe there is something else needed to be changed apart from fixing this line?

**Comment by fhinkel** [comment]
@noerog could you have a look please. Thanks

**Comment by noerog** [comment]
Are you passing in an API key? API keys are no longer required by the API but the Node.js code samples still expect one. You can either remove the API key parameter from the code or download a key using the instructions at https://cloud.google.com/docs/authentication/api-keys#creating_an_api_key and pass it in.

We are in the process of updating the samples to v1beta1 and removing the need for an API key.

**Comment by vsaase** [comment]
my mistake, the problem was that I set GCLOUD_PROJECT to mixed upper and lowercase, but only all lowercase is accepted
