### ISSUE TITLE
Http requests not working anyway

### ISSUE THREAD

**Issue by Chieftl** [GoogleCloudPlatform/nodejs-docs-samples#1312]
This HTTP request generate error:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/functions/node8/index.js#L314
```js
exports.helloAsync = async data => {
  const result = await fetch('https://www.example.com');
  return result;
};
```

Error message:
FetchError: request to https://www.example.com/ failed, reason: getaddrinfo EAI_AGAIN www.example.com:443 at ClientRequest.<anonymous>

Is it requests to foreign servers disabled now?

**Comment by fhinkel** [comment]
@ace-n Could you have a look, this is a problem with a Function sample. Thanks!

**Comment by ace-n** [comment]
Looks like a [DNS issue](https://stackoverflow.com/questions/40182121/error-getaddrinfo-eai-again). Are you running this code locally or on GCF itself? If the latter, do your firewall rules allow traffic on [ports 80 and 443](https://en.wikipedia.org/wiki/Port_(computer_networking)#Common_port_numbers)? (They should by default; you can double-check [here](https://console.cloud.google.com/networking/firewalls/list).)

**Comment by fhinkel** [comment]
@Chieftl :wave: Thanks for reporting the issue. Looks like it was a temporary problem and you were able to resolve it. Let us know if we should reopen the issue. Thanks!
