### ISSUE TITLE
topic.publisher is not a function

### ISSUE THREAD

**Issue by ttfreeman** [GoogleCloudPlatform/nodejs-docs-samples#1316]
I have followed all the steps in the tutorial but when I upload an image to Cloud Storage and check the logs, I find the function execution has stopped for the following error:

`TypeError: topic.publisher is not a function
                                                                  at pubsub.topic.get.then (/srv/index.js:37:30)
                                                                  at <anonymous>`

**Comment by fhinkel** [comment]
@ttfreeman Thanks for reporting the issue. Which sample is this?

**Comment by ttfreeman** [comment]
@fhinkel this tutorial: [https://cloud.google.com/functions/docs/tutorials/ocr#functions-clone-sample-repository-nodejs](url)

**Comment by fhinkel** [comment]
Thank you, I'll have a look

**Comment by fhinkel** [comment]
We were using an outdated API call. It should be `topic.publish()` instead of `topic.publisher.pubish()`. I created a PR to fix the issue. Thank you for brining it to our attention!
