### ISSUE TITLE
Cloud function while trigger - testing error

### ISSUE THREAD

**Issue by pratikdhavale** [GoogleCloudPlatform/nodejs-docs-samples#1318]
Getting output while testing the function

stopInstancePubSub
u3sbsgzeovt3
TypeError: callback is not a function at exports.stopInstancePubSub (/srv/functions/index.js:53:5) at Promise.resolve.then (/srv/node_modules/@google-cloud/functions-framework/build/src/invoker.js:330:28) at process._tickCallback (internal/process/next_tick.js:68:7)

Referring the doc/code from here: https://cloud.google.com/scheduler/docs/start-and-stop-compute-engine-instances-on-a-schedule

**Comment by shinobe-atobe** [comment]
Same issue, followed the documentation to a t and get the error "TypeError: callback is not a function" when running the following part of the documentation

```
gcloud functions call startInstancePubSub \
    --data '{"data":"eyJ6b25lIjoidXMtd2VzdDEtYiIsICJsYWJlbCI6ImVudj1kZXYifQo="}'
```

**Comment by prabowomurti** [comment]
I also face the same issue. I was trying to migrate the code, using this doc https://cloud.google.com/functions/docs/migrating/nodejs-runtimes but ends with no luck. Please. Help.

**Comment by pratikdhavale** [comment]
**Start Compute Engine:**

var http = require('http');
var Compute = require('@google-cloud/compute');
var compute = Compute();
exports.startInstance = function startInstance(req, res) {
    var zone = compute.zone('instance zone here');
    var vm = zone.vm('instance name here');
    vm.start(function(err, operation, apiResponse) {
        console.log('instance start successfully');
    });
res.status(200).send('Success start instance');
};
**package.json:**

{
"name": "sample-http",
"dependencies": {
"@google-cloud/compute": "0.7.1"
},
"version": "0.0.1"
}
**Stop Compute Engine:**

var Compute = require('@google-cloud/compute');
var compute = Compute();
exports.stopInstance = function stopInstance(req, res) {
    var zone = compute.zone('instance zone here');
    var vm = zone.vm('instance name here');
    vm.stop(function(err, operation, apiResponse) {
        console.log('instance stop successfully');
    });
    res.status(200).send('Success stop instance');
};

I found working solution here [https://medium.com/google-cloud/start-stop-compute-engine-instance-from-cloud-function-bf9ae5199609](url)

Thanks _**HuanTing Chen**_

But still the code provided in GCP docs is not working.

**Comment by fhinkel** [comment]
@djmailhot Could you have a look, you authored the sample. Thank you!

**Comment by jpatokal** [comment]
Thank you for bringing this to my attention.   It looks like the [function signature has changed for NodeJS 8](https://cloud.google.com/functions/docs/migrating/nodejs-runtimes#nodejs-8-changes), and this was not caught by the unit tests.  I'll update this repo shortly, but in the meantime, you can find a fixed version here:

https://github.com/jpatokal/nodejs-docs-samples/blob/4086fd02f2ce305f3b2b7c6f1ea8f6f685b10ff3/functions/scheduleinstance/index.js

**Comment by jpatokal** [comment]
This should be fixed now.

**Comment by ace-n** [comment]
Marking as closed - please reopen if this continues to be an issue.
