### ISSUE TITLE
Remove functions emulator from repo

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/nodejs-docs-samples#1333]
The Google Cloud Functions Emulator was never an official Google product as stated on the README and the tool has been deprecated.

Please remove all uses of the emulator from this repo.

Optionally replace references with the functions framework:
https://github.com/GoogleCloudPlatform/functions-framework-nodejs

**Comment by fhinkel** [comment]
See https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1255

**Comment by grant** [comment]
PR looking good. Should be merged soon.

**Comment by ace-n** [comment]
#1255 will _help_, but doesn't completely solve the problem. This is blocked on (Google internal) b/134440627.

**Comment by fhinkel** [comment]
We removed it from all the code - but the Readme's still list it
* functions/helloworld/README.md
* functions/speech-to-speech/README.md

**Comment by fhinkel** [comment]
AFAIK this is fixed, please reopen if needed.
