### ISSUE TITLE
Deployment failure: Function failed on loading user code. Error message: Node.js module defined by file index.js is expected to export function named helloPubSub

### ISSUE THREAD

**Issue by Kai68er** [GoogleCloudPlatform/nodejs-docs-samples#1340]
Hey,
**i am trying to create a cloud function in GCP with the Console:**
![05-06-_2019_11-32-14](https://user-images.githubusercontent.com/37147992/58946239-bba40700-8785-11e9-8996-3304b9b791a7.png)

**Unfortunately, I am getting an error after creating the cloud function:**

> Deployment failure:
> Function failed on loading user code. Error message: Node.js module defined by file index.js is expected to export function named helloPubSub

**I got the newest version here:**
[https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/functions/scheduleinstance/index.js](url)

**Nevertheless, if I get the files with `git` then I could successfully create cloud functions with the commands:**
`gcloud pubsub topics create start-instance-event`
`gcloud pubsub topics create stop-instance-event`

In the instructions [https://cloud.google.com/scheduler/docs/start-and-stop-compute-engine-instances-on-a-schedule](url) it is explained that you have to use 2 instead of 1 script. If so, what is the correct naming for the cloud function?
![05-06-_2019_11-34-06](https://user-images.githubusercontent.com/37147992/58946318-e1c9a700-8785-11e9-95a9-0f690a848087.png)

It seems that before the start- and stop-function were splitted and now are parsed into one?
So it means that I still have to create 2 cloud functions?
It might make sense to update the "Scheduling Compute Instances with Cloud Scheduler"-article or at least expail it better in the README.

Thanks a lot.

**Comment by fhinkel** [comment]
@ace-n Could you have a look at this functions questions? Thanks!

**Comment by ace-n** [comment]
@Kai68er - it looks like you forgot to set the **Function to execute** property when deploying your function in the Cloud Console. (`helloPubSub` is the default value for that.)

I'll close this for now - please re-open if you aren't able to resolve this issue.
