### ISSUE TITLE
Add Dockerfile linting to CI

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/nodejs-docs-samples#1374]
Per @grayside's comment [here](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1373#discussion_r295548272) - we should consider adding `hadolint` (or a similar Docker linting system) to CI.

(Aside: it does take eng. time, but my vote is 100% in favor of adding as many CI checks as we can.)

**Comment by grayside** [comment]
The easiest way to run hadolint is via docker:

```sh
docker run --rm -i hadolint/hadolint < Dockerfile
```

However, docker is not currently available in the workspace container image.

**Comment by fhinkel** [comment]
Sounds good. Is `hadolint` what we use in other libraries?

**Comment by grayside** [comment]
I've not seen anything used for Dockerfile linting in Google repos

**Comment by fhinkel** [comment]
Closing this as there are more pressing issues in this repo. Feel free to re-open if you want to work on it.
