### ISSUE TITLE
Add shell script linting to CI

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/nodejs-docs-samples#1386]
Using the [shellcheck utility](https://github.com/koalaman/shellcheck) we can ensure shell scripts are well-formed, consistent, and without silent failures.

shellcheck can be run via Docker.

Note: shellcheck is used by `hadolint` to scan the shell statements inside Dockerfiles. hadolint is currently under consideration as a distinct Dockerfile linting check in #1374

**Comment by grayside** [comment]
Assigning to fhinkel for consideration.

**Comment by fhinkel** [comment]
Closing this as there are more pressing issues in this repo. Feel free to re-open if you want to work on it.
