### ISSUE TITLE
Dialogflow error in function deviceId  can’t be null

### ISSUE THREAD

**Issue by cfmaley3** [GoogleCloudPlatform/nodejs-docs-samples#1402]
Unable to get the dialogflow sample to work. I’ve deployed the node function to fire base but I get this error deviceId can’t be null. 

It also looks like firebase messaging needs to be configured for this sample. Is that true?  I was unable to find any reference to firebase messaging is needed for this sample.

**Comment by fhinkel** [comment]
@cfmaley3 👋 Thanks for reporting the issue. @ace-n could you help out here? It's one of the `functions` examples. Thanks

**Comment by ace-n** [comment]
@fhinkel thanks for the ping - but I didn't write this. 🙂

@nnegrey - who would be the right person to investigate this?

**Comment by cfmaley3** [comment]
Hi everyone

I’ve solved my issue .  I’ve found a few small issues in the project but
I’ll post the issues when I have a few minutes.

Thanks

Chris

**Comment by nnegrey** [comment]
Hi, yep, looks like we need to add a README (@santhoshvaddi)

This sample is built to create a token service for a mobile application so that the mobile app can talk to Dialogflow. 

ios README with instructions for this sample: https://github.com/GoogleCloudPlatform/ios-docs-samples/tree/master/dialogflow/stopwatch

Docs page: https://cloud.google.com/solutions/mobile/dialogflow-agent-commands

**Comment by santhoshvaddi** [comment]
Hi, sure @nnegrey I will add a README.

**Comment by santhoshvaddi** [comment]
@nnegrey I have added README  and renamed the root folder name from "dialogflow" to "tokenservice".  @cfmaley3 Please check the [README](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/functions/tokenservice). DeviceID is used to push the notification from Firebase cloud messaging(FCM).

DeviceID is equivalent to client's(iOS or Android app) app instance .

**Comment by nnegrey** [comment]
Thanks @santhoshvaddi, left a few quick comments on the README that should be updated. 

@cfmaley3, let us know if you need any more info, but going to close for now.
