### ISSUE TITLE
functions/ocr-app CI is failing

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-docs-samples#1417]
Hi, could you have a look what's wrong here. I don't see any code changes recently: 

```
> nodejs-docs-samples-functions-ocr@0.0.1 test /tmpfs/src/github/nodejs-docs-samples/functions/ocr/app
> mocha test/*.test.js --timeout=20000
  5 passing (1s)
  1 failing
  1) processImage
       processImage detects text:
      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual
      -false
      +true
      at Context.it (test/index.test.js:60:12)
      at <anonymous>
```

https://source.cloud.google.com/results/invocations/c83c9b2e-6e34-46da-a99f-015b124834fb/targets

cc @ace-n

**Comment by ace-n** [comment]
This is likely due to the `nodejs-docs-samples-tests-functions` bucket missing a `wakeupcat.jpg` file.

@fhinkel I've added that file back to the bucket - can you run the tests again, and close this bug iof everything passes? Thanks! 😃

**Comment by fhinkel** [comment]
Fixed. Thanks!
