### ISSUE TITLE
Use a project pool to avoid test collisions

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/nodejs-docs-samples#1428]
The golang and ruby sample repositories use a project pool to provide a dedicated GCP project for every CI run.

Doing this is extremely useful for any tests which consume GCP resources:

* Avoid excessively management of unique namespacing
* Avoid spawn of many distinctly named resources and management overhead
* Avoid cross-test data poisoning (writing data to an accidentally shared resource)
* Avoid cross-test data noise (log entries for concurrent operations requiring careful filtration)

Obstacles: Based on my understanding of how the gimmeproj mechanism works, this would be done for discrete CI runs. This means it would need to apply on a per sample basis in Node.js unless some more grouping were done at the Kokoro configuration level.

I am raising this because navigation of service name uniqueness for Cloud Run samples has taken a significant amount of time.

Ruby and Golang facilitate this with the [gimmeproj tool](https://github.com/GoogleCloudPlatform/golang-samples/tree/master/testing/gimmeproj)

@broady

**Comment by fhinkel** [comment]
We're using individual tests for Node.js instead of one group test as it's much easier to see on the dashboard which tests are newly failing. If they're all grouped together, chances are that there's always a red one and nobody notices new failures (speaking from experience 😞 ).

**Comment by fhinkel** [comment]
I think the way for now is to use precise names in tests and clean up test specific resources. Closing this for now. Feel free to re-open if we proceed to work on this.
