### ISSUE TITLE
Run: Move in the System Packages sample app

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/nodejs-docs-samples#1436]
Current Staged Location: https://github.com/GoogleCloudPlatform/cloud-run-samples/tree/master/nodejs/system_package

This sample needs to be moved to nodejs-docs-samples so the tutorial can be updated to point to GitHub.

A core premise of the tutorial is its dependency on the graphviz system package. The tests will not pass without the presence of this package.

* **Option 1**: Run the tests inside the container by first adding the docker client to the kokoro node:10-user container. (My preference)
* **Option 2**: Add graphviz package to node:10-user container and (if needed) modify the sample to look up the binary from a different location.

@fhinkel please provide feedback on your preference.

**Comment by fhinkel** [comment]
Either way is fine assuming one doesn't make the image a lot bigger than the other, but I don't think so.

**Comment by fhinkel** [comment]
Let me know how you want to move forward with this. Thanks!

**Comment by grayside** [comment]
For alignment with how golang-samples will work, I'll add graphviz to the container.

**Comment by fhinkel** [comment]
Sounds good. Closing this as resolved. Feel free to reopen if needed.
