### ISSUE TITLE
Typo in URL in example of  authCloudExplicit

### ISSUE THREAD

**Issue by aaronmgdr** [GoogleCloudPlatform/nodejs-docs-samples#1442]
there is an extra `a` in `Platform` of  the uri 

`https://github.com/GoogleCloudPlaatform/google-cloud-node/blob/master/docs/authentication.md` 
should be 
`https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/docs/authentication.md`

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/a0e17315529e67e0e5efa2491e441cf7a7449401/auth/auth.js#L56

**Comment by fhinkel** [comment]
Thank you! I'll get right on it.
