### ISSUE TITLE
endpoints: add /auth/info/firebase endpoint

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/nodejs-docs-samples#145]
This one needs CORS headers.

See sample implementation here:
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/docs/managed_vms/endpoints/app.go

and copy the new swagger file:
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/docs/managed_vms/endpoints/swagger.yaml

**Comment by fhinkel** [comment]
Closed due to inactivity. Feel free to reopen if needed.
