### ISSUE TITLE
TypeError: TwimlResponse is not a constructor

### ISSUE THREAD

**Issue by timburgess** [GoogleCloudPlatform/nodejs-docs-samples#1453]
Running the demo server for twilio produces `TypeError: TwimlResponse is not a constructor` when the `/sms/receive` path is used.

`package.json` is specifying `"twilio": "^3.30.3"`

Handler code is
```
app.post('/sms/receive', bodyParser, (req, res) => {
  const sender = req.body.From
  const body = req.body.Body

  const resp = new TwimlResponse()
  resp.message(`Hello, ${sender}, you said: ${body}`)

  res
    .status(200)
    .contentType('text/xml')
    .send(resp.toString())
})
```

**Comment by fhinkel** [comment]
@timburgess :wave: Thanks for reporting the issue!

@michaelawyu  Could you please have a look at this? Seems like there's a problem with the `appengine/twilio` sample. Thank you.
