### ISSUE TITLE
Migrate IoT samples to Cloud Client library

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/nodejs-docs-samples#1478]
Because it's easier to instantiate client libraries, we should migrate the IoT samples to the Cloud Client library. Example code showing send command to device:

```
  const iot = require('@google-cloud/iot');

  const newclient = new iot.v1.DeviceManagerClient({
    // optional auth parameters.
  });

  const parentName = `projects/${projectId}/locations/${cloudRegion}`;
  const registryName = `${parentName}/registries/${registryId}`;
  const binaryData = Buffer.from(data).toString('base64');
  const request = {
    name: `${registryName}/devices/${deviceId}`,
    binaryData: binaryData,
  };
  newclient.modifyCloudToDeviceConfig(request)
    .then(responses => {
      const response = responses[0];
      // doThingsWith(response)
    })
    .catch(err => {
      console.error(err);
    });
```

**Comment by fhinkel** [comment]
Can we assign this to somebody or should we close it for now as infeasible?

**Comment by gguuss** [comment]
I'm the right one to take it, I was waiting for another CL to land first.

**Comment by fhinkel** [comment]
The samples should also be move to the client library instead of living here https://github.com/googleapis/nodejs-iot

This way we catch bugs when we release the library and not only later when we notice it in this repo.

**Comment by gguuss** [comment]
SGTM, I may not be able to get to this until late Nov. early Dec. but it should not take long after I've wrapped up my talks and travel.

**Comment by gguuss** [comment]
This is now fixed, thanks everyone!

**Comment by gguuss** [comment]
We'll be 3/4 of the way there after [this PR merges](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1572).

**Comment by gguuss** [comment]
we're 3/4 of the way there!

**Comment by gguuss** [comment]
4/4 will wrap up when #1594 merges
