### ISSUE TITLE
Speech to speech Readme is outdated

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-docs-samples#1500]
The Readme still uses the function emulator, please update that. Are the other instructions still valid? @ricalo 

Ref https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1333

**Comment by ricalo** [comment]
Got it. I'll work on a PR to replace the references to the emulator with the Functions Framework. Other instructions look valid⁠—@ace-n previously updated the README in  #1384⁠—but I'll check that too.
