### ISSUE TITLE
run/System Package sample is failing tests

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/nodejs-docs-samples#1506]
This samples tests are currently failing.

Currently visible failure is the lack of the graphviz "dot" utility in the container. This was added to the container in https://github.com/googleapis/testing-infra-docker/pull/31, my understanding is that it was supposed to propagate automatically, but that is clearly not happening.

@bcoe helped with the updates to the containers.

Assigning to fhinkel@ for help/guidance on container image propagation for the sample tests.

**Comment by bcoe** [comment]
@grayside turns out there was a job I needed to trigger, I just did so.

**Comment by fhinkel** [comment]
Thanks @bcoe

**Comment by grant** [comment]
Seeing failures with this test in unrelated PR, https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/2120.

Logs:

```
/tmpfs/src/github/nodejs-docs-samples/run/system-package
> mocha test/app.test.js --check-leaks

error: syntax: no graphviz definition provided
error: syntax: no graphviz definition provided
Error: <stdin>: syntax error in line 1 near ''
error: Command failed: /usr/bin/dot -Glabel="Made on Cloud Run" -Gfontsize=10 -Glabeljust=right -Glabelloc=bottom -Gfontcolor=gray -Tpng
Error: <stdin>: syntax error in line 1 near ''
```

**Comment by grayside** [comment]
Looking into this now.

**Comment by grayside** [comment]
Those error messages are expected as part of the unit test, this is probably another instance for current work in #1991
