### ISSUE TITLE
iot CI failing

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-docs-samples#1527]
Hi @hongalex , I can't get the iot manager test to pass, e.g., on this PR

https://source.cloud.google.com/results/invocations/ae9e7ed3-31f2-4454-b0e3-57fef10e1b2d/targets/cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Fiot%2Fiot-manager/log 

Refs 

- https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1526
- https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1525

Could you have a look? Thanks

**Comment by fhinkel** [comment]
The iot/manager test failing seem to be related to this change:
googleapis/nodejs-iot@68a1d6e

Method name changed, but test from sample code was not updated.
client.registryPath -> client.deviceRegistryPath

**Comment by mesmacosta** [comment]
I sent a PR with a proposed fix: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1528

**Comment by fhinkel** [comment]
@hongalex @gguuss We deactivated the tests for now. Were you able to roll back the API change? Or should we adapt the test?

**Comment by gguuss** [comment]
@JustinBeckwith to comment on rolling back the breaking change, I lost track of the thread where this discussion was taking place.

**Comment by gguuss** [comment]
We have [this PR](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1528) with a fix, I'm open to merging it and then resolving if we can  roll back.

**Comment by fhinkel** [comment]
ping @JustinBeckwith

**Comment by JustinBeckwith** [comment]
Tracking in b/143947540

**Comment by gguuss** [comment]
This will be [fixed when this PR merges](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1539/files).

**Comment by gguuss** [comment]
This is now fixed, thanks everyone!
