### ISSUE TITLE
Deployment failure: Function failed on loading user code. 

### ISSUE THREAD

**Issue by arashokbabu** [GoogleCloudPlatform/nodejs-docs-samples#1559]
Deployment failure: Function failed on loading user code. 
Error message: Code in file index.js can't be loaded. 
Did you list all required modules in the package.json dependencies? 
Detailed stack trace: Error: Cannot find module '@google-cloud/language'

**Comment by fhinkel** [comment]
@arashokbabu thanks for raining an issue. Which sample were you trying to run? Thanks
