### ISSUE TITLE
Google IOT Core get device Nodejs client getClient initialization return value problem

### ISSUE THREAD

**Issue by radianceltd** [GoogleCloudPlatform/nodejs-docs-samples#1579]
Hello, I have configured the service credential JSON, and import it under the project main file. The data read by this API is always empty. I do n’t know where I wrote the problem. What I want to achieve is through the new Google v1-client.projects.locations.registries.devices.list to get the API, but one encountered this problem, the following is my code：

```
const getClient = (res) => {
    // the getClient method looks for the GCLOUD_PROJECT and GOOGLE_APPLICATION_CREDENTIALS
    // environment variables if serviceAccountJson is not passed in
    const authClient =  google.auth.getClient({
        keyFilename: 'riltmw025tool-2019-296a54b9be.json',
        scopes: ['https://www.googleapis.com/auth/cloud-platform'],
    });

    const discoveryUrl = `${DISCOVERY_API}?version=${API_VERSION}`;

    google.options({
        auth: authClient,
    });

    try {
        res.send(google.discoverAPI(discoveryUrl));
        return google.discoverAPI(discoveryUrl);
    } catch (err) {
        console.error('Error during API discovery.', err);
    }
};

//List all devices in the specified registry
const registry_list_Device = async (
    client,
    registryId,
    projectId,
    cloudRegion,
    res
) => {
    const parentName = `projects/${projectId}/locations/${cloudRegion}`;
    const registryName = `${parentName}/registries/${registryId}`;

    const request = {
        parent: registryName,
    };
    res.send(client);
    try {

        const {data} = await client.projects.locations.registries.devices.list(
            request
        );

        res.status(200).send(data);
        console.log('Current devices in registry:', data['devices']);
    } catch (err) {
        res.status(402).send(err);
        console.error('Could not list devices', err);
    }
}
```

**Comment by radianceltd** [comment]
![image](https://user-images.githubusercontent.com/58924597/71715593-e6099000-2e4c-11ea-9d93-352c2dca9828.png)

**Comment by radianceltd** [comment]
When I read the client API, Getclient returned to me like this, I don't know how to call const {data} = await client.projects.locations.registries.devices.list (request); the data data
![image](https://user-images.githubusercontent.com/58924597/71715644-14876b00-2e4d-11ea-99a8-4a852f8abb21.png)

**Comment by fhinkel** [comment]
@hongalex Could you have a look at this IoT issue? Thanks

**Comment by radianceltd** [comment]
@hongalex Can you help me see my problem

**Comment by hongalex** [comment]
I think the main issue here is that `google.discoverAPI(discoveryUrl)` is an async call that returns a Promise rather than a value. Therefore, your `res.send` call doesn't actually send the actual client. Try using `await google.discoverAPI(discoveryUrl)` in your `getClient` function. This means that `getClient` will have to marked `async` as well.

Since this isn't an issue with the samples themselves, I'm marking this issue as closed. If you continue to experience issues, I recommend bringing your question to one of the forums described here: https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

**Comment by radianceltd** [comment]
@hongalex 谢谢您的解答，像你描述的这样google.discoverAPI(discoveryUrl)是返回了一个对象.Promise,我也没理解这个是什么数据，但我通过const client = getClient('riltmw025tool-2019-21396a54b9be.json');传递给我需要调用的谷歌API，如：listDevicesForGateway，那么就是把这个client值传递给listDevicesForGateway作为客户端，始终访问client.projects.locations.registries.devices.list返回不到数据

**Comment by radianceltd** [comment]
@hongalex Thank you for your answer. Like you described, google.discoverAPI (discoveryUrl) returns an object. Promise, I did n’t understand what this data is, but I passed const client = getClient ('riltmw025tool-2019-21396a54b9be.json'); passed it to the Google API I need to call, such as: listDevicesForGateway, then this client value Passed to listDevicesForGateway as the client, always accessing client.projects.locations.registries.devices.list returns no data

**Comment by radianceltd** [comment]
`exports.ymqtthelloa = async (req,res) => {

    const cloudRegion = 'us-central1';
    const gatewayId = 'my-region';
    const projectId = 'riltmw025tool';
    const registryId = 'my-registry-006s';

    const client = getClient('riltmw025tool-2019-21396a54b9be.json');
    listDevicesForGateway(client, projectId, cloudRegion, registryId, gatewayId);
    console.log("异步读取lo: " + client);
}

const getClient = async (serviceAccountJson,res) => {
    // the getClient method looks for the GCLOUD_PROJECT and GOOGLE_APPLICATION_CREDENTIALS
    // environment variables if serviceAccountJson is not passed in
    const authClient = await google.auth.getClient({
        keyFilename: serviceAccountJson,
        scopes: ['https://www.googleapis.com/auth/cloud-platform'],
    });
   // console.log("11"+authClient.toString());
    const discoveryUrl = 'https://cloudiot.googleapis.com/v1/projects/riltmw025tool-2019/locations/us-central1/registries/my-registry/devices';
   // console.log("22"+discoveryUrl.toString());
    google.options({
        auth: authClient,
    });

    try {
        console.log("33"+google.discoverAPI(discoveryUrl));
        return google.discoverAPI(discoveryUrl);
    } catch (err) {
        console.log("402"+err);
        console.error('Error during API discovery.', err);
    }
};

const listDevicesForGateway = async (
    client,
    projectId,
    cloudRegion,
    registryId,
    gatewayId
) => {
    const parentName = `projects/${projectId}/locations/${cloudRegion}/registries/${registryId}`;
    const request = {
        parent: parentName,
        'gatewayListOptions.associationsGatewayId': gatewayId,
    };

    let devices;
    try {
        const {data} = await client.projects.locations.registries.devices.list(
            request
        );
        devices = data.devices;
    } catch (err) {
        console.error('Could not list devices', err);
        return;
    }

    console.log('Current devices bound to gateway: ', gatewayId);
    if (devices && devices.length > 0) {
        devices.forEach(device => {
            console.log(`\tDevice: ${device.numId} : ${device.id}`);
        });
    } else {
        console.log('No devices bound to this gateway.');
    }
    // [END iot_list_devices_for_gateway]
};
`
Why does client.projects.locations.registries.devices.list not return data?

**Comment by radianceltd** [comment]
`exports.ymqtthelloa = async (req,res) => {

const cloudRegion = 'us-central1';
const gatewayId = 'my-region';
const projectId = 'riltmw025tool';
const registryId = 'my-registry-006s';

const client = getClient('riltmw025tool-2019-21396a54b9be.json');
listDevicesForGateway(client, projectId, cloudRegion, registryId, gatewayId);
console.log("异步读取lo: " + client);
}`

`const getClient = async (serviceAccountJson,res) => {
    // the getClient method looks for the GCLOUD_PROJECT and GOOGLE_APPLICATION_CREDENTIALS
    // environment variables if serviceAccountJson is not passed in
    const authClient = await google.auth.getClient({
        keyFilename: serviceAccountJson,
        scopes: ['https://www.googleapis.com/auth/cloud-platform'],
    });
   // console.log("11"+authClient.toString());
    const discoveryUrl = 'https://cloudiot.googleapis.com/v1/projects/riltmw025tool-2019/locations/us-central1/registries/my-registry/devices';
   // console.log("22"+discoveryUrl.toString());
    google.options({
        auth: authClient,
    });

    try {
       // console.log("33"+google.discoverAPI(discoveryUrl));
        return google.discoverAPI(discoveryUrl);
    } catch (err) {

        console.error('Error during API discovery.', err);
    }
};`

`const listDevicesForGateway = async (
    client,
    projectId,
    cloudRegion,
    registryId,
    gatewayId
) => {
    const parentName = `projects/${projectId}/locations/${cloudRegion}/registries/${registryId}`;
    const request = {
        parent: parentName,
        'gatewayListOptions.associationsGatewayId': gatewayId,
    };

    let devices;
    try {
        const {data} = await client.projects.locations.registries.devices.list(
            request
        );
        devices = data.devices;
    } catch (err) {
        console.error('Could not list devices', err);
        return;
    }

    console.log('Current devices bound to gateway: ', gatewayId);
    if (devices && devices.length > 0) {
        devices.forEach(device => {
            console.log(`\tDevice: ${device.numId} : ${device.id}`);
        });
    } else {
        console.log('No devices bound to this gateway.');
    }
    // [END iot_list_devices_for_gateway]
};`

Why does client.projects.locations.registries.devices.list not return data?

**Comment by hongalex** [comment]
As mentioned earlier, this is not the proper place to raise this question. The issue tracker for this repository is only for sample related issues.

If you require assistance debugging your code, please post your question on StackOverflow and the community there (including myself) should be better able to help you.

Thanks!

**Comment by radianceltd** [comment]
@hongalex 好的，知道了，谢谢。

**Comment by radianceltd** [comment]
Okay, thank you.

**Comment by radianceltd** [comment]
@hongalex Okay, thank you.
