### ISSUE TITLE
Hi, sorry about the delay...

### ISSUE THREAD

**Issue by jramirez0309** [GoogleCloudPlatform/nodejs-docs-samples#1590]
Hi, sorry about the delay...

So, it turns out, I was trying to be too clever.

Since I'm using Typescript, I was getting told that `secureProtocol` does not exist in type 'IClientOptions' and decided I should try the only other property that did exist but wasn't being used ('protocolId' as below).

```javascript
const connectionArgs: mqtt.IClientOptions = {
  host: mqttBridgeHostname,
  port: mqttBridgePort,
  clientId: mqttClientId,
  username: deviceId,
  password: createJWT(projectId, privateKeyFile, algorithm),
  protocol: 'mqtts',
  protocolId: 'TLSv1_2_method'
}

mqtt.connect(opts)
```

I changed 'protocolId' back to 'secureProtocol' and told typescript to ignore it and all is working as expected now.

*As a side note*

I feel like something is missing in the docs here: [https://cloud.google.com/iot/docs/how-tos/mqtt-bridge#downloading_mqtt_server_certificates](https://cloud.google.com/iot/docs/how-tos/mqtt-bridge#downloading_mqtt_server_certificates)

At the end of the section 'Downloading MQTT server certificates' the sentence

> After downloading Google root CA certificates to your device, you can configure an MQTT client to authenticate the device, connect to the MQTT server, and communicate over the MQTT bridge.

'configure an MQTT client to authenticate the device' is a link to a section on the page that doesn't exist.

There's nothing else in the documentation or in the code samples that explains or demonstrates what to do with the Google root CA certificate. Is it even needed?

_Originally posted by @prenna in https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1563#issuecomment-574378763_

**Comment by fhinkel** [comment]
@jramirez0309 Thanks for raising the issue. I opened a bug internally so we can update our documentation. Appreciate you letting us know!
