### ISSUE TITLE
Hi, I am getting authentication error while running OCR in nodeJS

### ISSUE THREAD

**Issue by mamta-dhaka** [GoogleCloudPlatform/nodejs-docs-samples#1592]
Error: The incoming JSON object does not contain a client_email field     at JWT.fromJSON can someone please help , where to send the config from?

**Comment by fhinkel** [comment]
👋 @mamta-dhaka Thanks for opening the issue. Could you specify which example you are running? Thank you

**Comment by mamta-dhaka** [comment]
Hi, it got resolved now by giving config file in keyFilename.
const client = new vision.ImageAnnotatorClient({keyFilename: 'config.default.json'});
its not mentioned in the api docs, it would be helpful if mentioned,
Thank you

**Comment by fhinkel** [comment]
Awesome, great!
