### ISSUE TITLE
appengine example for analytics has faulty got call

### ISSUE THREAD

**Issue by luukvr** [GoogleCloudPlatform/nodejs-docs-samples#1598]
[https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/appengine/analytics/app.js](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/appengine/analytics/app.js)

In this example the data javascript object is directly inserted as an argument in the got.post() call. This does not function. I don't know if this way of calling was deprecated earlier. No post data will be sent to analytics this way. (tested with https://www.google-analytics.com/debug/collect)

Anyway solved this via the following changes:

Changing the data argument to an object with a body key containing a querystring like version of the data object.

`return got.post('https://www.google-analytics.com/collect', { 'body': Object.keys(data).map(key => key + '=' + data[key]).join('&') });`

**Comment by fhinkel** [comment]
@ace-n Could you have a look at this appengine problem. Thanks
