### ISSUE TITLE
Internal CI (run/hello-broken) - Tests failed

### ISSUE THREAD

**Issue by ricardolsmendes** [GoogleCloudPlatform/nodejs-docs-samples#1603]
I've noticed `Internal CI (run/hello-broken)` is breaking the CI pipeline and preventing unrelated changes to be merged. I'm not familiar with **Cloud Run** samples, but investigating the error logs generated for a PR I submitted earlier, it turns out _Broken resource uses the NAME override_ might be the culprit.

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/6f31b840cb314eccf59b9304c68ca80c85646c13/run/hello-broken/test/system.test.js#L79-L91

Would you be able to take a look at this?

Thanks!

**Comment by fhinkel** [comment]
We know that those tests fail, that's why they're optional for merging. 

@grayside any thought on when they'll be fixed?
