### ISSUE TITLE
testing: enable the Build Cop Bot

### ISSUE THREAD

**Issue by tbpg** [GoogleCloudPlatform/nodejs-docs-samples#1615]
Instructions here: https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop

**Comment by tbpg** [comment]
I installed the bot on the repo (first step of the instructions). We still need to call the `buildcop` binary to publish the test logs.

**Comment by fhinkel** [comment]
We need to update all the tests to generate xUnit xml output before we can turn on the bot.

**Comment by tbpg** [comment]
Snippet I've seen elsewhere:

```
npm test -- --reporter=xunit --reporter-option='output=sponge_log.xml'
```
