### ISSUE TITLE
Cannot get redis to work

### ISSUE THREAD

**Issue by ad-on-is** [GoogleCloudPlatform/nodejs-docs-samples#1624]
I'm trying to access the redis memorystore within an appengine nodjs application.
Trying several approaches, including the example provided here, throw different errors.

A more detailed description is on StackOverflow:
https://stackoverflow.com/questions/60655129/google-cloud-memorystore-redis-etimedout-in-app-engine

### Trying the example from here or my own example, with AppEngine Standard

When I include `vpc_access_connector` into the app.yaml, `gcloud beta app build` throws the following error.
`ERROR: (gcloud.beta.app.deploy) Error Response: [13] An internal error occurred.`

### Trying the example from here or my own example, with AppEngine Flex

When I include `env: flex` into app.yaml  `gcloud beta app build` throws no error, but my nodejs-script throws an `ETIMEDOUT` error.

**Comment by michaelawyu** [comment]
The reporter has resolved this issue himself/herself (mismatched region).
