### ISSUE TITLE
iot/manager/manager.js does not match current doc samples

### ISSUE THREAD

**Issue by bcoe** [GoogleCloudPlatform/nodejs-docs-samples#1628]
I noticed addressing another bug that we don't have:

```js
const responses = await iotClient.sendCommandToDevice(request);
```

Enclosed in an async function, this means that it will cause a failure if folks just copy and paste the code.

**Comment by hongalex** [comment]
Sorry, just seeing this. Is the issue that we shouldn't use async/await in samples?

**Comment by munkhuushmgl** [comment]
@bcoe I have created PR for this, PTaL [#330](https://github.com/googleapis/nodejs-iot/pull/330)

**Comment by munkhuushmgl** [comment]
@bcoe I think I have covered every async call in manager.js. If there is anything left, let me know.
