### ISSUE TITLE
Mocha test results not visible in sponge output

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/nodejs-docs-samples#1681]
The lack of mocha results makes it more difficult to evaluate test failures. This is presumably the result of switching to xunit output in a spong_log.xml file in #1665.

Based on some discussion in https://github.com/mochajs/mocha/pull/2184 to support multiple reporters at once, we should be able to restore console output without significant time overhead.

**Comment by fhinkel** [comment]
I'm wondering why sponge doesn't have the xml file as artifact cc @tbpg

**Comment by grayside** [comment]
When I look at the output, I still don't see the mocha test output. As a result I don't have an easy way to triage the test failure short of locally running the tests. I don't see any further artifacts.

Is there a reason why we can't pursue inline mocha output as part of the overall log output?

Examples include:
* https://g3c.corp.google.com/results/invocations/e5f9038d-e794-48dd-9c64-ead9524ee340/targets/cloud-devrel%2Fnodejs-docs-samples%2Frelease%2Frun%2Flogging-manual/log
* https://g3c.corp.google.com/results/invocations/e5f9038d-e794-48dd-9c64-ead9524ee340/targets/cloud-devrel%2Fnodejs-docs-samples%2Frelease%2Frun%2Flogging-manual/log

**Comment by grayside** [comment]
@fhinkel do you have thoughts on the best path forward? I have a number of issues in the run/logging-manual sample that I can't reproduce locally. I can only assume general flakiness without more information.

**Comment by fhinkel** [comment]
Was this not fixed with https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1711? There should be a separate log file in sponge.

**Comment by grayside** [comment]
1. In poking around, I only saw one log file in the artifacts and it was the same content as the main invocation log.
2. When you say "separate", is the fix that we're going to look in two different files for the end-to-end log output?

**Comment by fhinkel** [comment]
This tests has the correct output: 

https://g3c.corp.google.com/results/invocations/f1ac27e7-10cb-499b-821f-1d662112106a/targets

A lot of other CI runs show the error "XML file not found", and there's no way to see the output. 

Yes, the results from `mocha` are in a separate file (`${project}-sponge.xml`). The buildcop finds that file, otherwise it wouldn't open an issue, but Sponge doesn't find it for a lot of projects 🤔

**Comment by fhinkel** [comment]
This new test also has correct output: 

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1786

**Comment by grayside** [comment]
I'm not following how to read the test output logs for https://source.cloud.google.com/results/invocations/ef760242-50d0-4f75-8e88-efcf1e4ac4cb/targets/cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Frun%2Fhello-broken/tests. Not sure if that means there's a bug or if it's just a documentation challenge.

**Comment by bcoe** [comment]
👋 I've talked to @fhinkel about this in 1:1s, I don't have a clue why, but our sponge output seems to work on client libraries:

https://github.com/googleapis/nodejs-logging/issues/821

Perhaps an extra set of eyes on our config, and something might jump out at you, here's where it's configured:

https://github.com/googleapis/nodejs-logging/blob/master/.kokoro/system-test.sh#L38
