### ISSUE TITLE
Fix for MySQL Pooling Async Bug

### ISSUE THREAD

**Issue by Antzy** [GoogleCloudPlatform/nodejs-docs-samples#1710]
The NodeJS MySQL server.js code has an async Pool creation call createPool() without any await. So when it is immediately followed by ensureSchema() which runs a query on the pool, it throws an error as the pool isn't yet created:

> UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'query' of undefined

This is the same example on [Google Cloud Docs](https://cloud.google.com/sql/docs/mysql/manage-connections#pools-nodejs) and I assumed them to be correct and wasted 2 days on this thinking something wrong at my end. Please fix this so even any other call can ensure that pool object is properly created before call.

Link to code:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/cloud-sql/mysql/mysql/server.js

**Comment by Antzy** [comment]
Might not be the optimum way but thus is how I solved it:
```
var **createPoolPromise** = createPool();
// [END cloud_sql_mysql_mysql_create]

const ensureSchema = async () => {
  **await createPoolPromise;**
  // Wait for tables to be created (if they don't already exist).
  await pool.query(
    `CREATE TABLE IF NOT EXISTS votes
      ( vote_id SERIAL NOT NULL, time_cast timestamp NOT NULL,
      candidate CHAR(6) NOT NULL, PRIMARY KEY (vote_id) );`
  );
};
ensureSchema();
```

**Comment by fhinkel** [comment]
@Antzy 👋 Thanks for raising the issue. We'll fix it!

**Comment by shubha-rajan** [comment]
Thanks for raising the issue! I think using a middleware function to ensure pool creation might be a cleaner approach. The problem I see is that even if we await the promise to create the pool before each query, if table creation hasn't completed before those other queries, the other queries will fail. I think we should actually be awaiting the promise from `ensureSchema` before other queries. I opened  #1712 with a possible fix

**Comment by Antzy** [comment]
Thanks for looking into this. My schema is pretty much guaranteed to be already in place, so I was await-ing pool creation before every query. But you are right, much better to await ensureSchema instead.
