### ISSUE TITLE
docs bug: unclear whether has to be index.js or if main in package.json can point to another file

### ISSUE THREAD

**Issue by ORESoftware** [GoogleCloudPlatform/nodejs-docs-samples#1727]
I assume if we want to use a different entrypoint other than index.js, we can point to the index.js file using the "main" property in package.json? could this be added to the docs?

**Comment by fhinkel** [comment]
Yes, you can specify the entry point in package.json.

**Comment by ORESoftware** [comment]
this needs to be better documented pls?
