### ISSUE TITLE
Cloud SQL PostgreSQL: Hostname/IP does not match certificate's altnames

### ISSUE THREAD

**Issue by joshxyzhimself** [GoogleCloudPlatform/nodejs-docs-samples#1735]
I'm not getting this when using DigitalOcean's CA certificate, sweet jesus.

**Comment by joshxyzhimself** [comment]
Also tried creating a client cert then using the `ca`, `cert`, and `key` as parameters for NodeJS TLS `createSecureContext` function, this shit sucks

**Comment by joshxyzhimself** [comment]
Confirmed at https://github.com/db-migrate/node-db-migrate/issues/592

**Comment by fhinkel** [comment]
@kurtisvg Can you have a look or re-assign please. Thanks

**Comment by kurtisvg** [comment]
Hi @joshxyzhimself, 

From a quick look at the other issue it looks like you were able to resolve the problem yourself using these pages:

- https://cloud.google.com/sql/docs/postgres/authorize-ssl
- https://cloud.google.com/sql/docs/postgres/connect-admin-proxy

In the future, please note that this repo (and the issues on it) are are only used for tracking problems with the samples in it. You will likely be able to get faster or more specific help using the following resources:

- Asking a question with the [`cloudsql` tag on StackOverflow]( https://stackoverflow.com/questions/tagged/google-cloud-sql)
- Filing an issue in the [Cloud SQL issue tracker](https://issuetracker.google.com/issues/new?component=187202&template=0)
- For proxy related issues, opening an issue on the [Cloud SQL proxy github repo](https://github.com/GoogleCloudPlatform/cloudsql-proxy).
