### ISSUE TITLE
googlesapis 49 causes failing tests in storage transfer

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-docs-samples#1747]
See https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1784

**Comment by meredithslota** [comment]
I feel like this is actually @laylasells's domain.

**Comment by fhinkel** [comment]
@laylasells Could somebody look into this please? We're not 3 releases behind because we can't update any sample in the repo. Thanks!

**Comment by frankyn** [comment]
Hi @fhinkel, I'm taking a look. Apologies for the delay.

**Comment by frankyn** [comment]
The [example](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/storage-transfer/transfer.js#L27-L48) is inconsistent with how auth is currently documented at https://cloud.google.com/storage-transfer/docs/reference/rest/v1/transferJobs/list. I saw consistent failures of unauthorized failures. 

Then I found: https://github.com/googleapis/google-auth-library-nodejs/blob/41b0cb7b3dbae1b264b7de1cae82648c402d5cc3/CHANGELOG.md#v200

I was able to fix the broken tests locally after updating the auth initialization in #[1807](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1807). I want to make sure CI passes, but this might be the issue given auth is at 5.0.0 IIUC.
