### ISSUE TITLE
run/logging-manual: fix test failures from got method usage

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/nodejs-docs-samples#1759]
Buildcop has been opening a series of issues on the behavior of this sample, which has a history of flakiness (#1427). I cannot see if a more specific problem is present in the test output due to #1681, so will focus on blanket resilience improvements.

To consolidate effort, I'm going to mark the other issues as duplicates of this work.

**Comment by grayside** [comment]
After digging in further, I was able to reproduce a problem other than general flakiness: got v11 tightened a requirement around API usage and started throwing an error on the way the test implementation for this sample worked.

**Comment by fhinkel** [comment]
For `run`, we always run the `system-tests`, whether pre-submit or nightly release, see https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/752c8eb1f970b898d0eca1f62d9fd33b35df58c3/.kokoro/build-with-run.sh#L95
