### ISSUE TITLE
Presubmit for run/markdown-preview/editor is consistently  failing

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-docs-samples#1791]
https://source.cloud.google.com/results/invocations/32813175-423a-4ddf-9065-e7da9f31cea5/targets
https://source.cloud.google.com/results/invocations/e393577d-e306-4540-b4c9-141aea0747f4/targets

**Comment by grayside** [comment]
Note that a CL was submitted enabling Kokoro testing for a sample still in development. This will be fixed in #1752.

**Comment by grayside** [comment]
Not sure what priority this has, but adjusting the labels to indicate this bug only exists as a flag to indicate this test failure can be ignored.

**Comment by averikitsch** [comment]
I assume we will be able to merge this sample at least by next week. Though an option would be to revert the CL.

**Comment by grayside** [comment]
Duplicate of #1877 and #1878
