### ISSUE TITLE
Set up Org ID for samples system-tests.

### ISSUE THREAD

**Issue by mesmacosta** [GoogleCloudPlatform/nodejs-docs-samples#1802]
One of the features of Data Catalog is users are able to search across their Organization, in this PR: #1799. I created sample code showing how to search with the Org ID, for their system-tests I need to set up the Org ID for **kokoro**. Looking at other samples they all use the project id, do we have a org id that could be used by the sample system-tests?

**Comment by fhinkel** [comment]
As far as I can tell, the project we use for testing does not have an org set up.

**Comment by fhinkel** [comment]
This project should work, it has an organizationID set up, see https://github.com/googleapis/nodejs-security-center/blob/e50061a5f834a356b0221ff01d8de4ed02089260/.kokoro/samples-test.sh#L24
