### ISSUE TITLE
Auto-generate command instructions for README.md

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/nodejs-docs-samples#181]
Once all our samples are converted to use `yargs` (or some other arg-parsing library that auto-generates command-line usage instructions), we should consider having a script insert those instructions into our Markdown documentation automatically (instead of manually cutting-and-pasting things).

Thoughts?

**Comment by jmdobry** [comment]
Things the script needs to know, per product:

* Product name
* Product description
* Setup section
  * Link to any general prerequisites and general "how to run a sample" instructions
  * Extra steps, either defined directly in metadata, or metadata points to a markdown file to be included
* Samples section
  * Title of sample
  * Links to where it's used in the documentation
  * Links to source code
  * Instructions on how to run it
    * Defined instructions in metadata
    * Specify markdown to be included
    * Specify command to be executed, using the resulting stdout as the instructions

Put metadata in `.samples.json` file in sample directory. To generate README in that directory, run the script _in_ that directory.

**Comment by jmdobry** [comment]
Done.
