### ISSUE TITLE
run/hello-broken Test Fails

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/nodejs-docs-samples#1817]
The `run/hello-broken` tests fail on `master`.

This failure makes this PRs's test fail: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1809

I'm not sure what's going on and don't have access to logs. It makes changes to unrelated PRs fail.

CC: @grayside

**Comment by fhinkel** [comment]
👋 Hi @grant Thanks for opening an issue. We are aware that those tests are failing. It is explicitely called out in the contributor guide. 

The logs are public. If you can't access them, can you please file a bug with Sponge. Thanks!

**Comment by grayside** [comment]
Somehow, I was not aware this test was still failing. Opening to address. The problem is b/156023473.

**Comment by grant** [comment]
Thanks for re-opening.

Even though this is a known issue by some people, I would still like to be able to track the state of the issue via some bug. I don't always re-check contribution guides before making PRs.
