### ISSUE TITLE
run/markdown-preview/editor Test Fails

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/nodejs-docs-samples#1818]
The `run/markdown-preview/editor` tests fail on `master`.

This failure makes this PRs's test fail: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1809

I'm not sure what's going on and don't have access to logs. It makes changes to unrelated PRs fail.

CC: @grayside

**Comment by fhinkel** [comment]
👋 Hi @grant Thanks for opening an issue. We are aware that those tests are failing. It is explicitely called out in the contributor guide. 

The logs are public. If you can't access them, can you please file a bug with Sponge. Thanks!
