### ISSUE TITLE
run/markdown-preview/renderer Test Fails

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/nodejs-docs-samples#1819]
The run/markdown-preview/renderer tests fail on master.

This failure makes this PRs's test fail: #1809

I'm not sure what's going on and don't have access to logs. It makes changes to unrelated PRs fail.

CC: @grayside

**Comment by grayside** [comment]
This is a test enabled for a PR still in progress, the failure while annoying should be non-blocking.

**Comment by grant** [comment]
Yup. This issue can just track it then.

**Comment by fhinkel** [comment]
👋 Hi @grant Thanks for opening an issue. We are aware that those tests are failing. It is explicitely called out in the contributor guide. 

The logs are public. If you can't access them, can you please file a bug with Sponge. Thanks!

**Comment by grant** [comment]
Can we still keep the issue open? I don't check the contributing guides for issues that often and usually use GitHub issues for notifications and bug filing.
