### ISSUE TITLE
run/events-storage/README needs updates

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/nodejs-docs-samples#1903]
[run/events-storage/README](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/run/events-storage/README.md) needs the env var set up to be used for the trigger cmd args.

**Comment by grant** [comment]
Not sure of the specific missing trigger cmd arg env var.
Fixed with https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1904.
