### ISSUE TITLE
What is the DB_SOCKET_PATH

### ISSUE THREAD

**Issue by Stegosource** [GoogleCloudPlatform/nodejs-docs-samples#1913]
I see some examples for connecting to Cloud SQL that reference `process.env.DB_SOCKET_PATH`

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/cloud-sql/postgres/knex/server.js#L70

And in the example code: https://cloud.google.com/sql/docs/postgres/connect-functions

But I can't find anywhere what this variable actually is. I'm not sure where to actually get that info from.

**Comment by kurtisvg** [comment]
Hi @Stegosource,

If you take a look at the [README](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/cloud-sql/postgres/knex/README.md#launch-proxy-with-unix-domain-socket), you'll see that the value is the location of the Unix domain socket being used to connect to your Cloud SQL instance. 

The actual location of this socket depends on where your code is running; Locally it depends on where you pointed the proxy, but when deployed to Cloud Functions it'll be at `/cloudsql/INSTANCE_CONNECTION_NAME`. Check out the [Connecting from Cloud Functions to Cloud SQL](https://cloud.google.com/sql/docs/postgres/connect-functions#connecting_to) for specifics:

> Once correctly configured, you can connect your service to your Cloud SQL instance's unix domain socket using the format: `/cloudsql/INSTANCE_CONNECTION_NAME`.

**Comment by Stegosource** [comment]
Hey @kurtisvg.

Thanks for the response. Sorry for the silly question, I just could not figure out what it meant. I have things working fine locally, but deployed, I was not sure what I needed. Your comment "when deployed to Cloud Functions it'll be at /cloudsql/INSTANCE_CONNECTION_NAME" actually clears it up for me. Thanks.
