### ISSUE TITLE
functions: update samples to Node 12

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/nodejs-docs-samples#1925]
GCF Node 12 went beta.

We should update the sample to use Node 12 syntax and update the engine target to Node 12+.

Related:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1917

**Comment by grant** [comment]
CC @ace-n

**Comment by ace-n** [comment]
The engine update is usually pretty trivial.

AFAIK, there are no major syntax changes we should be taking advantage of - but perhaps it's worth confirming that with @fhinkel or @bcoe.

**Comment by fhinkel** [comment]
@ace-n didn't we agree to have the samples match the GA version? While 12 is beta, we should not default to 12.

**Comment by ace-n** [comment]
@fhinkel - good catch, thanks!

@grant - let's hold off on this (or confine our changes to a separate
`node12` branch) until the Node 12 *runtime* is GA.

**Comment by ace-n** [comment]
Thanks to #1962 and #1964 (which fixed the Firebase samples), the existing samples should all work with Node 12.

We'll have to wait on updating `ENGINES` until Node 12 is GA.

**Comment by fhinkel** [comment]
ping @grant @ace-n. Has anybody updated the engine fields yet? Or do we wait until GCP deprecates the Node10 runtime?

**Comment by grant** [comment]
We need a GA runtime per comment above

**Comment by fhinkel** [comment]
GCF Node.js 12 is GA.

**Comment by grant** [comment]
Updating to 12 should be good to go.
