### ISSUE TITLE
Add a sample using NestJS

### ISSUE THREAD

**Issue by jdnichollsc** [GoogleCloudPlatform/nodejs-docs-samples#1932]
Hello folks,
Can you add a sample with **NestJS**? Check my template here: https://github.com/proyecto26/MyAPI

Thanks in advance!

**Comment by fhinkel** [comment]
👋 Hi @jdnichollsc, thanks for opening an issue. This repository is only for samples used in our official documentation on cloud.google.com. If you wrote a great sample but it is not used in Google's official documentation, there are better suited places to publish it such as a [community tutorial](https://cloud.google.com/community/).
