### ISSUE TITLE
The tutorial "Triggering a DAG with Node.JS and Google Cloud Functions" uses a different path for composer-storage-trigger

### ISSUE THREAD

**Issue by kyleschiess** [GoogleCloudPlatform/nodejs-docs-samples#1970]
The tutorial uses "nodejs-docs-samples/functions/composer-storage-trigger" while it is now "nodejs-docs-samples/composer/functions/composer-storage-trigger"

**Comment by fhinkel** [comment]
👋 @kyleschiess Thanks for reporting the issue. @leahecole Can you update the codelab please. Thanks you.

**Comment by fhinkel** [comment]
Here's the wrong link: https://codelabs.developers.google.com/codelabs/triggering-dag-gcf#3

**Comment by leahecole** [comment]
Submitted internal change 346158327

**Comment by leahecole** [comment]
fixed + published
