### ISSUE TITLE
Config Confirmation

### ISSUE THREAD

**Issue by leosan902** [GoogleCloudPlatform/nodejs-docs-samples#1975]
Sometimes when i send a config, and my device receive it, the confirmation icon dont apear on the site.

**Comment by leosan902** [comment]
After debugging, i need to put more information on this error:
- It happens after reconnection

**Comment by sofisl** [comment]
Hi @leosan902, would you mind including some more information about your issue, including:

(i) what sample/API this is related to,
(ii) code associated with it, 
(iii) what you're getting, 
(iv) what you expect to see,
(v) your current environment.

Thanks!

**Comment by leosan902** [comment]
I found the reason of the error i wasnt sending the qos in the new subscription and i wasnt receiving an error, for some reason this bugg was occurring

**Comment by sofisl** [comment]
Alright. Thanks for the update! I'll close for now.
