### ISSUE TITLE
functions/billing: test failure preventing PR merges #1985

### ISSUE THREAD

**Issue by engelke** [GoogleCloudPlatform/nodejs-docs-samples#1988]
This test appears to have been failing for at least six months. Latest failure log has this:

    1) "before all" hook in "{root}":
     Error: Invalid Credentials
      at Gaxios._request (node_modules/gaxios/build/src/gaxios.js:89:23)
      at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by grant** [comment]
I have observed this issue too.

I'd suggest disabling the test until it's more reliable.

**Comment by ace-n** [comment]
Test is no longer required. I'm investigating a fix in #1990.
