### ISSUE TITLE
lib request is not supported

### ISSUE THREAD

**Issue by joelviel** [GoogleCloudPlatform/nodejs-docs-samples#2001]
Hi,

Can you update this example https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/iot/http_example with a maintained library for http requests ?

Thanks

**Comment by fhinkel** [comment]
Hi @joelviel 👋 . Thanks for raising the issue. @hongalex would you have time to look into this? Thanks

**Comment by hongalex** [comment]
Upon discussion with @fhinkel, we will update the sample to use `node-fetch`.
