### ISSUE TITLE
chore: snippet-bot full scan

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/nodejs-docs-samples#2008]
## snippet-bot scan result
Life is too short to manually check unmatched region tags.
Here is the result:
- [ ] [cloud-sql/mysql/mysql/server.js:115](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/00031fc/cloud-sql/mysql/mysql/server.js#L115), tag `cloud_sql_mysql_mysql_create` doesn't have a matching start tag

---
Report generated by [snippet-bot](https://github.com/apps/snippet-bot).
If you find problems with this result, please file an issue at:
https://github.com/googleapis/repo-automation-bots/issues.

**Comment by fhinkel** [comment]
Thanks! @shubha-rajan can you look into this since it's SQL related? Thanks.
