### ISSUE TITLE
App Engine Cloud SQL tests are failing

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/nodejs-docs-samples#2014]
Since Oct 16th, the SQL and postgreSQL sample tests have been failing.

[Test fusion example](https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Fappengine%2Fnode10%2Fcloudsql)

**Comment by shubha-rajan** [comment]
It looks like only the appengine-cloudsql tests are failing. The tests for the cloud sql samples are working: 
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Fcloudsql-mysql
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Fcloudsql-postgres
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Fcloudsql-sqlserver

@ace-n is making the failing checks non-required while we figure out what's going on.

**Comment by ace-n** [comment]
I've marked the associated GitHub checks as non-required, but don't have bandwidth to investigate further this week.

@engelke is this something you can look into?

**Comment by fhinkel** [comment]
@engelke @shubha-rajan Who is looking at those test failure?

**Comment by engelke** [comment]
From what I can see, it seems the tests are working for Node 10 and 12. The failures for Node 8 seem to be test configuration, not the sample code itself, and have been happening since June. Somebody familiar with the Kokoro Node test configuration will have to look into this.

**Comment by averikitsch** [comment]
The tests are now passing though there doesn't seem to be any changes for them breaking or passing?
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Fappengine%2Fnode10%2Fcloudsql
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Fappengine%2Fnode10%2Fcloudsql_postgresql
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Fappengine%2Fnode12%2Fcloudsql
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Fappengine%2Fnode12%2Fcloudsql_postgresql

@fhinkel / @kvg the internal configuration for release doesn't look set up correctly therefore those tests are failing
https://fusion.corp.google.com/runanalysis/buildlogs/prod:cloud-devrel%2Fnodejs-docs-samples%2Frelease%2Fappengine%2Fcloudsql_postgresql/prod:cloud-devrel%2Fnodejs-docs-samples%2Frelease%2Fappengine%2Fcloudsql_postgresql/KOKORO/bbe618f7-42d1-4c6a-8183-57ed30f01ddc/1604633108215/build%20%23869/Targets

**Comment by fhinkel** [comment]
Thanks for digging into this everybody! We probably don't want to run Node 8 anymore in the appengine test environment. 

@michaelawyu   Can you take over as per CODEOWNERS you're responsible for `appengine`? Thanks

**Comment by michaelawyu** [comment]
Fix sent: cl/342055399.

This bug occurs as the `release` series of Kokoro tests is configured to use Node 8 config files, which no longer exist. The CL now patches the config to use Node 12 files instead.
