### ISSUE TITLE
Functions/Billing tests are failing

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/nodejs-docs-samples#2015]
[Test Fusion](https://fusion.corp.google.com/runanalysis/info/prod%3Acloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Ffunctions%2Fbilling/prod%3Acloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Ffunctions%2Fbilling/KOKORO/87aaabf8-0c18-4c01-8529-21998ae014ed/0/prod%3Acloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Ffunctions%2Fbilling/Targets)

**Comment by ace-n** [comment]
I was able to reproduce this (permissions error), but it mysteriously went away during my attempts to fix it.

(It's possible parallel test runs interfered with each other, as they all use a [single] GCP project as a test fixture. Try running them again, and reopen this if the error persists?)
