### ISSUE TITLE
Unused (and untested) functions in run/idp-sql

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-docs-samples#2047]
There are some unused functions in `run/idp-sql`. 
Some are not covered by region tags so we should be able to delete them. Those inside region tags should have test coverage and thus not show up as unused. 

```
$ npm run lint
nodejs-docs-samples/run/idp-sql/static/config.js
  2:7  warning  'config' is assigned a value but never used  no-unused-vars

nodejs-docs-samples/run/idp-sql/static/firebase.js
  22:10  warning  'signIn' is defined but never used  no-unused-vars
  40:16  warning  'vote' is defined but never used    no-unused-vars
 ```

**Comment by averikitsch** [comment]
All of these variables and functions are used but organized specifically into different files for client side code. Can I opt these files out?

**Comment by fhinkel** [comment]
We can opt out (which we're doing right now with `.eslintrc` in the `run/idp-sql` folder. Thanks for clarifying, I didn't realize they're used in fronttend code. Ideally, we would have tests for those functions, but then we'd need a bundler and it would probably convolute the sample too much.
