### ISSUE TITLE
run/* CI should be required or deleted

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-docs-samples#2055]
* Internal CI (run/hello-broken)
* Internal CI (run/helloworld) 
* Internal CI (run/idp-sql)
* Internal CI (run/markdown-preview/editor)
* Internal CI (run/markdown-preview/renderer)

CI for those two tests is not required to merge a PR. Please mark tests as required or delete the tests.

**Comment by averikitsch** [comment]
Hi @fhinkel, can you link how to make these required?

**Comment by fhinkel** [comment]
Settings -> Branches -> Edit branch protection for master. Do you have permissions to change it or should I mark them all as required?

**Comment by averikitsch** [comment]
@fhinkel I don't have permission, can you mark all `run/` samples as required?

**Comment by fhinkel** [comment]
Done!
