### ISSUE TITLE
[Question] Pub/Sub Cloud Run example - Return code.

### ISSUE THREAD

**Issue by Normynator** [GoogleCloudPlatform/nodejs-docs-samples#2066]
Hello,

I wondering: what's the point of returning status code 400 on invalid or no message?

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/4548f63d3edb3da80296cc76e98536ffd0495ab6/run/pubsub/app.js#L21
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/4548f63d3edb3da80296cc76e98536ffd0495ab6/run/pubsub/app.js#L27

Is there any benefit if Pub/Sub keeps retrying to send events which are considered invalid in the first place?

**Comment by averikitsch** [comment]
Hi @Normynator, these 2 checks are to make sure the program doesn't throw an exception and minimal checks for bad actors. We are assuming if there is no request body or Pub/Sub message in the request body that this isn't a request from Pub/Sub; therefore we should respond with 400 Bad Request. You are correct in if the request was a Pub/Sub message that we don't want to retry, we shouldn't respond with a 400.
