### ISSUE TITLE
Update endpoints/getting-started-grpc to use @grpc/grpc-js

### ISSUE THREAD

**Issue by chalin** [GoogleCloudPlatform/nodejs-docs-samples#2076]
The [grpc package](https://www.npmjs.com/package/grpc) is deprecated. Consider updating the endpoint example to make use of [@grpc/grpc-js](https://www.npmjs.com/package/@grpc/grpc-js) -- if it is now sufficiently feature complete.

cc @murgatroid99 @nicolasnoble

**Comment by n-machiavelli** [comment]
Hi there. Can someone assign this to me ? Thanks!
