### ISSUE TITLE
Missing iot folder in master branch

### ISSUE THREAD

**Issue by tanchinluh** [GoogleCloudPlatform/nodejs-docs-samples#2082]
It seems like the master branch is missing iot folders. Thanks.

**Comment by fhinkel** [comment]
@tanchinluh 👋 . Thanks for raising the issue. Where do you see the `iot` folder being referenced from? We moved to samples to the corresponding client library https://github.com/googleapis/nodejs-iot/tree/master/samples.  

cc @gguuss

**Comment by tanchinluh** [comment]
Hi @fhinkel , the folder and the samples were referred by the quick start tutorial. https://cloud.google.com/iot/docs/quickstart . perhaps you might want to update the doc. 

thanks.

regards,
CL

**Comment by fhinkel** [comment]
Thank you, we updated the doc.
