### ISSUE TITLE
Archive functions/tokenservice sample

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-docs-samples#2107]
As discussed via email, we want to move this sample out of `nodejs-docs-samples` and archive it. 

- [ ] Move code out of nodejs-docs-samples/functions/tokenservice/
- [ ] Delete matching .kokoro files on GitHub
- [ ] Delete matching .kokoro files internally
- [ ] Update CODEOWNERS

**Comment by ricalo** [comment]
Requested review to @fhinkel / @ace-n to take care of third item: *Delete matching .kokoro files internally*.
