### ISSUE TITLE
run(idp-sql): Unhandled promise rejection

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/nodejs-docs-samples#2108]
## Actual

Trying to get this working locally using the Cloud SQL proxy, I ran into this error:

```
(node:1) UnhandledPromiseRejectionWarning: Error: connect ENOENT /cloudsql/<connection name>/.s.PGSQL.5432
     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I do not have a clear action item to help troubleshoot this problem.

## Expected

Handle this rejection and provide actionable guidance on what the developer can do.

**Comment by grayside** [comment]
I'm going to investigate this problem a bit more.

**Comment by averikitsch** [comment]
Could it be updated to `main().catch((e) => console.log(e))` in `index.js`?

**Comment by grayside** [comment]
The general purpose handling is pretty simple, but doesn't really provide much value: either way the developer gets the raw error. What we really want is to provide the actionable guidance.

```js
process.on('unhandledRejection', error => {
  // Will print "unhandledRejection err is not defined"
  console.log('unhandledRejection', error.message);
});
```

Narrowing this down, here's the difference between handling the problem and passing through the error message:

```
error: Cloud SQL create table:connect ENOTDIR /cloudsql/adamross-svls-kibble:us-central1:f/.s.PGSQL.5432
{"message":"Error while connecting to the Cloud SQL database. Check that your username and password are correct, that the Cloud SQL proxy is running (locally), and that the database/table exists and is ready for use: Error: connect ENOTDIR /cloudsql/adamross-svls-kibble:us-central1:f/.s.PGSQL.5432","level":"error","severity":"error","timestamp":"2020-12-10T18:51:24.243Z"}
```

The next thing is to confirm my database credentials work.

**Comment by grayside** [comment]
This specific problem is the result of pointing a Postgres library to a MySQL database instance. I think going back to the original comment and adding more actionable error handling note, perhaps reusing the existing text, would be the best resolution.
