### ISSUE TITLE
gcloud app logs read ERROR: gcloud crashed (ValueError): time data does not match format

### ISSUE THREAD

**Issue by goh-chunlin** [GoogleCloudPlatform/nodejs-docs-samples#213]
Issue running command [gcloud app logs read].

What steps will reproduce the problem?
I'm encountering an error that I've never seen before when I run "gcloud app logs read" after deploying my app using "gcloud app deploy".

What is the expected output? What do you see instead?
This is the error message shown: ERROR: gcloud crashed (ValueError): time data '2016-09-18T12:19:50Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

Please provide any additional information below.

Trace:
gcloud_main.py:130
 gcloud_cli.Execute()
calliope\cli.py:737
 self._HandleAllErrors(exc, command_path_...
calliope\cli.py:715
 resources = args.calliope_command.Run(cl...
calliope\backend.py:1538
 resources = command_instance.Run(args)
lib\surface\app\logs\read.py:83
 lines.append(printer.Format(entry))
api_lib\app\logs_util.py:141
 time = datetime.datetime.strptime(timest...
platform\bundledpython\lib\_strptime.py:325
 (data_string, format))
ValueError: time data '2016-09-18T12:37:21Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

Installation information:

Google Cloud SDK [126.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]]
Python Location: [C:\Users\chunlin\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\python.exe]
Site Packages: [Disabled]

Installation Root: [C:\Users\chunlin\AppData\Local\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  bundled-python: [2.7.10]
  bq-win: [2.0.24]
  core: [2016.09.12]
  core-win: [2016.08.05]
  gcloud: []
  windows-ssh-tools: [2016.05.13]
  gsutil: [4.21]
  bq: [2.0.24]
  powershell: [0.1.6]
  gsutil-win: [4.20]
[output truncated]

**Comment by jmdobry** [comment]
Hi @goh-chunlin 

Problems with the google cloud sdk should be reported [here](https://code.google.com/p/google-cloud-sdk/issues/entry). Thanks!
