### ISSUE TITLE
Schedule Instance tests are broken

### ISSUE THREAD

**Issue by chrisjensen** [GoogleCloudPlatform/nodejs-docs-samples#2153]
The tests in [functions/scheduleinstance/](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/functions/scheduleinstance/test/index.test.js) are incorrect.

Main two problems are:

1) They're frequently missing an `await` when calling the cloud function
2) The input data for the assert calls the stubbed function directly, so completely bypasses testing any behaviour of the cloud function

**Comment by ace-n** [comment]
@chrisjensen thanks for the issue! @askmeegs owns this sample, so I'll ask them to take a look.

(Side note: we also need to update `CODEOWNERS`.)
