### ISSUE TITLE
Unable to record speech

### ISSUE THREAD

**Issue by phanikumar1210** [GoogleCloudPlatform/nodejs-docs-samples#219]
I am newbie to this Google and its API's I was able to decode the sample raw files. But I was unable to use speech recognition from microphone and I am getting the following error on my run. 

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn rec ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:456:3
```

Could you please let me know what is the exact issue.

**Comment by jmdobry** [comment]
We just published new Node.js Google Cloud Speech API samples a few hours ago. Give them a try: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/speech

**Comment by phanikumar1210** [comment]
I am getting the same error with this code as well. I think there is an issue with microphone recognization do I need to make any changed to the settings. I am using windows 8.1.

**Comment by jmdobry** [comment]
Looking at https://github.com/gillesdemey/node-record-lpcm16 (which is what the microphone recording sample uses), it looks like you need to have [SoX](http://sox.sourceforge.net/) installed on your system. For windows, it looks like you have to [download a binary](http://sourceforge.net/projects/sox/files/latest/download)

**Comment by phanikumar1210** [comment]
I have installed it by having a look at the module requirements. But I was unable to use perform recording.

**Comment by damienromito** [comment]
launch `brew install sox`  on macOs fix it for me

**Comment by phanikumar1210** [comment]
I am working with windows operating system and I have installed sox on it but I am facing the same error. I have also tried using **node-record-lpcm16** module there is a problem with that module itself.

**Comment by jmdobry** [comment]
@phanikumar1210 Have you opened an issue on the `node-record-lpcm16` repository?

**Comment by phanikumar1210** [comment]
There is an existing issue on it without response. Do we have any other source which is working on windows. On which platforms is this code got tested. Does this code work on Ubuntu platform.

**Comment by stshume** [comment]
Did anyone get this working on the Windows OS?

**Comment by freund17** [comment]
I think i found a fix.
See my comment over at https://github.com/gillesdemey/node-record-lpcm16/issues/8.

**Comment by youjinyano** [comment]
When deploying it to Heroku, what should I do to install sox there?
