### ISSUE TITLE
Where is the iot/mqtt_example

### ISSUE THREAD

**Issue by aternatedimension** [GoogleCloudPlatform/nodejs-docs-samples#2191]
hi i am trying to fire up the mqtt protocols using google cloud platform. but i dont see iot/mqtt_example. is there anyway i can get my hands on it.

**Comment by fhinkel** [comment]
Hi @aternatedimension, The IoT samples moved to  https://github.com/googleapis/nodejs-iot/tree/master/samples, including the mqtt example.

**Comment by aternatedimension** [comment]
Hi fhinkel, thanks! I'll try finding it.
