### ISSUE TITLE
Service Unavailable of Websocket project

### ISSUE THREAD

**Issue by TonyChiangUSA** [GoogleCloudPlatform/nodejs-docs-samples#2298]
Followed this wiki but got an error when I open the url given by cloud run, it says:

"Error: connect ECONNREFUSED 127.0.0.1:6379
TCPConnectWrap.afterConnect (net.js:1148)"

**Comment by sofisl** [comment]
Hi @TonyChiangUSA, could you provide steps (including any code snippets) to reproduce the error? Thanks in advance.

**Comment by sofisl** [comment]
I also attempted to recreate the tutorial, and I got stuck at the final step, here is the output in Cloud Build:

```
starting build "a019ad85-4d2e-4780-bc4a-16ff668d1af5"
Already have image (with digest): gcr.io/cloud-builders/docker
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /workspace/Dockerfile: no such file or directory
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
```

I will attempt to take a look at this later in the week, thanks for reporting @TonyChiangUSA

**Comment by sofisl** [comment]
Filed b/195133753 internally.

**Comment by averikitsch** [comment]
> Followed this wiki but got an error when I open the url given by cloud run, it says:
> 
> "Error: connect ECONNREFUSED 127.0.0.1:6379
> TCPConnectWrap.afterConnect (net.js:1148)"

Hi @TonyChiangUSA, it looks like you may have forgotten to set the `REDISHOST` env var:
```
 export REDISHOST=$(gcloud redis instances describe INSTANCE_ID --region REGION --format "value(host)")
gcloud beta run deploy chat-app --source . \
    --vpc-connector CONNECTOR_NAME \
    --allow-unauthenticated \
    --timeout 3600 \
    --service-account chat-identity \
    --update-env-vars REDISHOST=$REDISHOST
```

**Comment by averikitsch** [comment]
Please reopen if you continue to experience this issue.
