### ISSUE TITLE
Crashes on start: Error: Module version mismatch. Expected 46, got 14.

### ISSUE THREAD

**Issue by GeoffreyPlitt** [GoogleCloudPlatform/nodejs-docs-samples#230]
I'm trying to run the speech samples and I got the error above, with Node v4.6.0. I had done "npm install".

What else is necessary for this to run properly?

**Comment by jmdobry** [comment]
I would try deleting the `node_modules/` folder and then re-running `npm install`. `Error: Module version mismatch` typically happens when NPM installed (compiled) a dependency using one version of Node.js, and then you tried to run it using another version of Node.js.

**Comment by GeoffreyPlitt** [comment]
Fixed! How dumb. Thanks!

**Comment by jmdobry** [comment]
Yeah, I wish they'd print a nicer error message.
