### ISSUE TITLE
`console.error(new Error(''))` won't be sent to Cloud Error Reporting automatically

### ISSUE THREAD

**Issue by ZYinMD** [GoogleCloudPlatform/nodejs-docs-samples#2317]
It seems [this line](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/functions/helloworld/index.js#L98) is incorrect.

I tested in a deployed cloud function: if I do `console.error(new Error('hello world'))`, it won't show up in console -> Error Reporting. But if I use the `@google-cloud/error-reporting` library to report errors, it'll show.

If I'm right, then the [doc](https://cloud.google.com/functions/docs/monitoring/error-reporting) is mistaken?

**Comment by tmatsuo** [comment]
It seems like @ace-n added that line.

@ZYinMD thinks that `console.error(new Error('hello world'))` is not captured by Cloud Error Reporting.
