### ISSUE TITLE
Microservices Sample

### ISSUE THREAD

**Issue by travisoneill** [GoogleCloudPlatform/nodejs-docs-samples#233]
I just finished making a demo app w/ multiple services for the Python flexible environment.  Would you guys like a similar demo for Node?

https://github.com/GoogleCloudPlatform/python-docs-samples/pull/509

**Comment by jmdobry** [comment]
Sure!

**Comment by taras** [comment]
I would love to see an example of this as well. 

How do dependencies work in this example? Does each microservice have it's own dependencies or are they shared by the default app?

**Comment by jmdobry** [comment]
Moved to GoogleCloudPlatform/community#227
