### ISSUE TITLE
Does `transaction.get` guarantees the same order as the keys?

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/nodejs-docs-samples#234]
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/datastore/concepts.js#L1048

I don't think `transaction.get` guarantees that the order of the result is the same as the given keys. Please close if it does, but please fix this otherwise.

**Comment by jmdobry** [comment]
As far as I can tell, the order of the entities in the response is undefined and has no relation to the order of the keys in the input. I'll have to fix the sample.

See: https://cloud.google.com/datastore/docs/reference/rpc/google.datastore.v1beta3#google.datastore.v1beta3.LookupResponse
