### ISSUE TITLE
Unable to do npm install for Speech on MacOS

### ISSUE THREAD

**Issue by jcastill0** [GoogleCloudPlatform/nodejs-docs-samples#248]
npm install

> grpc@1.0.1 install /Users/jcastillo/dev/git/speech/nodejs-docs-samples/speech/node_modules/grpc
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.0.1/node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.0.1 and node@7.0.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/homebrew/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/homebrew/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/homebrew/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/homebrew/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/homebrew/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/homebrew/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/homebrew/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/homebrew/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/homebrew/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/homebrew/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/homebrew/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/homebrew/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/usr/local/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/local/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/local/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/usr/local/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "/usr/local/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 77, in CalculateVariables
    import gyp.generator.xcode as xcode_generator
  File "/usr/local/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode.py", line 7, in <module>
    import gyp.xcodeproj_file
  File "/usr/local/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcodeproj_file.py", line 152, in <module>
    _new_sha1 = hashlib.sha1
AttributeError: 'module' object has no attribute 'sha1'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/homebrew/Cellar/node/7.0.0/bin/node" "/usr/local/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/jcastillo/dev/git/speech/nodejs-docs-samples/speech/node_modules/grpc/src/node/extension_binary/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/jcastillo/dev/git/speech/nodejs-docs-samples/speech/node_modules/grpc/src/node/extension_binary"
gyp ERR! cwd /Users/jcastillo/dev/git/speech/nodejs-docs-samples/speech/node_modules/grpc
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp configure --fallback-to-build --module=/Users/jcastillo/dev/git/speech/nodejs-docs-samples/speech/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/Users/jcastillo/dev/git/speech/nodejs-docs-samples/speech/node_modules/grpc/src/node/extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jcastillo/dev/git/speech/nodejs-docs-samples/speech/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 15.6.0
node-pre-gyp ERR! command "/usr/local/homebrew/Cellar/node/7.0.0/bin/node" "/Users/jcastillo/dev/git/speech/nodejs-docs-samples/speech/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/jcastillo/dev/git/speech/nodejs-docs-samples/speech/node_modules/grpc
node-pre-gyp ERR! node -v v7.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp configure --fallback-to-build --module=/Users/jcastillo/dev/git/speech/nodejs-docs-samples/speech/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/Users/jcastillo/dev/git/speech/nodejs-docs-samples/speech/node_modules/grpc/src/node/extension_binary' (1)
nodejs-docs-samples-speech@0.0.1 /Users/jcastillo/dev/git/speech/nodejs-docs-samples/speech
├─┬ mocha@3.1.2 
│ ├── browser-stdout@1.3.0 
│ ├─┬ commander@2.9.0 
│ │ └── graceful-readlink@1.0.1 
│ ├─┬ debug@2.2.0 
│ │ └── ms@0.7.1 
│ ├── diff@1.4.0 
│ ├── escape-string-regexp@1.0.5 
│ ├─┬ glob@7.0.5 
│ │ ├── fs.realpath@1.0.0 
│ │ ├─┬ inflight@1.0.6 
│ │ │ └── wrappy@1.0.2 
│ │ ├── inherits@2.0.3 
│ │ ├─┬ minimatch@3.0.3 
│ │ │ └─┬ brace-expansion@1.1.6 
│ │ │   ├── balanced-match@0.4.2 
│ │ │   └── concat-map@0.0.1 
│ │ ├── once@1.3.3 
│ │ └── path-is-absolute@1.0.1 
│ ├── growl@1.9.2 
│ ├── json3@3.3.2 
│ ├─┬ lodash.create@3.1.1 
│ │ ├─┬ lodash._baseassign@3.2.0 
│ │ │ ├── lodash._basecopy@3.0.1 
│ │ │ └─┬ lodash.keys@3.1.2 
│ │ │   ├── lodash._getnative@3.9.1 
│ │ │   ├── lodash.isarguments@3.1.0 
│ │ │   └── lodash.isarray@3.0.4 
│ │ ├── lodash._basecreate@3.0.3 
│ │ └── lodash._isiterateecall@3.0.9 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ └─┬ supports-color@3.1.2 
│   └── has-flag@1.0.0 
├─┬ node-record-lpcm16@0.1.4 
│ └── lodash@2.4.2 
└─┬ yargs@6.3.0 
  ├── camelcase@3.0.0 
  ├─┬ cliui@3.2.0 
  │ ├─┬ strip-ansi@3.0.1 
  │ │ └── ansi-regex@2.0.0 
  │ └── wrap-ansi@2.0.0 
  ├── decamelize@1.2.0 
  ├── get-caller-file@1.0.2 
  ├─┬ os-locale@1.4.0 
  │ └─┬ lcid@1.0.0 
  │   └── invert-kv@1.0.0 
  ├─┬ read-pkg-up@1.0.1 
  │ ├─┬ find-up@1.1.2 
  │ │ ├── path-exists@2.1.0 
  │ │ └─┬ pinkie-promise@2.0.1 
  │ │   └── pinkie@2.0.4 
  │ └─┬ read-pkg@1.1.0 
  │   ├─┬ load-json-file@1.1.0 
  │   │ ├── graceful-fs@4.1.10 
  │   │ ├─┬ parse-json@2.2.0 
  │   │ │ └─┬ error-ex@1.3.0 
  │   │ │   └── is-arrayish@0.2.1 
  │   │ ├── pify@2.3.0 
  │   │ └─┬ strip-bom@2.0.0 
  │   │   └── is-utf8@0.2.1 
  │   ├─┬ normalize-package-data@2.3.5 
  │   │ ├── hosted-git-info@2.1.5 
  │   │ ├─┬ is-builtin-module@1.0.0 
  │   │ │ └── builtin-modules@1.1.1 
  │   │ ├── semver@5.3.0 
  │   │ └─┬ validate-npm-package-license@3.0.1 
  │   │   ├─┬ spdx-correct@1.0.2 
  │   │   │ └── spdx-license-ids@1.2.2 
  │   │   └── spdx-expression-parse@1.0.4 
  │   └── path-type@1.1.0 
  ├── require-directory@2.1.1 
  ├── require-main-filename@1.0.1 
  ├── set-blocking@2.0.0 
  ├─┬ string-width@1.0.2 
  │ ├── code-point-at@1.1.0 
  │ └─┬ is-fullwidth-code-point@1.0.0 
  │   └── number-is-nan@1.0.1 
  ├── which-module@1.0.0 
  ├── window-size@0.2.0 
  ├── y18n@3.2.1 
  └─┬ yargs-parser@4.0.2 
    └── camelcase@3.0.0 

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/homebrew/Cellar/node/7.0.0/bin/node" "/usr/local/homebrew/bin/npm" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.0.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jcastillo/dev/git/speech/nodejs-docs-samples/speech/npm-debug.log

**Comment by jmdobry** [comment]
I'm guessing it doesn't work on Node v7?

Try downgrading to Node v6.9.1

**Comment by jcastill0** [comment]
Yes, as you can see, I was running it under node v7. I also tried v4, v5 and I think also v6.
THe problem is with the installation of the grpc. That fails directly in my environments. I tried also doing so in Ubuntu 16 with the same results.

**Comment by jmdobry** [comment]
Can you please open an is here: https://github.com/grpc/grpc and reference this issue?

**Comment by jmdobry** [comment]
Is this still an issue?

**Comment by ace-n** [comment]
Closing due to staleness; @jcastill0 please reopen if this is still a problem. Thanks!
