### ISSUE TITLE
@google-cloud/datastore 0.5.0 does not return entity keys with query results

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/nodejs-docs-samples#250]
_From @floodfx on November 9, 2016 16:40_

#### Environment details

  - OS: MacOS 10.11.6
  - Node.js version: 6.9.1
  - npm version: 3.10.8
  - google-cloud-node version: 0.43.0
  - @google-cloud/datastore version: 0.5.0

#### Steps to reproduce

```
git clone git@github.com:GoogleCloudPlatform/nodejs-docs-samples.git
cd nodejs-docs-samples/datastore
```
Open ```quickstart.js```
Add code below to end of the file
```
// query for entities
var q = datastoreClient.createQuery(kind)
q.run((err, entities, nextQuery) => {
  console.log(err, entities, nextQuery)
  for(var i = 0; i < entities.length; i++) {
    var task = entities[i];
    console.log(`Task ${task}: Key${task.key}`);
  }
});
```

Run 
```
npm install
node quickstart.js
```

Keys returned with entity results.

Next update package.json to use 0.5.0 of @google-cloud/datastore

Run 
```
node quickstart.js
```

Keys are "undefined".

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#1780_

**Comment by stephenplusplus** [comment]
_From @floodfx on November 9, 2016 16:42_

Note the default version of @google-cloud/datastore for nodejs-docs-samples is "^0.1.1"

**Comment by stephenplusplus** [comment]
Thanks for reporting, @floodfx!

An entity structures its data differently now, not embedding the Key within the object:

```js
datastore.get(key, function(error, entity) {
  // Before:
  entity.key = Key object
  entity.data = {...data...}

  // After:
  entity = {...data...}
  entity[datastore.KEY] = Key object
});
```

See https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1768 for more details.

**Comment by floodfx** [comment]
Thanks @stephenplusplus.  appreciate the link.  figured I was missing something obvious.  Do you know where this is mentioned in the official docs?  I spent a lot of time trying to figure this out before trying a different version.  Happy to send a PR on docs if that'd be helpful?

**Comment by stephenplusplus** [comment]
I'm really sorry about that :( I think we've caught all of the examples in the docs, but they won't update until we cut a new release. If you browse the [master docs](https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore/master/datastore), you'll see the corrected examples.

Thank you very much for being patient and offering your help!

**Comment by jmdobry** [comment]
I actually just fixed all of the Datastore samples in this repo to use 0.5.0, the PR is pending review: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/249

**Comment by puppetmaster3** [comment]
Does not work, I tried the new way, and you can't get the key back via query.
