### ISSUE TITLE
Should remove new when using busboy

### ISSUE THREAD

**Issue by Youlean** [GoogleCloudPlatform/nodejs-docs-samples#2557]
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/d689fe5e670e7dbd4b36674b28152251cd26264c/functions/http/index.js#L127

The "new" should be removed for the latest version of busboy

**Comment by chingor13** [comment]
Breaking changes notes from 1.0.0: https://github.com/mscdex/busboy/issues/266

**Comment by averikitsch** [comment]
fixed in #2564
