### ISSUE TITLE
Adding Readme for eventarc samples

### ISSUE THREAD

**Issue by gcp-grauj** [GoogleCloudPlatform/nodejs-docs-samples#2575]
There is no Readme documents for all the samples under the `eventarc/` folder.

Some of these samples are used on the official Eventarc docs, but some are not (for example, the generic sample it's not documented).

Would it be possible to add a short readme for each of these samples, or one for all of them, explaining the usage and goal for each of the samples on that folder [1]?

Thanks in advance!

[1] https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/main/eventarc

**Comment by chingor13** [comment]
@grant It looks like you authored these awhile back - can you take a look?

**Comment by grant** [comment]
Hi @gcp-grauj, I hope these samples are useful! Yes, not all of them are used in the docs.

The generic sample can be used with any eventarc trigger. Here is some example setup for a related sample: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/main/eventarc/pubsub

**Comment by grant** [comment]
@chingor13 Thanks. I no longer work on this, however I added a reply.

In terms of owners, I'd contact the serverless DPE folks and add them to https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CODEOWNERS for further work.

**Comment by pattishin** [comment]
Closing out as request is ~2 years old.
