### ISSUE TITLE
Link to 'Create a service account' in the nodejs-docs-samples/cloud-sql/postgres/knex/ project does not lead to instructions

### ISSUE THREAD

**Issue by arcticfly** [GoogleCloudPlatform/nodejs-docs-samples#2598]
I'm trying to follow the instructions under https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/main/cloud-sql/postgres/knex to set up a Google Cloud project with a postgres database.  Unfortunately, the link on step number 4 is broken.

```
Create a service account with the 'Cloud SQL Client' permissions by following these [instructions](https://cloud.google.com/sql/docs/postgres/connect-external-app#4_if_required_by_your_authentication_method_create_a_service_account). Download a JSON key to use to authenticate your connection.
```

https://cloud.google.com/sql/docs/postgres/connect-external-app#4_if_required_by_your_authentication_method_create_a_service_account leads to a page with no specific instructions for creating a service account.

This link needs to be updated.

**Comment by davidlcorbitt** [comment]
Perhaps this link would work: https://cloud.google.com/iam/docs/creating-managing-service-accounts

**Comment by SurferJeffAtGoogle** [comment]
Thank you @davidlcorbitt for reporting this issue and providing an alternative link.

@jsimonweb If the link is simply replaced, I'm not sure the instructions will result in readers succeeding.  I think the text needs some rewriting.  I request your expertise.

**Comment by andyzeli** [comment]
If possible its always more beneficial for those of us lacking the context of daily GCP ops work to keep instructions for each example of task as self contained as possible. one of the reasons I left AWS is all of their documentation is just a hastily put together collection of links. these instructions are very confusing. it says "Setting up the Cloud SQL database for the app requires setting up the app for local use." not sure what this means?  you cant deploy app engine with Postgres without the confusing local proxy setup?
