### ISSUE TITLE
Cloud Functions background sample appears incorrect: entity.data.myMessage

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/nodejs-docs-samples#260]
nodejs-docs-samples/functions/background/index.js line 27

commit: f7b29b3c724b2de6219dfba096c61d8727c299ee

introduces 'event.data.myMessage'

IIUC 'event' object does not contain this property and the code does not work:

https://cloud.google.com/functions/docs/writing/background#event_parameter

A different and probably better mechanism is used here:

https://cloud.google.com/functions/docs/tutorials/pubsub#preparing_the_application

**Comment by jasonpolites** [comment]
Which property do you mean?  `myMessage` or `data`?

`event.data` exists
`event.data.myMessage` is just an example.  Perhaps we need to be clear about how `myMessage` is populated in that example

**Comment by jmdobry** [comment]
I just tested it, seems to work fine.

The error case:
```
$ gcloud alpha functions call helloWorld --data '{"data":{}}'

executionId: xhsrd3tpbwpe
result: |
  Function failed, details: No message defined!
```

Then looking at https://console.cloud.google.com/logs/viewer?project=nodejs-docs-samples&resource=cloud_function I see:

![screen shot 2016-11-17 at 10 32 49 am](https://cloud.githubusercontent.com/assets/1213510/20402372/4542bdd8-acb1-11e6-9938-5db5ea858c6c.png)

The success case:
```
$ gcloud alpha functions call helloWorld --data '{"data":{"myMessage":"Hello, world!"}}'

executionId: xhsrgavertuo
```

![screen shot 2016-11-17 at 10 29 58 am](https://cloud.githubusercontent.com/assets/1213510/20402300/fb2937e0-acb0-11e6-9f3c-a43622c19cd5.png)

**Comment by jmdobry** [comment]
I agree though, it's not clear what the use case is for that particular sample.

**Comment by DazWilkin** [comment]
But, you're cheating :-)

The code is an example of a Cloud Function being used as a background function.

There are two ways background functions should be triggered, in response to a:

-- Pub/Sub topic being published
-- Cloud Storage bucket event

In both of those cases, the event.data schema is defined by the originating service.

For Pub/Sub,
```
gcloud alpha pubsub topics publish \
MY-TOPIC \
'{"myMessage":"Hello, Henry!"}' \
--project=MY-PROJECT
```
I receive a string encoding of the JSON object (not a JSON object):

```
data: "{\"myMessage\":\"Test\"}"
```

For Cloud Storage, I receive:

```
data: ""
```

If I deploy your function as-is, I receive an error:

```
Error: No message defined! at exports.originalPubSub (/user_code/index.js:31:14) at /var/tmp/worker/worker.js:572:16 at Domain.<anonymous> (/var/tmp/worker/worker.js:530:9) at Domain.run (domain.js:221:14) at Handler.handle (/var/tmp/worker/worker.js:520:7) at /var/tmp/worker/worker.js:587:13 at Layer.handle [as handle_request] (/var/tmp/worker/node_modules/express/lib/router/layer.js:82:5) at next (/var/tmp/worker/node_modules/express/lib/router/route.js:110:13) at Route.dispatch (/var/tmp/worker/node_modules/express/lib/router/route.js:91:3) at Layer.handle [as handle_request] (/var/tmp/worker/node_modules/express/lib/router/layer.js:82:5)
```

**Comment by jmdobry** [comment]
You are right, this particular sample only works if you call it with `gcloud alpha functions call`. 😕

**Comment by jmdobry** [comment]
I removed this sample from the docs.
