### ISSUE TITLE
Function Code Failing for 'Scheduling compute instances with Cloud Scheduler'

### ISSUE THREAD

**Issue by anthonytwh** [GoogleCloudPlatform/nodejs-docs-samples#2612]
Creating the scheduler functions in this tutorial (https://cloud.google.com/scheduler/docs/start-and-stop-compute-engine-instances-on-a-schedule) does not work and the functions fail to load. 

`Function failed on loading user code. This is likely due to a bug in the user code. Error message: Error: please examine your function logs to see the error cause: https://cloud.google.com/functions/docs/monitoring/logging#viewing_logs. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.`

I have also tried using NodeJS version 12 as stated in package.json here (https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/64b60cb1bf12fb2d71b40a9e928e0f29b83d6ca9/functions/scheduleinstance) but that does not work.

Unfortunately there are no logs that I available when trying to see what went wrong.

**Comment by alexander-fenster** [comment]
Hi @anthonytwh,

You might be able to find some logs if you go to console.cloud.google.com → Logging and pick Log Explorer there. Having those logs will be very helpful to see what's going on.

Otherwise, we'll try to reproduce the problem by following the guide step by step and see what might go wrong.

**Comment by anthonytwh** [comment]
> Hi @anthonytwh,
> 
> You might be able to find some logs if you go to console.cloud.google.com → Logging and pick Log Explorer there. Having those logs will be very helpful to see what's going on.
> 
> Otherwise, we'll try to reproduce the problem by following the guide step by step and see what might go wrong.

@alexander-fenster I'm having issues loading the logs (or any logs in general) but it doesn't seem to be an issue on my end..

This is error message I was able to get off gcloud console shell:

```
gcloud logging read "resource.type=cloud_function AND \
severity=ERROR"
ERROR: (gcloud.logging.read) HttpError accessing <https://logging.googleapis.com/v2/entries:list?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Mon, 18 Apr 2022 19:52:06 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': 500}>, content <{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
>
This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach.
```

**Comment by anthonytwh** [comment]
This is the error from the Debug log:

```
severity: "DEBUG"
textPayload: "Function execution took 1106 ms. Finished with status: response error"
timestamp: "2022-04-19T14:38:42.240777750Z"
```
and trace details:

```
/_ah/healthcheck
Start Time: @0 ms
Timestamp: 2022-04-19 (10:38:41.007) -0400
HTTP Method
    GET 
HTTP Status Code
    503
```

**Comment by FrodoTheTrue** [comment]
Hi @anthonytwh!

I have just went through the tutorial steps and it works as expected.

I have one assumption: are you providing payload data to the function correctly? According to the tutorial it should be `{"data":"eyJ6b25lIjoidXMtd2VzdDEtYiIsICJsYWJlbCI6ImVudj1kZXYifQo="}` (base64 from `{"zone":"us-west1-b", "label":"env=dev"}`)
![Screen Shot 2022-05-13 at 16 19 57](https://user-images.githubusercontent.com/9107905/168305258-ed9dbb5c-94c4-4314-b1c1-c33938b4c9b4.png)
