### ISSUE TITLE
Update Websocket Cloud Run sample to use latest Redis version

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/nodejs-docs-samples#2657]
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/commit/05b5423242f273518e8600e26e2bd35036082959#r61378446 change broke the sample.
In PR #2654, we will convert the version back. We should update redis back to v4 and make the needed changes to the code. Learn more: 
* https://socket.io/docs/v4/redis-adapter/#migrating-from-socketio-redis

**Comment by kweinmeister** [comment]
I think this issue might be blocking #2909 ? The `run/websockets` test failed on this dependency update.

**Comment by ace-n** [comment]
@kweinmeister yes, you are correct. I took some time to investigate this issue, and added my notes below.

----------

Two issues with this sample:
1. ID token fetching is broken on my local MacBook. To get around this, we can use a `gcloud` command to fetch an ID token:

        ID_TOKEN = execSync(`gcloud auth print-identity-token`).toString().trim();

    Then, we can replace the `Authorization` header with `Bearer: ${ID_TOKEN}
2. When running this on Cloud Run, the most up-to-date `socket.io` and `redis` library versions [result in a `transport close` error](https://github.com/socketio/socket.io/issues/3025) in the browser. 

    **This will take significant investigation (`O(1-2 weeks)`) to fix**, and should be saved for a dedicated fix-it.
