### ISSUE TITLE
Error reporting Cloud Functions using an Error object

### ISSUE THREAD

**Issue by stefandoorn** [GoogleCloudPlatform/nodejs-docs-samples#2673]
At this docs: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/HEAD/functions/helloworld/index.js#L112.

It's mentioned that this will not be reported into Error Reporting:

```nodejs
// These will NOT be reported to Error Reporting
console.error(new Error('I failed you')); // Logging an Error object
```

But, we used `console.info(new Error('Test'))` in a project and we see it ending up in Error Reporting. The idea was here to report them either as `error` or as `info` based on flag, but in this case using `info` does still seem to send it into Error Reporting. My guess is that there's something done with the `Error` class on the CF framework. 

I have notifications set-up and these enter there, and trigger notifications. Changing it just into `console.info('Test')` prevents that. 

Are the docs here incorrect or am I just reading the explanation wrongly in here?

**Comment by ace-n** [comment]
@stefandoorn thanks for reporting this!

It looks like it's a docs issue (possibly due to a change in the [Node.js Functions Framework](https://github.com/GoogleCloudPlatform/functions-framework-nodejs); I've filed #2675 to fix that.
