### ISSUE TITLE
opencensus/metrics-quickstart.js - Invalid authentication credentials

### ISSUE THREAD

**Issue by didiermicoud** [GoogleCloudPlatform/nodejs-docs-samples#2689]
metrics-quickstart fails to POST to 'https://monitoring.googleapis.com/v3/projects/{myProjectId}/timeSeries',

```
status: 401,
statusText: 'Unauthorized',
request: {
  responseURL: 'https://monitoring.googleapis.com/v3/projects/{myProjectId}/timeSeries'
}
...
  code: 401,
  errors: [
    {
      message: 'Invalid Credentials',
      domain: 'global',
      reason: 'authError',
      location: 'Authorization',
      locationType: 'header'
    }
  ]
```

```
headers: {
      'x-opencensus-outgoing-request': 1,
      'x-goog-api-client': 'gdcl/4.4.3 gl-node/16.14.0 auth/6.1.6',
      'Accept-Encoding': 'gzip',
      'User-Agent': 'opencensus-node/0.0.20 google-api-nodejs-client/4.4.3 (gzip)',
      Authorization: 'Bearer {JWT}',
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
```

I can confirm that my environment variables are correct being able to send metrics from the [python opencensus sample](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/0763e174767964b103dfd374d1c0871a34f659fd/opencensus)
With the same 
GOOGLE_APPLICATION_CREDENTIALS
GOOGLE_PROJECT_ID

**Comment by didiermicoud** [comment]
Exception thrown:
```
/Users/didiermicoud/Work/dmicoud/javascript-scratchpad/opencensus/node_modules/gaxios/build/src/gaxios.js:129
                throw new common_1.GaxiosError(`Request failed with status code ${translatedResponse.status}`, opts, translatedResponse);
                      ^

GaxiosError: Invalid Credentials
    at Gaxios._request (/Users/didiermicoud/Work/dmicoud/javascript-scratchpad/opencensus/node_modules/gaxios/build/src/gaxios.js:129:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async JWT.requestAsync (/Users/didiermicoud/Work/dmicoud/javascript-scratchpad/opencensus/node_modules/google-auth-library/build/src/auth/oauth2client.js:343:18)
```

**Comment by didiermicoud** [comment]
No success setting `forceRefreshOnFailure` - 
It looks like [opencensus-exporter-stackdriver](https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-exporter-stackdriver/package.json#L70) is on `"google-auth-library": "^6.1.6",` trying to figure if moving to `^7.0.0` would address the issue - 

Anyway, this does not look like it's specific to the sample code but still the sample is not working as expected on the current version of `@opencensus/exporter-stackdriver`

**Comment by sofisl** [comment]
@ace-n or @mayurkale22, would either of you be the correct codeowners to respond to this sample question?

**Comment by sofisl** [comment]
Hi @didiermicoud, I'm not sure who owns. @opencensus/exporter-stackdriver but I'd agree, it seems like they are on a much older version of [google-auth-library-nodejs](https://github.com/googleapis/google-auth-library-nodejs/blob/main/package.json), which means an older dependency on gaxios as well.

Please open an issue on their repository to update their dependencies, once they publish a new version we should be able to update our dependency as well. Thanks!
