### ISSUE TITLE
run/idp-sql tests fail when upgrading to firebase-admin v11

### ISSUE THREAD

**Issue by sofisl** [GoogleCloudPlatform/nodejs-docs-samples#2706]
I did not upgrade it here because I could not get tests to pass when upgrading the dependency: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/2705

**Comment by ace-n** [comment]
It looks like Cloud Run tests currently run against [Node 12](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/.kokoro/run/common.cfg#L21), whereas this library uses a feature (nullish coalescing operator) that is **only** available in Node 14+.

@averikitsch @iennae any objection to migrating Cloud Run tests to Node 14?

**Comment by averikitsch** [comment]
Looks like PR #2716 is now passing
