### ISSUE TITLE
Add sample / docs for HSTS for requiring https

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/nodejs-docs-samples#271]
With the move to flex, we lost support for secure: handlers that required https for given routes.  We need a sample that shows how to make this work with the HSTS header.  

I tried to do this with helmet/hsts, but it doesn't handle the initial redirect / 301 that you need for hsts to actually kick in.  

Also, there's currently a bug where health checks on flex don't work over HTTPs :(

To get around both of these... I wrote a npm module that works for us:
https://github.com/JustinBeckwith/yes-https/

**Comment by fhinkel** [comment]
Closed due to inactivity and moving the standard 😆 . Feel free to reopen if needed.
