### ISSUE TITLE
Update Node.js samples for google-cloud to use latest library versions

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/nodejs-docs-samples#273]
We have updated several of our libraries to a new version: https://github.com/GoogleCloudPlatform/google-cloud-node/releases

Especially important is that BigQuery, Storage, Datastore, and Logging are now at Beta.

We should update all our samples to test against the latest library for each of these APIs.

(and we can update the other samples for all other APIs to use the latest library available as well).

**Comment by jmdobry** [comment]
Done
