### ISSUE TITLE
datastore-functions test is taking 6h and failing

### ISSUE THREAD

**Issue by bcoe** [GoogleCloudPlatform/nodejs-docs-samples#2755]
The [datastore-functions test](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/actions/runs/3012242172) is taking 6h to run, finishing with a failure.

This is a contributing factor in us having a high usage # for GitHub Actions.

**Comment by bcoe** [comment]
Note: our renovate PRs seem to continue rebasing, making this a larger issue:

https://github.com/renovatebot/renovate/issues/17762

**Comment by sofisl** [comment]
Should revert #2761 when this is done
