### ISSUE TITLE
pubsub throws 'Service Unavailable'

### ISSUE THREAD

**Issue by grandmore** [GoogleCloudPlatform/nodejs-docs-samples#277]
When running pub/sub the quickstart.js to test the connection to google cloud, I get get a service unavailable. 
```bash
(node:2787) UnhandledPromiseRejectionWarning: 
Unhandled promise rejection (rejection id: 1): Error: Service Unavailable
```

I changed the projectId id in the code to match mine 
```const projectId = 'YOUR_PROJECT_ID';```

As well as setting an env var
```export GCLOUD_PROJECT=your-project-id```

If I run another services, like big query, they connect correctly so the auth seems to be correct. Is there something specific to pub/sub that needs to be done to make a connection?

Thanks.

**Comment by grandmore** [comment]
Currently I cannot use pub/sub but the other services seem fine so I went a lot further to test this and see if it is my setup or the library at fault here.

(I'm using OSX Sierra 10.2.1)

1. I deleted the ```~/.config``` folder which holds all the google SDK authentication information
2. I created a new google project 
3. I re-authenticated with google using ```cloud init```

I then ran some node.js code to create some datastore databases and do some test searches.

4. I created a  new app engine app in the new project (accessing datastore wanted me to do this)

I continued to run the datastore tests and everything worked. (My auth seems correct)

5. I ran some bigQuery tests, created some tables, did some searches all from node.js.
6. I ran some test code to create a topic in Pub/Sub and it failed with ```Error: Service Unavailable```

Any help would be greatly appreciated.

Thanks,

**Comment by grandmore** [comment]
## I just found the issue after much hair pulling.

I have an environmental variable ```export PUBSUB_EMULATOR_HOST=localhost:8170```

This was used to test the local pub/sub emulator. 

To stop this happening for others, perhaps when the this libraries default functionality is overrides by an environment var, instead of the real services, it could report it in the console. 

There is zero visibility that this is happening behind the scenes hence the many hours it has taken me to track this down.

Thanks.

**Comment by jmdobry** [comment]
> perhaps when the this libraries default functionality is overrides by an environment var, instead of the real services, it could report it in the console.

@stephenplusplus Is that something google-cloud-node could do?

**Comment by stephenplusplus** [comment]
We aren't keen on printing to the console, since we're a low level library, we don't know what layers are stacked on top of us, who wouldn't appreciate our logs cluttering output their users are seeing. We're somewhat trapped due to that restriction, however we have discussed having a debug mode, which when enabled, our library would start getting noisy, logging exactly what we're doing-- raw requests, responses, and things like "USING LOCAL EMULATOR" would fit in nicely there as well.

**Comment by jmdobry** [comment]
Any update on a debug mode?

**Comment by stephenplusplus** [comment]
Check this out!: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2517

After that merges, modules will have the ability to log when/whatever they need to.

**Comment by fhinkel** [comment]
Closed due to inactivity. Feel free to reopen if needed.
