### ISSUE TITLE
Recognize stream freezes (from example)

### ISSUE THREAD

**Issue by bloodcarter** [GoogleCloudPlatform/nodejs-docs-samples#278]
Steps to reproduce:
wget https://cloud.google.com/speech/docs/samples/audio.raw
./recognize.js stream audio.raw

**Comment by jmdobry** [comment]
I just attempted to reproduce the issue, following these steps (I'm on OS X):

1. `node -v` (printed `v6.9.1`)
1. `npm -v` (printed `3.10.8`)
1. `gcloud beta auth application-default login`
1. `git clone https://github.com/GoogleCloudPlatform/nodejs-docs-samples.git`
1. `cd nodejs-docs-samples/speech`
1. `npm install`
1. `wget https://cloud.google.com/speech/docs/samples/audio.raw`
1. `node recognize.js stream audio.raw`

This is what I got:

```
Data received: {"error":null,"results":"","resultIndex":0,"endpointerType":"START_OF_SPEECH"}
Data received: {"error":null,"results":"","resultIndex":0,"endpointerType":"END_OF_AUDIO"}
Data received: {"error":null,"results":"how old is the Brooklyn Bridge","resultIndex":0,"endpointerType":"ENDPOINTER_EVENT_UNSPECIFIED"}
```

**Comment by bloodcarter** [comment]
@jmdobry Weird. Well, if so, this is must be my own problem. Closing the issue.
