### ISSUE TITLE
App engine pubsub authenticated endpoint does not need PUBSUB_VERIFICATION_TOKEN

### ISSUE THREAD

**Issue by mbyrne00** [GoogleCloudPlatform/nodejs-docs-samples#2794]
Thanks for the samples. Some notes below on areas I think can be improved, but feel free to let me know if I've missed the mark.

I'm looking at https://cloud.google.com/pubsub/docs/push#validate_tokens and the corresponding code here https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/b0257afe31f3a41f54ab4342a71ed579e4d9d135/appengine/pubsub/app.js#L93. There seems no point in having `PUBSUB_VERIFICATION_TOKEN` in this endpoint if the JWT token is being validated. This only adds confusion. Also most of the code is keeping track of tokens for another endpoint to view them. It would be nice to get this function down to the concise lines needed just to authenticate. It all seems clearer to me now but it took some time to understand which parts to pay specific attention to.

Also, I've been looking at pub/sub with node in App Engine and initially read the readme here: https://cloud.google.com/pubsub/docs/push. This states:

> Automatic authentication and authorization mechanisms are available for App Engine Standard and Cloud Functions endpoints hosted in the same project as the subscription.

There are no examples that clarify what that statement means for App Engine. How does such "Automatic authentication and authorization" happen within App Engine Standard? I'm guessing only for services behind Identity Aware Proxy? A small statement here would really save a lot of confusion. I was searching for a long time to find this "automatic" solution and couldn't find anything.

**Comment by pattishin** [comment]
Appreciate the feedback on the App Engine Pubsub sample and docs, we will take it into consideration. To your last query, if you have a GCP project that is leveraging both Cloud Functions and App Engine - configuring authentication/authorization 
 should  "automatically" be applied to the other.

**Comment by pattishin** [comment]
Thanks again for the feedback! Please feel free to re-open another issue if this hasn't answered your query.

**Comment by mbyrne00** [comment]
Hi @pattishin - thanks for feedback but the main bug was about fixing the sample code. Can you please remove the check for `PUBSUB_VERIFICATION_TOKEN` as this is the _old way_ and is completely redundant code if you are checking a JWT token. Keeping that code in the sample makes it quite confusing for people trying to implement JWT validation.
