### ISSUE TITLE
How to change Client GRPC deadline?

### ISSUE THREAD

**Issue by bloodcarter** [GoogleCloudPlatform/nodejs-docs-samples#283]
I randomly receive this error while streaming data:
`Client GRPC deadline too short. Should be at least: 3 * audio-duration + 5 seconds. Current deadline is: 59.699356980447192 second(s). Required at least: 60 second(s).`

What should I do with that?

**Comment by jmdobry** [comment]
@jmuk How would one increase the deadline?

**Comment by jmuk** [comment]
The autogen layer can customize the deadline through the `CallOption` parameter, however `@google-cloud/speech` hand-written layer doesn't allow passing timeout by themselves.

Which method are you using?  I'm wild-guessing that `asyncRecognize` does not have such restriction.

**Comment by jmdobry** [comment]
Something like this would work:

```js
const v1beta1 = require('@google-cloud/speech').v1beta1();
const speech = v1beta1.speechClient();

const request = {
  audio: {
    uri: 'gs://my-bucket/filename.raw'
  },
  config: {
    encoding: 'LINEAR16',
    sampleRate: 16000
  }
};

const options = {
  longrunning: {
    initialRetryDelayMillis: 100, , // Default
    retryDelayMultiplier: 1.3, // Default
    maxRetryDelayMillis: 60000, // Default
    initialRpcTimeoutMillis: null, // Default
    rpcTimeoutMultiplier: null, // Default
    maxRpcTimeoutMillis: null, // Default
    totalTimeoutMillis: 600000 // Default
  }
};

speech.syncRecognize(request, options)
  .then((results) => {
    const transcription = results[0];

    console.log(transcription);
  });
```

**Comment by bloodcarter** [comment]
@jmdobry Would this work with recognizeStream?

**Comment by jmdobry** [comment]
I'm not sure the bi-directional streaming uses exponential backoff. @jmuk?

**Comment by jmuk** [comment]
@bloodcarter: `createRecognizeStream` can customize the timeout as https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/speech/src/index.js#L378

```javascript
const speech = require('@google-cloud')();
const stream = speech.createRecognizeStream(..., {timeout: 300});
...
```

@jmdobry: bidi streaming does not use exponential backoff, but uses `timeout` field in the options.

```javascript
const v1beta1 = require('@google-cloud/speech').v1beta1();
const speech = v1beta1.speechClient();

// set the timeout to 300 seconds.
const stream = speech.streamingRecognize({timeout: 300});
stream.write(...);
...
```

This should customize the timeout.
