### ISSUE TITLE
HL7v2Message ID

### ISSUE THREAD

**Issue by alexvacharat-abridge** [GoogleCloudPlatform/nodejs-docs-samples#2835]
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/d2ca7bbb436a60527379d4838c319b9c328cfc44/healthcare/hl7v2/getHl7v2Message.js#L39

Where is this hl7v2MessageID from? None of the documentation I've looked at seems to reference it, and the dataStore itself doesn't display them even after having ingested a message.

**Comment by noerog** [comment]
Hi @alexvacharat-abridge, the HL7v2 message ID is a unique ID returned by the Healthcare API that identifies an HL7v2 message. The ID is generated and returned in the response whenever you create or ingest a message in an HL7v2 store. If you query the HL7v2 store using [healthcare/hl7v2/listHl7v2Messages.js](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/healthcare/hl7v2/listHl7v2Messages.js), you should a see a list of messages with their ID at the end of the `name` field, like so:

{
  "hl7_v2_messages": [
    {
      "name": "projects/my-project/locations/us-central1/datasets/my-dataset/hl7V2Stores/my-hl7v2-store/messages/**MESSAGE_ID**",
      ...
    },
    ...
  ]
}

**Comment by kweinmeister** [comment]
@noerog do you recommend adding any comments or additional documentation with the information you provided above? If not, can we close the issue?

**Comment by noerog** [comment]
@kweinmeister I have a PR out in https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/2948 to add a comment describing what the HL7v2 message ID is.
