### ISSUE TITLE
websocket issues

### ISSUE THREAD

**Issue by patricktresp** [GoogleCloudPlatform/nodejs-docs-samples#285]
Hi all,
i just wanted to use this example for websocket:

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/appengine/websockets

**issue #1**
using`vm: true` in app.yaml is not supported anymore
**issue #2**
 `env: flex` is missing in app.yaml
**issue #3**
forwarding posts is not allowed anymore in flex-environments
`network:
  forwarded_ports:
  - 65080
  instance_tag: websocket`

**issue #4** 
getExternalIP gets uncorrect ip-address from meta,
( scripts sets 104.xxx.xxx.xxx - console shows external ip as set to 130.xxx.xxx.xxx )
Does anyone have this example up and running on gce?

Main target is to create a websocket server which can be connected to from non gce-environmental clients...

thanks for help

**Comment by jmdobry** [comment]
The reason this example hasn't been updated to use `env: flex` is that `env: flex` does not yet support websockets.

**Comment by artpolikarpov** [comment]
+

**Comment by jmdobry** [comment]
There's nothing I can do for this until Google App Engine flexible environment supports websockets.

:/

**Comment by shahbazahmed1269** [comment]
I am facing similar issue with port forwarding. I deployed a custom docker image of tcp server listening on port 6788 on app engine flexible environment. But seems like `forwarded_ports:` in app.yaml is not working.

Can we run a tcp server on app engine flexible environment? If so then how do I apply port forwarding from host port to container port?
Any help is appreciated.

**Comment by mcdaid01** [comment]
Is there any update on this issue, is it likely to be fixed in the near future?

**Comment by drBenway** [comment]
+1
