### ISSUE TITLE
Transferring issue from nodejs-monitoring to reenable tests

### ISSUE THREAD

**Issue by sofisl** [GoogleCloudPlatform/nodejs-docs-samples#2866]
https://github.com/googleapis/nodejs-monitoring/issues/653

**Comment by kweinmeister** [comment]
Alerts test is running properly (not skipped), see: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/f93be7952af51ca10451b2762c0147811c57b9dd/monitoring/snippets/test/alerts.test.js#L46
