### ISSUE TITLE
Error while deploying Nodejs Express framework sample application to AppEngine

### ISSUE THREAD

**Issue by MopideviAshok** [GoogleCloudPlatform/nodejs-docs-samples#287]
Failing to start node when tried to deploy express js sample to AppEngine.
Please have a look at this issue http://stackoverflow.com/questions/41458081/error-while-deploying-nodejs-express-framework-sample-application-to-appengine

**Comment by jmdobry** [comment]
There was a bug in the Google Cloud SDK that has since been fixed where some source folders were not being properly uploaded during deployment.

https://code.google.com/p/google-cloud-sdk/issues/detail?id=1431
