### ISSUE TITLE
Speech sample with 'listen' command stops node after results returned

### ISSUE THREAD

**Issue by stuarttayler** [GoogleCloudPlatform/nodejs-docs-samples#291]
When I run the speech sample with the 'listen' command, the transcribed text is returned but then the node process stops and returns be to the command line. I'm not getting any error messages, it just returns the text and stops.

I assumed it should carry on listening and return more results rather than quitting, or is this the expected behaviour? If so is there a way to continually listen?

I am running the sample on a mac with node 6.9.4. I'm using the service json file to authorise.

**Comment by jmdobry** [comment]
I am seeing the same issue.

> I assumed it should carry on listening and return more results rather than quitting

That is what it used to do. I suspect this may be related to upgrading the version of `node-record-lpcm16` used by the sample.

Can you try downgrading `node-record-lpcm16` to `0.1.4` and see how that works for you?

**Comment by stuarttayler** [comment]
Thanks, I'll give that a try and let you know

**Comment by stuarttayler** [comment]
Hey @jmdobry that didn't work, but just looking at package on [NPM](https://www.npmjs.com/package/node-record-lpcm16) and it says: "The library will automatically attempt to stop when it encounters silence, if not you can stop the recording manually." which I guess explains it... Not sure if earlier versions did this too.

**Comment by jmdobry** [comment]
Looks like there's a silence threshold setting, I'll try tweaking that in the sample.

**Comment by iam-peekay** [comment]
Hi @jmdobry For me, it's throwing an error here:
```javascript
  const recognizeStream = speech.createRecognizeStream(options)
    .on('error', console.error('ERROR'))
    .on('data', (data) => process.stdout.write(data.results));
```
it logs error and then halts. So I cant even get the listen command to output anything. Stack trace below:

```
Error: spawn rec ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
```

**Comment by jmdobry** [comment]
Hmm, I just tried the sample again, and I was unable to reproduce any issue. It worked fine for me. I'm on Node.js 6.9.1 and Mac OS X. 

It continued to listen, even after pauses. Note that I tried this in a rather quiet environment.

**Comment by victorfliks** [comment]
Hi @jmdobry  i try the speech sync, and the other command and work fine, 
but if i use listen command it always return :

Listening, press Ctrl+C to stop.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn rec ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

my node version are 6.10.0
and i'm running on windows machine
I'm using the service json file to authorise.

**Comment by metalaureate** [comment]
@victorfliks  +1 same error

**Comment by immartian** [comment]
same problem here. 
The listening will stop after several hits, without error messages.

**Comment by fhinkel** [comment]
If the issue still persists, please file it [here](https://github.com/googleapis/nodejs-speech). Thank you.
