### ISSUE TITLE
Why non working instructions here?

### ISSUE THREAD

**Issue by ivose** [GoogleCloudPlatform/nodejs-docs-samples#2924]
Please give perfectly working code. I tried over 3 hours following the guides with my finger e.g in here: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/translate/v3/translate_list_codes.js. And no better result than the next lines:
```
throw new Error('Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.');
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
```
And the https://cloud.google.com/docs/authentication/getting-started gives no sufficient well understanding instuctions.
Please, Google translate nodejs-api developers, check and repair your codes.

**Comment by rsamborski** [comment]
@Shnatsel PTAL

**Comment by Shnatsel** [comment]
Hello @ivose,

My apologies for the late response. I'm looking to improve the instructions for authenticating to Google Cloud.

Could you please try following the steps listed at https://cloud.google.com/docs/authentication/provide-credentials-adc#local-dev and check if you still face the error? The steps listed there are supposed to resolve it.

You may then get the following error:

```
7 PERMISSION_DENIED: Cloud Translation API has not been used in project <PROJECT_NUMBER> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/translate.googleapis.com/overview?project=<PROJECT_NUMBER> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

If so, please visit the link from the error message in a web browser and click "Enable".

Running the sample works for me after that:

```
$ node translate_list_codes.js $PROJECT_ID
Supported languages:
Language Code: af
Language Code: ak
...
```

I've also added a Node.js sample to the https://cloud.google.com/docs/authentication/getting-started page, which was previously missing. Hopefully that makes the process more clear.

**Comment by kweinmeister** [comment]
Hi @ivose, thanks for your feedback. Now that we have a node.js authentication sample (thanks @Shnatsel !), we will close this issue. Please let us know if you have any remaining questions.
