### ISSUE TITLE
No a Issue but Need some details regarding streaming app.

### ISSUE THREAD

**Issue by higunjan** [GoogleCloudPlatform/nodejs-docs-samples#295]
I'm developing speech to text web app. As per recording and generate `wave` file I converted that wave into google api supported `.raw` file and sent to API it successfully converted into text.

Now I have to develop like streaming when I speak send chunk to google API and bind text output on web page. 

How should I develop. record direct into `.raw` format is that any way or google API support with direct chunk file.

Technology : NodeJS

**Comment by jmdobry** [comment]
You can find the encodings supported by the Google Cloud Speech API here: https://cloud.google.com/speech/reference/rest/v1beta1/RecognitionConfig#AudioEncoding

It may be that your `.wave` file matches the `MULAW` encoding supported by the Cloud Speech API. You'll have to try it and see. More details on encodings: https://cloud.google.com/speech/docs/encoding

You can access the Cloud Speech API from the browser, but only via HTTP (REST) and only for the [SyncRecognize](https://cloud.google.com/speech/reference/rest/v1beta1/speech/syncrecognize) and [AsyncRecognize](https://cloud.google.com/speech/reference/rest/v1beta1/speech/asyncrecognize) methods.

Do do streaming, you need to use [Speech#createRecognizeStream](https://googlecloudplatform.github.io/google-cloud-node/#/docs/speech/0.5.0/speech?method=createRecognizeStream) on the server in Node.js, then send the results back up to the browser.
