### ISSUE TITLE
Cloud functions need to be updated

### ISSUE THREAD

**Issue by sofisl** [GoogleCloudPlatform/nodejs-docs-samples#2954]
https://github.com/googleapis/google-cloud-node/issues/3621

**Comment by ace-n** [comment]
@rswlkr would you mind telling us which samples this was for?

Note to self:
> I looked for Cloud Functions samples with upper-case names (using the `grep` commands below in the `functions` directory), but I couldn't find anything:
> ```
> grep -E "functions\.(http|cloudEvent)\(.[A-Z]" **/*.js
> grep -E "exports\.[A-Z]" **/*.js
> ```

**Comment by pattishin** [comment]
Closing out as this is referencing older version. As previously noted, directions for valid characters listed https://github.com/googleapis/nodejs-functions/blob/main/src/v2/function_service_client.ts#L869.
