### ISSUE TITLE
Sample command's response take too long time

### ISSUE THREAD

**Issue by umezy** [GoogleCloudPlatform/nodejs-docs-samples#303]
I try "node recognize.js --help" in samples like this.
```
 node recognize.js sync ./resources/audio.raw
 node recognize.js async ./resources/audio.raw
 node recognize.js stream ./resources/audio.raw
 node recognize.js listen
```
But sometimes transcription take more than 1minute, and sometimes transcription return soon correctly.
my internet connection don't have troubble.
Please teach me what is the possible factor.

**Comment by ace-n** [comment]
It could be due to the size/formatting/amount of speech of the audio.

In any case, I don't believe we make any guarantees around the latency/timing of our APIs.

Feel free to reopen this issue if you have further questions.
