### ISSUE TITLE
yarn.lock prevents deploying the hello-world appengine sample

### ISSUE THREAD

**Issue by newbreedofgeek** [GoogleCloudPlatform/nodejs-docs-samples#308]
If you follow this tutorial:
https://cloud.google.com/nodejs/getting-started/hello-world

You will hit an issue when you try and `gcloud app deploy` which fails.

This is because of this yarn.lock file:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/appengine/hello-world/yarn.lock

The error you see will be:
```
ERROR: Yarn checker: "yarn.lock" was found indicating Yarn is being used, but "yarn check" indicates "yarn.lock" is invalid.
ERROR: (gcloud.app.deploy) Your application does not satisfy all of the requirements for a runtime of type [nodejs].  Please correct the errors and try again.
```

No sure why this is checkin here as the tutorial uses npm.

Removing the file locally before deploying will fix the issue.

**Comment by jmdobry** [comment]
I have updated [the tutorial](https://cloud.google.com/nodejs/getting-started/hello-world) to include instructions about using Yarn, and I have I've updated the dependencies in this repo such that the `yarn check --strict-semver --integrity` command should succeed during deployment.

**Comment by happyjohnnylin** [comment]
On this tutorial - Run MongoDB on Google Cloud Platform:
https://cloud.google.com/nodejs/resources/databases/mongodb

I also hit an issue when executing "gcloud app deploy", which failedin errors that are same as above.

**Comment by jmdobry** [comment]
Good catch, I'll update this tutorial as well
