### ISSUE TITLE
`topic.exists` method does not resolve promise

### ISSUE THREAD

**Issue by hansman** [GoogleCloudPlatform/nodejs-docs-samples#310]
Running `@google-cloud/pubsub@0.7.1`, the `topic.exists` does not get resolved but is pending indefinitely. This is not in `@google-cloud/pubsub@0.6.2`.

**Comment by jmdobry** [comment]
Can you please move this issue to https://github.com/GoogleCloudPlatform/google-cloud-node?

**Comment by hansman** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1957
