### ISSUE TITLE
I keep getting "PartialFailureError" for every attempt

### ISSUE THREAD

**Issue by dmauas** [GoogleCloudPlatform/nodejs-docs-samples#315]
A very uninformative "partialfailureerror" message keeps popping up.
I am anxious to get to the bottom of it.

I'm running NodeJS v7.5.0
I followed all steps to install prerequisites and then ran:
node tables.js insert temp2 day_site_placement_channel_country myfile3.json

Got the following:

(node:9512) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): PartialFailureError: A failure occurred during this request.
(node:9512) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any help would be appreciated

**Comment by fhinkel** [comment]
Closed due to inactivity. Feel free to reopen if needed.
