### ISSUE TITLE
run/idp-sql not running in CI

### ISSUE THREAD

**Issue by kweinmeister** [GoogleCloudPlatform/nodejs-docs-samples#3150]
There is neither a Kokoro config or GitHub Actions workflow configured.

**Comment by averikitsch** [comment]
Config is hosted: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/.kokoro/run/idp-sql.cfg
Presubmit tests are running: https://fusion2.corp.google.com/ci;prev=s/kokoro/prod:cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Frun%2Fidp-sql/activity/e2c78d12-3352-40e5-9e27-74a1eed52d6f/summary?q=prod:cloud-devrel%2Fnodejs-docs-samples%2F&s=p
Release tests are running: https://fusion2.corp.google.com/ci;prev=s/kokoro/prod:cloud-devrel%2Fnodejs-docs-samples%2Frelease%2Frun%2Fidp-sql/activity/21a052dc-77bf-4a80-9f41-491715322bb1/log?q=prod:cloud-devrel%2Fnodejs-docs-samples%2Frelease%2F&s=p
