### ISSUE TITLE
dicomWebRetrieveStudy in a zip format

### ISSUE THREAD

**Issue by sanjay3290** [GoogleCloudPlatform/nodejs-docs-samples#3205]
Can anybody help on how to download all the dcm instances related to a study in a zipped folder using healthcare/dicom/dicomWebRetrieveStudy.js instead of a multipart file?

**Comment by noerog** [comment]
Hi @sanjay3290, at this time, the Cloud Healthcare API doesn't support retrieving DICOM studies or series using the `application/zip` media type. You can find the supported Accept Headers in https://cloud.google.com/healthcare-api/docs/dicom#dicom_studyseriesinstances.
