### ISSUE TITLE
speech FLAC encoding not work

### ISSUE THREAD

**Issue by leizard** [GoogleCloudPlatform/nodejs-docs-samples#327]
I use 'FLAC' for the encoding not 'LINEAR16' and the server doesn't respond anything. If I use encoding 'LINEAR16' in the config again everything works fine.
How could the speech package support FLAC encoding ?

**Comment by willemmulder** [comment]
I've just tried with FLAC and it works on my machine... Set FLAC as encoding, set the samplerate to the proper rate (441000 in my case) and select a .flac file as input.

**Comment by fhinkel** [comment]
If the issue still persists, please file it [here](https://github.com/googleapis/nodejs-speech). Thank you.
