### ISSUE TITLE
New to Google Cloud Platform;  running the sample gives auth error?

### ISSUE THREAD

**Issue by willemmulder** [GoogleCloudPlatform/nodejs-docs-samples#329]
I'm new to the Google Cloud Platform and was happy to find this repo of examples.

However, when I simply follow the instructions I seem to get an auth error? 

> node recognize.js stream ./resources/audio.raw  -e LINEAR16 -r 16000

Gives me

> UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.

Which points to a page full of information about authentication, except the information I'm looking for: how can I simply pass an API key to the Speech client so it just simply works?

Could the documention be updated to instruct step-by-step how to do auth? Would it be possible to make that work something like

```
Speech({
  apikey: [somekey]
});
```

? Or is there a reason not to make it that easy? 
Right now it feels like there are so many implicit assumptions and things around auth that scare newcomers away. 

Would be happy to help in any way once I understand how it works.

**Comment by ace-n** [comment]
You need to authenticate with an account (either a Google account, or a [service account](https://cloud.google.com/compute/docs/access/service-accounts#serviceaccount)).

Does [this part](https://developers.google.com/identity/protocols/application-default-credentials#howtheywork) of that page help?

**Comment by willemmulder** [comment]
Yes that seems to be the important part; thanks.

Could we update the documentation with two parts?

1. Mention the environment variables explicitly, so that the example code runs without 'unexpected' issues
2. Also explain how the API can be used with an API key. I don't seem to understand how that works yet either.

**Comment by jmdobry** [comment]
For 1), this repo has [setup instructions](https://github.com/GoogleCloudPlatform/nodejs-docs-samples#prerequisites) for running samples.

For 2) we don't want to encourage the use of API keys. The more secure authentication method is with a Service Account. The setup instructions in 1) should help with this.
