### ISSUE TITLE
Migrate instructions to use Artifact Registry

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/nodejs-docs-samples#3298]
On [this page](https://cloud.google.com/run/docs/deploying-source-code), users are invited to use gcr.io.

These instructions should be updated to use Artifact Registry

**Comment by RichieEscarez** [comment]
@jama22 , that Cloud Run page mentions both Artifact Registry and also GCR but in the context of buildpacks. Will buildpacks move to AR or do we need to continue using the GCR URL locations?

**Comment by jama22** [comment]
we have some plans to get an AR reigstry address for that builder, so we can leave this issue open and I'll make a PR to update when we have that address available

**Comment by iennae** [comment]
@jama22 as of May 15, 2024 Artifact Registry will host images for the gcr.io domain by default. When I look up gcr.io/buildpacks/builder:latest it still looks like it's using Container Registry. Do we know the plan/impact for this?

**Comment by iennae** [comment]
I'm going to go ahead and close this issue. the gcr domain redirection will work once it's set up. Currently, it does still look like Container Registry is still in use, but based on the way the feature works, once migrated it will work seamlessly. There isn't anything that needs to be done from the sample side of things at this time.
