### ISSUE TITLE
Unable to run recognize.JS 

### ISSUE THREAD

**Issue by danishnazir** [GoogleCloudPlatform/nodejs-docs-samples#332]
Hi there !
Whenever i try to execute the recognize.JS file i get the following error
command: node recognize listen
Result:Listening, press Ctrl+C to stop.                                                events.js:141                                                                         throw er; // Unhandled 'error' event                                            ^                                                                                                                                                         Error: spawn rec ENOENT                                                             at exports._errnoException (util.js:870:11)                                     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)       at onErrorNT (internal/child_process.js:344:16)                                 at nextTickCallbackWith2Args (node.js:442:9)                                    at process._tickCallback (node.js:356:17)                                       at Function.Module.runMain (module.js:443:11)                                   at startup (node.js:139:18)                                                     at node.js:968:3

**Comment by MarcoThePoro** [comment]
I got around this by setting `recordProgram` to `'sox'` in the options passed to `record.start()`

eg.
```
record.start({
    sampleRateHertz: sampleRateHertz,
    threshold: 0,
    recordProgram: 'sox'
  }).pipe(recognizeStream);
```

**Comment by danishnazir** [comment]
@MarcoThePoro Now i get this error
Error: spawn sox ENOENT                                                             at exports._errnoException (util.js:870:11)                                     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)       at onErrorNT (internal/child_process.js:344:16)                                 at nextTickCallbackWith2Args (node.js:442:9)                                    at process._tickCallback (node.js:356:17)                                       at Function.Module.runMain (module.js:443:11)                                   at startup (node.js:139:18)                                                     at node.js:968:3

**Comment by MarcoThePoro** [comment]
Did you make sure to install SoX and add it to your path?

The speech example readme says this:
Note: The listen command requires that you have SoX installed and available
in your $PATH. See
https://www.npmjs.com/package/node-record-lpcm16#dependencies.

**Comment by danishnazir** [comment]
Hi there yes i have installed it and now that problem is resolved thanks

**Comment by danishnazir** [comment]
Hi @MarcoThePoro  i have been able to successfully compile it but whenever i run it using the listen option it says Listening, press Ctrl+C to stop.  but after this it automatically stop with no error messages! any ideas?

**Comment by MarcoThePoro** [comment]
I ran into that issue but just gave up then

**Comment by danishnazir** [comment]
@MarcoThePoro oh i see i am amazed to see that no one from google is helping us in solving this problem i mean where they? i am thoroughly disappointed!!

**Comment by jmdobry** [comment]
@danishnazir Can you provide extensive details so we can reproduce the behavior you're experiencing? OS, Node version, `@google-cloud/speech` version, sox version, `node-record-lpcm16` version, etc.

**Comment by danishnazir** [comment]
Here are the details
sox:v14.4.2
node:v4.4.4
@google-cloud/speech: same version as here in github repo as i am cloning
node-record-lpcm16:same version as here in github repo as i am cloning
@jmdobry

**Comment by jmdobry** [comment]
We just updated this repo yesterday, so you might want to try re-cloning it and re-installing dependencies. You might also try upgrading Node.js to say, 6.10.1

**Comment by danishnazir** [comment]
Hi @jmdobry i just reclonned the repo and upgraded my node setup but still same issue

**Comment by jmdobry** [comment]
Can you try changing the options (found [here](https://www.npmjs.com/package/node-record-lpcm16#options)) passed to `record.start()`? In particular, what happens if you change the `silence` option to `"10.0"`, or what happens if you change the `recordProgram ` option to `"sox"`?

**Comment by danishnazir** [comment]
@jmdobry still the same problem!! including the extra perimeters didnt helped me !

**Comment by jmdobry** [comment]
I think the value for `silence` is supposed to be a string, and did you try different values for `recordProgram` and threshold?

**Comment by danishnazir** [comment]
i tried using string too!! and no i havent manipulated the threshold yet

**Comment by josefsandoval** [comment]
Hello,

I am having the very same issue whenever I run using node .
I just get "Listening, press Ctrl+C to stop" and the program stops running right away. 
I am using sox: v14.4.2 and nodejs : v6.11.0.
Has anyone found a solution to this???

**Comment by josefsandoval** [comment]
@danishnazir Did you ever get it to work?

**Comment by danishnazir** [comment]
No i left for ibm

**Comment by Nathan4jesus** [comment]
@danishnazir I reached to the same point as you, getting no response, using the function : createRecognizeStream

` const recognizeStream = speechClient.createRecognizeStream(request)` 

rather than streamingRecognize()

Now, using streamingRecognize(), I get the error : 

> Uncaught TypeError: speechClient.streamingRecognize is not a function

When i try accing it throiugh the api object of my speechClient instance, i get this error as response :+1: 

>  .google.cloud.speech.v1.StreamingRecognizeRequest#0 is not a field: undefined

Any help please ?
@jmdobry ?

I would also like to know how to get the sample [https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/speech/recognize.js](url) work please....?

**Comment by Nathan4jesus** [comment]
I can now run the sample [https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/speech/recognize.js](url) but getting no result, no error, as @danishnazir and others stated...

When I try to call the streamingRecognize() method in my own node.js app, the method be found

> Uncaught TypeError: speechClient.streamingRecognize is not a function

This is my code : 

`// The BCP-47 language code to use, e.g. 'en-US'
            const languageCode = settingsRecord.language; //'en-US';

            // Your Google Cloud Platform project ID
            const nathProjectId = 'protocol-recorder-201707';

            // Instantiates a client
            const speechClient = Speech({
                projectId: nathProjectId
                ,keyFilename: './rsc/credentials/spr-426ec2968cf6.json'
            });

            // The encoding of the audio file, e.g. 'LINEAR16'
            const encoding = 'LINEAR16';

            // The sample rate of the audio file in hertz, e.g. 16000
            const sampleRateHertz = 16000;          

            const request = {
                config: {
                    encoding: encoding,
                    sampleRateHertz: sampleRateHertz,
                    languageCode: languageCode
                    },  
                interimResults: false // If you want interim results, set this to true
            };

            // Create a recognize stream           
            var notes = '';  
            console.log('create the recognize Stream object to be piped..')
            //const recognizeStream = speechClient.createRecognizeStream(request)
            console.log("speechClient : ",speechClient)
            const recognizeStream = speechClient.api.Speech._streamingRecognize(request)
                .on('error', console.error)
                .on('data', (response) => {
                    //process.stdout.write(response.results)   
                    process.stdout.write(
                        (response.results[0] && response.results[0].alternatives[0])
                        ? `Transcription: ${response.results[0].alternatives[0].transcript}\n`
                        : `\n\nReached transcription time limit, press Ctrl+C\n`);                  
                   
                    notes = document.getElementById("notes").value;  
                    notes = notes + response.results;
                    document.getElementById("notes").value =  notes;
                });

            // Start recording and send the microphone input to the Speech API
            console.log('Start recording and send the microphone input to the Speech API..')
            record.start({
                sampleRateHertz: sampleRateHertz,
                threshold: 0,
                // Other options, see https://www.npmjs.com/package/node-record-lpcm16#options
                verbose: true,
                recordProgram: 'sox', // Try also "arecord" or "sox"
                silence: '1.0',
                device : settingsRecord.audio_input
            })
            .on('error', console.error)
            .pipe(recognizeStream);`

Could anyone clue me on what matters ?

Thanks

**Comment by txie1993** [comment]
I'm getting the exact same error as Nathan4jesus. I had a program that just suddenly stopped getting data or errors when I piped an audio stream to it, updating npm/node didn't fix anything.

Now I either use `createRecognizeStream` and get no data or error, or `streamingRecognize` and get the TypeError that says streamingRecognize is not a function.

**Comment by yashnerella** [comment]
Any updates on this? I am encountering a similar issue. The program never pauses to record users voice. I think this is a problem with sox on windows

**Comment by mumunuu** [comment]
same issue to me. doesn't matter on macOS, but Widnwos doens't work!

**Comment by rrc2** [comment]
i have the same problem (windows) The program never pauses to record users voice. is there solution?

**Comment by atifsajjad** [comment]
+1 same exact situation. 
My setup:
Windows 7
Node v8.11.2
npm 5.6.0

I'm trying to get streaming input from mic and convert it to text. Tried both the example code here:
https://cloud.google.com/speech-to-text/docs/streaming-recognize#speech-streaming-mic-recognize-nodejs

as well as the sample here:
https://github.com/googleapis/nodejs-speech/tree/master/samples

Got the "Error: spawn rec ENOENT" error initially. Fixed that using the info from:
https://github.com/gillesdemey/node-record-lpcm16/issues/8

Now the script runs for about a second but then immediately closes without any error or transcript returned. Does seems like it is an issue only on windows. Will try something other than sox and report back if I get any success. Meanwhile, any help would be appreciated.

**Comment by fhinkel** [comment]
If the issue still persists, please file it [here](https://github.com/googleapis/nodejs-speech). Thank you.
