### ISSUE TITLE
Remove skipped aiplatform tests

### ISSUE THREAD

**Issue by kweinmeister** [GoogleCloudPlatform/nodejs-docs-samples#3377]
In #3371 several `aiplatform` tests were skipped due to timeouts. These should be removed once these tests are stabilized.

**Comment by gericdong** [comment]
Skipped tests: 

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3371
ai-platform/snippets/test/create-custom-job.test.js
ai-platform/snippets/test/deploy-model.test.js
ai-platform/snippets/test/create-custom-job.test.js
ai-platform/snippets/test/create-dataset-image.test.js
ai-platform/snippets/test/create-dataset-tabular-bigquery.test.js

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3303
ai-platform/snippets/test/create-featurestore-fixed-nodes-sample.test.js
ai-platform/snippets/test/create-featurestore-sample.test.js

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3311
ai-platform/snippets/test/deploy-model-custom-trained-model.test.js
