### ISSUE TITLE
Replace node-mailer module with something else

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/nodejs-docs-samples#338]
`node-mailer` only supports Node 6 - we need something that supports Node 4.

**Comment by kacepe** [comment]
[feathers-mailer](https://www.npmjs.com/package/feathers-mailer) supports [Node >= 4](https://github.com/feathersjs/feathers-mailer/blob/master/package.json#L30)

**Comment by jmdobry** [comment]
I found also [emailjs](https://github.com/eleith/emailjs), picked from [awesome-nodejs](https://github.com/sindresorhus/awesome-nodejs)

**Comment by JustinBeckwith** [comment]
Good news!  Node.js 4 is EOL 😂
