### ISSUE TITLE
Fix the npm @google-cloud/security-center/ deps

### ISSUE THREAD

**Issue by jlandure** [GoogleCloudPlatform/nodejs-docs-samples#3418]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

## In which file did you encounter the issue?
Read: https://cloud.google.com/security-command-center/docs/how-to-notifications
Code: https://github.dev/GoogleCloudPlatform/nodejs-docs-samples/blob/HEAD/security-center/snippets/v1/createNotificationConfig.js

## Did you change the file? If so, how?
L22: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/95631e4a619029701c0a549788e82e43b77bdaf6/security-center/snippets/v1/createNotificationConfig.js#L22
// npm install @google-cloud/security-center/ ➡️  // npm install @google-cloud/security-center

## Describe the issue
`npm install @google-cloud/security-center/` doesn't work
`npm install @google-cloud/security-center` works.

Thanks!

**Comment by jlandure** [comment]
Can I submit a PR or do I have to wait for it?

**Comment by kweinmeister** [comment]
Hi @jlandure , yes you can definitely file a PR, thank you for flagging this!
