### ISSUE TITLE
texttospeech/quickstart.js change the file to use fs/promises

### ISSUE THREAD

**Issue by andriotisnikos1** [GoogleCloudPlatform/nodejs-docs-samples#3504]
hello! ive noticed that texttospeech/quickstart.js uses fs.writeFile synchronously, and is then promisified with 'util.promisify'. why not just use 'fs/promises' and not just 'fs'? it does the same thing, and the code is more understandable. lmk your opinion google team!

**Comment by iennae** [comment]
@andriotisnikos1 thanks so much for filing this issue. we've updated the sample code for this quickstart.
