### ISSUE TITLE
Cloud Event Function triggered by a change to a Firestore document

### ISSUE THREAD

**Issue by aelkerda** [GoogleCloudPlatform/nodejs-docs-samples#3511]
## In which file did you encounter the issue?
functions/v2/firebase/firestore/helloFirestore/index.js

## Did you change the file? If so, how?
No

## Describe the issue

console.log(JSON.stringify(firestoreReceived.value, null, 2)); 
console.log(JSON.stringify(firestoreReceived.oldValue, null, 2));

are printing strange values:

![image](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/assets/93186493/5517f1e2-bba4-4615-80ce-16c8c4367168)

**Comment by pattishin** [comment]
@aelkerda Thanks for submitting an issue - if you can provide more information that would be very helpful for us to debug what you are seeing. I recommend checking out our test case against this for more information https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/e9fec8d71b546553d3e4f725db04ba941502096f/functions/v2/firebase/firestore/helloFirestore/test/index.test.js#L50.

**Comment by pattishin** [comment]
@aelkerda Closing out if no further comments, but please feel free to open back up with more information when you are able!
