### ISSUE TITLE
Semantic Text Matching like quora using Google NLP API (question)

### ISSUE THREAD

**Issue by jasan-s** [GoogleCloudPlatform/nodejs-docs-samples#353]
How can I use google NLP to match say a question entered by user to calculate how much it is similar to all other previously asked questions in the database.  SO i can show the user of all previous answer if the match is above certain threshold.

**Comment by jmdobry** [comment]
You could probably leverage the salience of each entity discovered by the NL API, which is a score of how strongly an entity appeared in the text. You would store those scores, comparing the stored scores to the new question.
