### ISSUE TITLE
ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). 

### ISSUE THREAD

**Issue by kbhagi** [GoogleCloudPlatform/nodejs-docs-samples#3583]
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/run/filesystem/index.js

## Did you change the file? If so, how?
No, happy to raise a PR.

## Describe the issue

Following the https://cloud.google.com/run/docs/tutorials/network-filesystems-filestore#before-you-begin created a Cloud Run service with VPC connector and Filestore.

Making an authenticated HTTP POST request from a VM probably behind a proxy to this Cloud Run app URL resulted in an HTTP 302 with a error logged to the Cloud Logging.

![X-forwarded-error](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/assets/19756773/150c1e8d-1152-4fd2-b1b7-bad0c0a4ef6e)

```
ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/app/node_modules/express-rate-limit/dist/index.cjs:166:13)
    at wrappedValidations.<computed> [as xForwardedForHeader] (/app/node_modules/express-rate-limit/dist/index.cjs:324:22)
    at Object.keyGenerator (/app/node_modules/express-rate-limit/dist/index.cjs:579:20)
   ```

#### CURL request and response 

```
$ curl -H "Authorization: Bearer $(gcloud auth print-identity-token)" https://xxxxxx.run.app -vvi
*   Trying 216.239.32.53:443...
* Connected to XXXXX.run.app (216.239.32.53) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.a.run.app
*  start date: Nov 20 08:02:20 2023 GMT
*  expire date: Feb 12 08:02:19 2024 GMT
*  subjectAltName: host "XXXXX.a.run.app" matched cert's "*.a.run.app"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1C3
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://XXXXX.a.run.app/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: XXXXXl.a.run.app]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.3.0]
* [HTTP/2] [1] [accept: */*]
* [HTTP/2] [1] [authorization: Bearer eXXXXXX
> GET / HTTP/2
> Host: XXXXX-el.a.run.app
> User-Agent: curl/8.3.0
> Accept: */*
> Authorization: Bearer XXXXX
> 
< HTTP/2 302 
HTTP/2 302 
< x-powered-by: Express
x-powered-by: Express
< x-ratelimit-limit: 100
x-ratelimit-limit: 100
< x-ratelimit-remaining: 97
x-ratelimit-remaining: 97
< x-ratelimit-reset: 1702213958
x-ratelimit-reset: 1702213958
< location: /mnt/nfs/filestore
location: /mnt/nfs/filestore
< vary: Accept
vary: Accept
< content-type: text/plain; charset=utf-8
content-type: text/plain; charset=utf-8
< x-cloud-trace-context: XXXXXa2ed;o=1
x-cloud-trace-context: XXXXXd;o=1
< date: Sun, 10 Dec 2023 12:59:43 GMT
date: Sun, 10 Dec 2023 12:59:43 GMT
< server: Google Frontend
server: Google Frontend
< content-length: 40
content-length: 40

< 
* Connection #0 to host filesystem-app-uplgjpifoa-el.a.run.app left intact
```
* It happened first time out out of 4 requests being made
* 2nd, 3rd and 4th requests lead to a empty response 
* 5th request resulted in the expected output  **Found. Redirecting to /mnt/nfs/filestore** .

Fix: https://github.com/express-rate-limit/express-rate-limit/wiki/Troubleshooting-Proxy-Issues
       https://express-rate-limit.mintlify.app/reference/error-codes#err-erl-unexpected-x-forwarded-for

**Comment by glasnt** [comment]
(googlers: conversation in associated b/)

**Comment by glasnt** [comment]
Summary of discussion: 

* The ValidationError is non-blocking, app will throw this error once in tutorial-defined operation (a simple browser get), but does not effect sample functionality. 
* Configuring the `trust proxy` option to enumerate the proxy conditions set in Cloud Run (`1`) eliminates this error, updates configuration as suggested by  https://github.com/express-rate-limit/express-rate-limit/wiki/Troubleshooting-Proxy-Issues. 

I'll submit a PR to resolve this.

**Comment by Mubtasimf443** [comment]
I am facing the same error

![Image](https://github.com/user-attachments/assets/45294bf8-22e5-4879-9279-2dd73de45a6f)

**Comment by sh4dowmyst1c** [comment]
I'm having same error when deploying n8n to kubernetes.

`k -n pathshards-prd logs n8n-deployment-d84cdfffb-4vmvc -f
No encryption key found - Auto-generating and saving to: /home/node/.n8n/config
Initializing n8n process
n8n ready on ::, port 5678
n8n Task Broker ready on 127.0.0.1, port 5679
[license SDK] Skipping renewal on init because renewal is not due yet or cert is not initialized
Registered runner "JS Task Runner" (YVypThI8pn3sU4hrWY_2N) 
Failed to load OIDC configuration from database, falling back to default configuration.
OIDC login is disabled.
Version: 1.102.4

Editor is now accessible via:
https://www.pathshards.com/n8n
ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/express-rate-limit@7.5.0_express@5.1.0/node_modules/express-rate-limit/dist/index.cjs:187:13)
    at Object.wrappedValidations.<computed> [as xForwardedForHeader] (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/express-rate-limit@7.5.0_express@5.1.0/node_modules/express-rate-limit/dist/index.cjs:398:22)
    at Object.keyGenerator (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/express-rate-limit@7.5.0_express@5.1.0/node_modules/express-rate-limit/dist/index.cjs:671:20)
    at /usr/local/lib/node_modules/n8n/node_modules/.pnpm/express-rate-limit@7.5.0_express@5.1.0/node_modules/express-rate-limit/dist/index.cjs:724:32
    at /usr/local/lib/node_modules/n8n/node_modules/.pnpm/express-rate-limit@7.5.0_express@5.1.0/node_modules/express-rate-limit/dist/index.cjs:704:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'`

**Comment by sh4dowmyst1c** [comment]
I'm having same error when deploying n8n to k8s.

> Log from POD after initialization:

```markdown
No encryption key found - Auto-generating and saving to: /home/node/.n8n/config
Initializing n8n process
n8n ready on ::, port 5678
n8n Task Broker ready on 127.0.0.1, port 5679
[license SDK] Skipping renewal on init because renewal is not due yet or cert is not initialized
Registered runner "JS Task Runner" (YVypThI8pn3sU4hrWY_2N) 
Failed to load OIDC configuration from database, falling back to default configuration.
OIDC login is disabled.
Version: 1.102.4

Editor is now accessible via:
https://mydomain/n8n
ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/express-rate-limit@7.5.0_express@5.1.0/node_modules/express-rate-limit/dist/index.cjs:187:13)
    at Object.wrappedValidations.<computed> [as xForwardedForHeader] (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/express-rate-limit@7.5.0_express@5.1.0/node_modules/express-rate-limit/dist/index.cjs:398:22)
    at Object.keyGenerator (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/express-rate-limit@7.5.0_express@5.1.0/node_modules/express-rate-limit/dist/index.cjs:671:20)
    at /usr/local/lib/node_modules/n8n/node_modules/.pnpm/express-rate-limit@7.5.0_express@5.1.0/node_modules/express-rate-limit/dist/index.cjs:724:32
    at /usr/local/lib/node_modules/n8n/node_modules/.pnpm/express-rate-limit@7.5.0_express@5.1.0/node_modules/express-rate-limit/dist/index.cjs:704:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/
```
