### ISSUE TITLE
EOS (End of Support) for nodejs16

### ISSUE THREAD

**Issue by Judge-Paul** [GoogleCloudPlatform/nodejs-docs-samples#3602]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**The issue you're having must be related to a file in this repository.** We are unable to provide assistance for issues unrelated to samples in this repository.

Please include as much information as possible:

## In which file did you encounter the issue?
[yaml example for app engine](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/HEAD/appengine/building-an-app/build/app.yaml)

## Did you change the file? If so, how?

Update to use node 18

## Describe the issue

Node 16 is about to reach its End of support by the node community and app engine is throwing an error that I won't be allowed to use node 16 by that time so I think the docs should be updated to use node 18

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by matharden** [comment]
References to Node v16 exist in many other files. See https://github.com/GoogleCloudPlatform/nodejs-docs-samples/commit/12253139b0abfaa742f15a1a0b44fe67242f955d

**Comment by Judge-Paul** [comment]
> References to Node v16 exist in many other files. See [1225313](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/commit/12253139b0abfaa742f15a1a0b44fe67242f955d)

Oh okay, but are you working on updating it across all files?

**Comment by iennae** [comment]
@Judge-Paul Thanks so much for filing this issue; We'll sort out getting this updated to the version needed (20 at this time for App Engine).

**Comment by iennae** [comment]
Thanks again, had to resolve some other issues but this is now resolved for this sample. There are other app engine samples that will need to get updated but that is tracked in a separate issue.
