### ISSUE TITLE
SQL sample README suggests using JSON keys against best practices

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/nodejs-docs-samples#3634]
The [README for Cloud SQL MySQL samples](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/cloud-sql/mysql/mysql/README.md) includes instructions to download a JSON key:

---
***4. Create a service account following these instructions, and then grant the roles/cloudsql.client role following these instructions.***

***Download a JSON key to use to authenticate your connection.***

---
The console page for downloading JSON keys includes the warning:

---
***Service account keys could pose a security risk if compromised. We recommend you avoid downloading service account keys and instead use the Workload Identity Federation . You can learn more about the best way to authenticate service accounts on Google Cloud here.***

---
This conflicting messaging could cause friction for new users to Google Cloud.

### Recommendation:

Update the Cloud SQL sample README to replace the use of JSON keys with an alternative such as Workload Identity Federation or service account impersonation.

**Comment by iennae** [comment]
@mrfaizal do you have any insight on who might be able to assess and triage this ? Thanks

**Comment by iennae** [comment]
@enocom another one for you if you have bandwidth

**Comment by enocom** [comment]
cc @jackwotherspoon who's going to significantly clean up all these samples.

I can grab this one as well. The README really shouldn't exist and instead just reference the public docs (where this information should live as a single source of truth). For now, I'll just clean up these items.
