### ISSUE TITLE
Steps in Cloud SQL README are out of date and do not work

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/nodejs-docs-samples#3635]
The [README for Cloud SQL MySQL samples](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/cloud-sql/mysql/mysql/README.md) has several problems:

- it includes a link to [our docs to install cloud-sql-proxy](https://cloud.google.com/sql/docs/mysql/sql-proxy#install). The steps after this however are out of date, as they use the older `cloud_sql_proxy` instead of `cloud-sql-proxy`. **ALL COMMANDS USING `cloud_sql_proxy` FAIL.** 
- step 5 sets the environment variable for `INSTANCE_CONNECTION_NAME`. Subsequence steps still use `<project-id>:<region>:<instance-name>` instead of the variable
- the flag `--credential_file` used in these steps does not exist; it is `--credentials-file`

## Recommendation:
These instructions do not work. They should be updated ASAP as they are linked directly from official Cloud SQL documentation. See [Connect from Cloud Run](https://cloud.google.com/sql/docs/mysql/connect-run#connect)**

**Comment by iennae** [comment]
@mrfaizal do you have any insight on who might be able to assess and triage this ? Thanks

**Comment by enocom** [comment]
This is probably an issue across all engines. I can send a quick PR to address the key v1 vs v2 Cloud SQL Proxy concerns.

Separately, we are planning a general rewrite of these samples. cc @jackwotherspoon
