### ISSUE TITLE
Nodejs16 AppEngine is now EOL, please update all samples to nodejs20 the latest AppEngine node version.

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/nodejs-docs-samples#3645]
Similar to https://github.com/GoogleCloudPlatform/nodejs-docs-samples/commit/12253139b0abfaa742f15a1a0b44fe67242f955d
we now need to bump all App Engine Nodejs samples to nodejs 20 which is the latest support.

This will also make the public Google documentation up to date (see https://cloud.google.com/appengine/docs/standard/nodejs/building-app/writing-web-service#creating_the_appyaml_file
which is sending the wrong signal to the customers).

See supported versions at https://cloud.google.com/appengine/docs/standard/lifecycle/support-schedule#nodejs

Samples are a critical part of the user experience and onboarding, so our docs have to be in sync with latest releases.

**Comment by iennae** [comment]
@jinglundong can you identify someone who can take this on from App Engine? Thanks.

**Comment by jinglundong** [comment]
ACK. I believe we have this one in our backlog. We will groom and prioritize accordingly.
