### ISSUE TITLE
storage-control: Samples for Managed Folders

### ISSUE THREAD

**Issue by sofisl** [GoogleCloudPlatform/nodejs-docs-samples#3713]
We would like to have samples for the following managed folders operations:
Create
Get
List
Delete

See the java samples as the canonical sample https://github.com/googleapis/java-storage/pull/2562
Thanks!

see: https://github.com/googleapis/google-cloud-node/issues/5441

**Comment by sydney-munro** [comment]
hey @ddelgrosso1 when can we get this scheduled?
