### ISSUE TITLE
Does not install on macos sierra

### ISSUE THREAD

**Issue by hanselke** [GoogleCloudPlatform/nodejs-docs-samples#373]
npm install -g @google-cloud/functions-emulator
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/Cellar/node/7.9.0/libexec/npm/bin/functions -> /usr/local/Cellar/node/7.9.0/libexec/npm/lib/node_modules/@google-cloud/functions-emulator/bin/functions
/usr/local/Cellar/node/7.9.0/libexec/npm/bin/functions-emulator -> /usr/local/Cellar/node/7.9.0/libexec/npm/lib/node_modules/@google-cloud/functions-emulator/bin/functions

> grpc@1.2.4 install /usr/local/Cellar/node/7.9.0/libexec/npm/lib/node_modules/@google-cloud/functions-emulator/node_modules/grpc
> node-pre-gyp install --fallback-to-build

[grpc] Success: "/usr/local/Cellar/node/7.9.0/libexec/npm/lib/node_modules/@google-cloud/functions-emulator/node_modules/grpc/src/node/extension_binary/grpc_node.node" is installed via remote

> @google-cloud/functions-emulator@1.0.0-alpha.16 postinstall /usr/local/Cellar/node/7.9.0/libexec/npm/lib/node_modules/@google-cloud/functions-emulator
> node scripts/upgrade-warning

If you're upgrading @google-cloud/functions-emulator, these
are the recommended upgrade steps:

1.  Stop the currently running emulator, if any:

        functions stop

2.  Uninstall the current emulator, if any:

        npm uninstall -g @google-cloud/functions-emulator

3.  Install the new version of the emulator:

        npm install -g @google-cloud/functions-emulator

If you have trouble after upgrading, try deleting the config
directory found in:

    ~/.config/configstore/@google-cloud/functions-emulator

Then restart the emulator. You can also check for any renegade
Node.js emulator processes that may need to be killed:

    ps aux | grep node

/usr/local/Cellar/node/7.9.0/libexec/npm/lib
└─┬ @google-cloud/functions-emulator@1.0.0-alpha.16 
  ├─┬ @google-cloud/storage@1.0.0 
  │ ├─┬ @google-cloud/common@0.13.2 
  │ │ ├── array-uniq@1.0.3 
  │ │ ├── ent@2.2.0 
  │ │ ├─┬ google-auto-auth@0.6.1 
  │ │ │ ├─┬ gcp-metadata@0.1.0 
  │ │ │ │ └─┬ retry-request@1.3.2 
  │ │ │ │   └─┬ request@2.76.0 
  │ │ │ │     ├── caseless@0.11.0 
  │ │ │ │     ├─┬ har-validator@2.0.6 
  │ │ │ │     │ ├─┬ chalk@1.1.3 
  │ │ │ │     │ │ ├── ansi-styles@2.2.1 
  │ │ │ │     │ │ ├── escape-string-regexp@1.0.5 
  │ │ │ │     │ │ ├── has-ansi@2.0.0 
  │ │ │ │     │ │ └── supports-color@2.0.0 
  │ │ │ │     │ ├─┬ commander@2.9.0 
  │ │ │ │     │ │ └── graceful-readlink@1.0.1 
  │ │ │ │     │ └─┬ is-my-json-valid@2.16.0 
  │ │ │ │     │   ├── generate-function@2.0.0 
  │ │ │ │     │   ├─┬ generate-object-property@1.2.0 
  │ │ │ │     │   │ └── is-property@1.0.2 
  │ │ │ │     │   └── jsonpointer@4.0.1 
  │ │ │ │     ├── node-uuid@1.4.8 
  │ │ │ │     └── tunnel-agent@0.4.3 
  │ │ │ └── object-assign@3.0.0 
  │ │ ├── log-driver@1.2.5 
  │ │ ├── methmeth@1.1.0 
  │ │ ├── modelo@4.2.0 
  │ │ ├─┬ request@2.81.0 
  │ │ │ ├── aws-sign2@0.6.0 
  │ │ │ ├── aws4@1.6.0 
  │ │ │ ├── caseless@0.12.0 
  │ │ │ ├─┬ combined-stream@1.0.5 
  │ │ │ │ └── delayed-stream@1.0.0 
  │ │ │ ├── forever-agent@0.6.1 
  │ │ │ ├─┬ har-validator@4.2.1 
  │ │ │ │ └── har-schema@1.0.5 
  │ │ │ ├─┬ hawk@3.1.3 
  │ │ │ │ ├── boom@2.10.1 
  │ │ │ │ ├── cryptiles@2.0.5 
  │ │ │ │ ├── hoek@2.16.3 
  │ │ │ │ └── sntp@1.0.9 
  │ │ │ ├─┬ http-signature@1.1.1 
  │ │ │ │ ├── assert-plus@0.2.0 
  │ │ │ │ ├─┬ jsprim@1.4.0 
  │ │ │ │ │ ├── assert-plus@1.0.0 
  │ │ │ │ │ ├── extsprintf@1.0.2 
  │ │ │ │ │ ├── json-schema@0.2.3 
  │ │ │ │ │ └── verror@1.3.6 
  │ │ │ │ └─┬ sshpk@1.13.0 
  │ │ │ │   ├── asn1@0.2.3 
  │ │ │ │   ├── assert-plus@1.0.0 
  │ │ │ │   ├── bcrypt-pbkdf@1.0.1 
  │ │ │ │   ├─┬ dashdash@1.14.1 
  │ │ │ │   │ └── assert-plus@1.0.0 
  │ │ │ │   ├── ecc-jsbn@0.1.1 
  │ │ │ │   ├─┬ getpass@0.1.7 
  │ │ │ │   │ └── assert-plus@1.0.0 
  │ │ │ │   ├── jodid25519@1.0.2 
  │ │ │ │   ├── jsbn@0.1.1 
  │ │ │ │   └── tweetnacl@0.14.5 
  │ │ │ ├── is-typedarray@1.0.0 
  │ │ │ ├── json-stringify-safe@5.0.1 
  │ │ │ ├── oauth-sign@0.8.2 
  │ │ │ ├── performance-now@0.2.0 
  │ │ │ ├── qs@6.4.0 
  │ │ │ ├── stringstream@0.0.5 
  │ │ │ ├─┬ tough-cookie@2.3.2 
  │ │ │ │ └── punycode@1.4.1 
  │ │ │ └── tunnel-agent@0.6.0 
  │ │ ├── retry-request@2.0.0 
  │ │ └─┬ split-array-stream@1.0.0 
  │ │   ├── async@1.5.2 
  │ │   └── is-stream-ended@0.1.0 
  │ ├── arrify@1.0.1 
  │ ├── async@2.4.0 
  │ ├─┬ concat-stream@1.6.0 
  │ │ ├── inherits@2.0.3 
  │ │ ├─┬ readable-stream@2.2.9 
  │ │ │ ├── buffer-shims@1.0.0 
  │ │ │ ├── core-util-is@1.0.2 
  │ │ │ ├── isarray@1.0.0 
  │ │ │ ├── process-nextick-args@1.0.7 
  │ │ │ ├── string_decoder@1.0.0 
  │ │ │ └── util-deprecate@1.0.2 
  │ │ └── typedarray@0.0.6 
  │ ├─┬ create-error-class@3.0.2 
  │ │ └── capture-stack-trace@1.0.0 
  │ ├─┬ duplexify@3.5.0 
  │ │ ├─┬ end-of-stream@1.0.0 
  │ │ │ └── once@1.3.3 
  │ │ └── stream-shift@1.0.0 
  │ ├── extend@3.0.1 
  │ ├─┬ gcs-resumable-upload@0.7.6 
  │ │ └── buffer-equal@1.0.0 
  │ ├── hash-stream-validation@0.2.1 
  │ ├── is@3.2.1 
  │ ├─┬ mime-types@2.1.15 
  │ │ └── mime-db@1.27.0 
  │ ├─┬ once@1.4.0 
  │ │ └── wrappy@1.0.2 
  │ ├─┬ pumpify@1.3.5 
  │ │ └─┬ pump@1.0.2 
  │ │   └── end-of-stream@1.4.0 
  │ ├─┬ stream-events@1.0.1 
  │ │ └── stubs@1.1.2 
  │ ├── string-format-obj@1.1.0 
  │ └─┬ through2@2.0.3 
  │   └── xtend@4.0.1 
  ├── adm-zip@0.4.7 
  ├─┬ ajv@4.11.6 
  │ ├── co@4.6.0 
  │ └─┬ json-stable-stringify@1.0.1 
  │   └── jsonify@0.0.0 
  ├─┬ body-parser@1.17.1 
  │ ├── bytes@2.4.0 
  │ ├── content-type@1.0.2 
  │ ├─┬ debug@2.6.1 
  │ │ └── ms@0.7.2 
  │ ├── depd@1.1.0 
  │ ├── http-errors@1.6.1 
  │ ├── iconv-lite@0.4.15 
  │ ├─┬ on-finished@2.3.0 
  │ │ └── ee-first@1.1.1 
  │ ├── qs@6.4.0 
  │ ├─┬ raw-body@2.2.0 
  │ │ └── unpipe@1.0.0 
  │ └─┬ type-is@1.6.15 
  │   └── media-typer@0.3.0 
  ├─┬ cli-table2@0.2.0 
  │ ├── lodash@3.10.1 
  │ └─┬ string-width@1.0.2 
  │   ├── code-point-at@1.1.0 
  │   ├─┬ is-fullwidth-code-point@1.0.0 
  │   │ └── number-is-nan@1.0.1 
  │   └─┬ strip-ansi@3.0.1 
  │     └── ansi-regex@2.1.1 
  ├── colors@1.1.2 
  ├─┬ configstore@3.0.0 
  │ ├─┬ dot-prop@4.1.1 
  │ │ └── is-obj@1.0.1 
  │ ├── graceful-fs@4.1.11 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ ├─┬ unique-string@1.0.0 
  │ │ └── crypto-random-string@1.0.0 
  │ ├─┬ write-file-atomic@1.3.4 
  │ │ ├── imurmurhash@0.1.4 
  │ │ └── slide@1.1.6 
  │ └── xdg-basedir@3.0.0 
  ├─┬ express@4.15.2 
  │ ├─┬ accepts@1.3.3 
  │ │ └── negotiator@0.6.1 
  │ ├── array-flatten@1.1.1 
  │ ├── content-disposition@0.5.2 
  │ ├── cookie@0.3.1 
  │ ├── cookie-signature@1.0.6 
  │ ├── encodeurl@1.0.1 
  │ ├── escape-html@1.0.3 
  │ ├── etag@1.8.0 
  │ ├─┬ finalhandler@1.0.2 
  │ │ └─┬ debug@2.6.4 
  │ │   └── ms@0.7.3 
  │ ├── fresh@0.5.0 
  │ ├── merge-descriptors@1.0.1 
  │ ├── methods@1.1.2 
  │ ├── parseurl@1.3.1 
  │ ├── path-to-regexp@0.1.7 
  │ ├─┬ proxy-addr@1.1.4 
  │ │ ├── forwarded@0.1.0 
  │ │ └── ipaddr.js@1.3.0 
  │ ├── qs@6.4.0 
  │ ├── range-parser@1.2.0 
  │ ├─┬ send@0.15.1 
  │ │ ├── destroy@1.0.4 
  │ │ └── mime@1.3.4 
  │ ├── serve-static@1.12.1 
  │ ├── setprototypeof@1.0.3 
  │ ├── statuses@1.3.1 
  │ ├── utils-merge@1.0.0 
  │ └── vary@1.1.1 
  ├── google-proto-files@0.11.0 
  ├─┬ googleapis@19.0.0 
  │ ├── async@2.3.0 
  │ ├─┬ google-auth-library@0.10.0 
  │ │ ├─┬ gtoken@1.2.2 
  │ │ │ └─┬ google-p12-pem@0.1.2 
  │ │ │   └── node-forge@0.7.1 
  │ │ ├─┬ jws@3.1.4 
  │ │ │ ├── base64url@2.0.0 
  │ │ │ └─┬ jwa@1.1.5 
  │ │ │   ├── buffer-equal-constant-time@1.0.1 
  │ │ │   └── ecdsa-sig-formatter@1.0.9 
  │ │ └── lodash.noop@3.0.1 
  │ └── string-template@1.0.0 
  ├─┬ got@6.7.1 
  │ ├── duplexer3@0.1.4 
  │ ├── get-stream@3.0.0 
  │ ├── is-redirect@1.0.0 
  │ ├── is-retry-allowed@1.1.0 
  │ ├── is-stream@1.1.0 
  │ ├── lowercase-keys@1.0.0 
  │ ├── safe-buffer@5.0.1 
  │ ├── timed-out@4.0.1 
  │ ├── unzip-response@2.0.1 
  │ └─┬ url-parse-lax@1.0.0 
  │   └── prepend-http@1.0.4 
  ├─┬ grpc@1.2.4 
  │ ├── arguejs@0.2.3 
  │ ├── nan@2.6.2 
  │ ├─┬ node-pre-gyp@0.6.34 
  │ │ ├─┬ mkdirp@0.5.1 
  │ │ │ └── minimist@0.0.8 
  │ │ ├─┬ nopt@4.0.1 
  │ │ │ ├── abbrev@1.1.0 
  │ │ │ └─┬ osenv@0.1.4 
  │ │ │   ├── os-homedir@1.0.2 
  │ │ │   └── os-tmpdir@1.0.2 
  │ │ ├─┬ npmlog@4.0.2 
  │ │ │ ├─┬ are-we-there-yet@1.1.2 
  │ │ │ │ ├── delegates@1.0.0 
  │ │ │ │ └─┬ readable-stream@2.2.9 
  │ │ │ │   ├── buffer-shims@1.0.0 
  │ │ │ │   ├── core-util-is@1.0.2 
  │ │ │ │   ├── inherits@2.0.3 
  │ │ │ │   ├── isarray@1.0.0 
  │ │ │ │   ├── process-nextick-args@1.0.7 
  │ │ │ │   ├── string_decoder@1.0.0 
  │ │ │ │   └── util-deprecate@1.0.2 
  │ │ │ ├── console-control-strings@1.1.0 
  │ │ │ ├─┬ gauge@2.7.3 
  │ │ │ │ ├── aproba@1.1.1 
  │ │ │ │ ├── has-unicode@2.0.1 
  │ │ │ │ ├── object-assign@4.1.1 
  │ │ │ │ ├── signal-exit@3.0.2 
  │ │ │ │ ├─┬ string-width@1.0.2 
  │ │ │ │ │ ├── code-point-at@1.1.0 
  │ │ │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
  │ │ │ │ │   └── number-is-nan@1.0.1 
  │ │ │ │ ├─┬ strip-ansi@3.0.1 
  │ │ │ │ │ └── ansi-regex@2.1.1 
  │ │ │ │ └── wide-align@1.1.0 
  │ │ │ └── set-blocking@2.0.0 
  │ │ ├─┬ rc@1.2.1 
  │ │ │ ├── deep-extend@0.4.1 
  │ │ │ ├── ini@1.3.4 
  │ │ │ ├── minimist@1.2.0 
  │ │ │ └── strip-json-comments@2.0.1 
  │ │ ├─┬ request@2.81.0 
  │ │ │ ├── aws-sign2@0.6.0 
  │ │ │ ├── aws4@1.6.0 
  │ │ │ ├── caseless@0.12.0 
  │ │ │ ├─┬ combined-stream@1.0.5 
  │ │ │ │ └── delayed-stream@1.0.0 
  │ │ │ ├── extend@3.0.0 
  │ │ │ ├── forever-agent@0.6.1 
  │ │ │ ├─┬ form-data@2.1.4 
  │ │ │ │ └── asynckit@0.4.0 
  │ │ │ ├─┬ har-validator@4.2.1 
  │ │ │ │ ├─┬ ajv@4.11.6 
  │ │ │ │ │ ├── co@4.6.0 
  │ │ │ │ │ └─┬ json-stable-stringify@1.0.1 
  │ │ │ │ │   └── jsonify@0.0.0 
  │ │ │ │ └── har-schema@1.0.5 
  │ │ │ ├─┬ hawk@3.1.3 
  │ │ │ │ ├── boom@2.10.1 
  │ │ │ │ ├── cryptiles@2.0.5 
  │ │ │ │ ├── hoek@2.16.3 
  │ │ │ │ └── sntp@1.0.9 
  │ │ │ ├─┬ http-signature@1.1.1 
  │ │ │ │ ├── assert-plus@0.2.0 
  │ │ │ │ ├─┬ jsprim@1.4.0 
  │ │ │ │ │ ├── assert-plus@1.0.0 
  │ │ │ │ │ ├── extsprintf@1.0.2 
  │ │ │ │ │ ├── json-schema@0.2.3 
  │ │ │ │ │ └── verror@1.3.6 
  │ │ │ │ └─┬ sshpk@1.11.0 
  │ │ │ │   ├── asn1@0.2.3 
  │ │ │ │   ├── assert-plus@1.0.0 
  │ │ │ │   ├── bcrypt-pbkdf@1.0.1 
  │ │ │ │   ├── dashdash@1.14.1 
  │ │ │ │   ├── ecc-jsbn@0.1.1 
  │ │ │ │   ├── getpass@0.1.6 
  │ │ │ │   ├── jodid25519@1.0.2 
  │ │ │ │   ├── jsbn@0.1.1 
  │ │ │ │   └── tweetnacl@0.14.5 
  │ │ │ ├── is-typedarray@1.0.0 
  │ │ │ ├── isstream@0.1.2 
  │ │ │ ├── json-stringify-safe@5.0.1 
  │ │ │ ├─┬ mime-types@2.1.15 
  │ │ │ │ └── mime-db@1.27.0 
  │ │ │ ├── oauth-sign@0.8.2 
  │ │ │ ├── performance-now@0.2.0 
  │ │ │ ├── qs@6.4.0 
  │ │ │ ├── safe-buffer@5.0.1 
  │ │ │ ├── stringstream@0.0.5 
  │ │ │ ├─┬ tough-cookie@2.3.2 
  │ │ │ │ └── punycode@1.4.1 
  │ │ │ ├── tunnel-agent@0.6.0 
  │ │ │ └── uuid@3.0.1 
  │ │ ├─┬ rimraf@2.6.1 
  │ │ │ └─┬ glob@7.1.1 
  │ │ │   ├── fs.realpath@1.0.0 
  │ │ │   ├─┬ inflight@1.0.6 
  │ │ │   │ └── wrappy@1.0.2 
  │ │ │   ├── inherits@2.0.3 
  │ │ │   ├─┬ minimatch@3.0.3 
  │ │ │   │ └─┬ brace-expansion@1.1.7 
  │ │ │   │   ├── balanced-match@0.4.2 
  │ │ │   │   └── concat-map@0.0.1 
  │ │ │   ├─┬ once@1.4.0 
  │ │ │   │ └── wrappy@1.0.2 
  │ │ │   └── path-is-absolute@1.0.1 
  │ │ ├── semver@5.3.0 
  │ │ ├─┬ tar@2.2.1 
  │ │ │ ├── block-stream@0.0.9 
  │ │ │ ├─┬ fstream@1.0.11 
  │ │ │ │ └── graceful-fs@4.1.11 
  │ │ │ └── inherits@2.0.3 
  │ │ └─┬ tar-pack@3.4.0 
  │ │   ├─┬ debug@2.6.3 
  │ │   │ └── ms@0.7.2 
  │ │   ├─┬ fstream@1.0.11 
  │ │   │ ├── graceful-fs@4.1.11 
  │ │   │ └── inherits@2.0.3 
  │ │   ├─┬ fstream-ignore@1.0.5 
  │ │   │ ├── inherits@2.0.3 
  │ │   │ └─┬ minimatch@3.0.3 
  │ │   │   └─┬ brace-expansion@1.1.7 
  │ │   │     ├── balanced-match@0.4.2 
  │ │   │     └── concat-map@0.0.1 
  │ │   ├─┬ once@1.4.0 
  │ │   │ └── wrappy@1.0.2 
  │ │   ├─┬ readable-stream@2.2.9 
  │ │   │ ├── buffer-shims@1.0.0 
  │ │   │ ├── core-util-is@1.0.2 
  │ │   │ ├── inherits@2.0.3 
  │ │   │ ├── isarray@1.0.0 
  │ │   │ ├── process-nextick-args@1.0.7 
  │ │   │ ├── string_decoder@1.0.0 
  │ │   │ └── util-deprecate@1.0.2 
  │ │   └── uid-number@0.0.6 
  │ └─┬ protobufjs@5.0.2 
  │   ├─┬ ascli@1.0.1 
  │   │ ├── colour@0.7.1 
  │   │ └── optjs@3.2.2 
  │   ├─┬ bytebuffer@5.0.1 
  │   │ └── long@3.2.0 
  │   └─┬ yargs@3.32.0 
  │     ├── camelcase@2.1.1 
  │     └── window-size@0.1.4 
  ├─┬ http-proxy@1.16.2 
  │ ├── eventemitter3@1.2.0 
  │ └── requires-port@1.0.0 
  ├── lodash@4.17.4 
  ├─┬ prompt@1.0.0 
  │ ├── pkginfo@0.4.0 
  │ ├─┬ read@1.0.7 
  │ │ └── mute-stream@0.0.7 
  │ ├── revalidator@0.1.8 
  │ ├─┬ utile@0.3.0 
  │ │ ├── async@0.9.2 
  │ │ ├── deep-equal@0.2.2 
  │ │ ├── i@0.3.5 
  │ │ └── ncp@1.0.1 
  │ └─┬ winston@2.1.1 
  │   ├── async@1.0.0 
  │   ├── colors@1.0.3 
  │   └── pkginfo@0.3.1 
  ├─┬ rimraf@2.6.1 
  │ └─┬ glob@7.1.1 
  │   ├── fs.realpath@1.0.0 
  │   ├── inflight@1.0.6 
  │   ├─┬ minimatch@3.0.3 
  │   │ └─┬ brace-expansion@1.1.7 
  │   │   ├── balanced-match@0.4.2 
  │   │   └── concat-map@0.0.1 
  │   └── path-is-absolute@1.0.1 
  ├── semver@5.3.0 
  ├─┬ serializerr@1.0.3 
  │ └── protochain@1.0.5 
  ├─┬ supertest@3.0.0 
  │ └─┬ superagent@3.5.2 
  │   ├── component-emitter@1.2.1 
  │   ├── cookiejar@2.1.1 
  │   ├─┬ form-data@2.1.4 
  │   │ └── asynckit@0.4.0 
  │   ├── formidable@1.1.1 
  │   └── qs@6.3.2 
  ├─┬ tmp@0.0.31 
  │ └── os-tmpdir@1.0.2 
  ├── uuid@3.0.1 
  ├─┬ winston@2.3.1 
  │ ├── async@1.0.0 
  │ ├── colors@1.0.3 
  │ ├── cycle@1.0.3 
  │ ├── eyes@0.1.8 
  │ ├── isstream@0.1.2 
  │ └── stack-trace@0.0.9 
  └─┬ yargs@7.1.0 
    ├── camelcase@3.0.0 
    ├─┬ cliui@3.2.0 
    │ └── wrap-ansi@2.1.0 
    ├── decamelize@1.2.0 
    ├── get-caller-file@1.0.2 
    ├─┬ os-locale@1.4.0 
    │ └─┬ lcid@1.0.0 
    │   └── invert-kv@1.0.0 
    ├─┬ read-pkg-up@1.0.1 
    │ ├─┬ find-up@1.1.2 
    │ │ ├── path-exists@2.1.0 
    │ │ └─┬ pinkie-promise@2.0.1 
    │ │   └── pinkie@2.0.4 
    │ └─┬ read-pkg@1.1.0 
    │   ├─┬ load-json-file@1.1.0 
    │   │ ├─┬ parse-json@2.2.0 
    │   │ │ └─┬ error-ex@1.3.1 
    │   │ │   └── is-arrayish@0.2.1 
    │   │ ├── pify@2.3.0 
    │   │ └─┬ strip-bom@2.0.0 
    │   │   └── is-utf8@0.2.1 
    │   ├─┬ normalize-package-data@2.3.8 
    │   │ ├── hosted-git-info@2.4.2 
    │   │ ├─┬ is-builtin-module@1.0.0 
    │   │ │ └── builtin-modules@1.1.1 
    │   │ └─┬ validate-npm-package-license@3.0.1 
    │   │   ├─┬ spdx-correct@1.0.2 
    │   │   │ └── spdx-license-ids@1.2.2 
    │   │   └── spdx-expression-parse@1.0.4 
    │   └── path-type@1.1.0 
    ├── require-directory@2.1.1 
    ├── require-main-filename@1.0.1 
    ├── set-blocking@2.0.0 
    ├── which-module@1.0.0 
    ├── y18n@3.2.1 
    └─┬ yargs-parser@5.0.0 
      └── camelcase@3.0.0 

functions command does not exist after installing. have uninstalled, deleted config and reinstalled but not luck

**Comment by jmdobry** [comment]
Did you mean to open this issue on https://github.com/GoogleCloudPlatform/cloud-functions-emulator ?

**Comment by JustinBeckwith** [comment]
Greetings!  This issue has been hanging out for a while.  If you're still running into problems... please do let us know!  We're going to close this one out for now.
