### ISSUE TITLE
speech to text v2 INVALID_ARGUMENT: Invalid resource field value in the request

### ISSUE THREAD

**Issue by tdd102** [GoogleCloudPlatform/nodejs-docs-samples#3733]
if (speechClient == null) {
                speechClient = NaturalApp.context.resources.openRawResource(R.raw.credential).use {
                    SpeechClient.create(
                        SpeechSettings.newBuilder()
                            .setCredentialsProvider { GoogleCredentials.fromStream(it) }
                            .build())
                }
            }

            if (clientStream == null){
                clientStream =
                    speechClient?.streamingRecognizeCallable()?.splitCall(responseObserver)

                var explicitDecodingConfig = ExplicitDecodingConfig.newBuilder()
                    .setEncoding(ExplicitDecodingConfig.AudioEncoding.LINEAR16)
                    .setSampleRateHertz(16000)
                    .build()
                val recognitionConfig = RecognitionConfig.newBuilder()
                    .setAutoDecodingConfig(AutoDetectDecodingConfig.getDefaultInstance())
                    .addLanguageCodes("en-US")
                    .build()
                
                val streamingRecognitionConfig = StreamingRecognitionConfig.newBuilder()
                    .setConfig(recognitionConfig)
                    .setStreamingFeatures(
                        StreamingRecognitionFeatures.getDefaultInstance())//如果设为true会立即返回结果，很多近似的结果；false则返回最佳匹配结果，较慢
                    .build()
                var request = StreamingRecognizeRequest.newBuilder()
                    .setStreamingConfig(streamingRecognitionConfig)
                    .build()
                // The first request in a streaming call has to be a config
                clientStream?.send(request)

**Comment by iennae** [comment]
Can you provide additional context of what the problem you are trying to solve is? It'd be helpful if you provided a link to the sample you are using as well. Thanks.

**Comment by iennae** [comment]
I'm going to close this issue as it hasn't had a response in the last month. If you want to update with the name of the sample and reopen that would be great. Thanks!
