### ISSUE TITLE
BigQuery: How do i get asynchronously a job query result with job id

### ISSUE THREAD

**Issue by jmunozz** [GoogleCloudPlatform/nodejs-docs-samples#374]
Hello, 
I can't figure out how to perform asynchronous call to API to retrieve results from a query job with just jobId.

I tried bigquery.jobs.getQueryResult(jobId) => bigquery.jobs does not exist
I tried bigquery.getQueryResult(jobId) => the function does not exist

My guess is I first need to get a job ressource then execute ressource.getQueryResult() but I can't find how to get this job resource.

Thanks

**Comment by jmdobry** [comment]
```js
const bigquery = require('@google-cloud/bigquery')();

bigquery
  .job('your-job-id')
  .getQueryResults()
  .then(([rows]) => {
    console.log(rows);
  });
```

as seen here: https://googlecloudplatform.github.io/google-cloud-node/#/docs/bigquery/latest/bigquery/job

**Comment by jmunozz** [comment]
Thanks.
 It works perfectly fine.
(I thought this version of the doc was deprecated because it shows '/bigquery/0.9.2' in the URL)
