### ISSUE TITLE
build: run/websockets tests appear to be broken by a dependency on a GCR image

### ISSUE THREAD

**Issue by briandorsey** [GoogleCloudPlatform/nodejs-docs-samples#3827]
While attempting to disable flaky-bot in #3822, tests for run/websockets are now failing with a permissions error. 

After troubleshooting (thanks @subfuzion !), it appears that test is relying on a base image hosted in GCR which has recently been deprecated.

**Comment by subfuzion** [comment]
I was able to make a fix, but not an optimal one; the internal decision was made to temporarily disable `run/websockets` testing (b/366619034), merged with #3853.

**Comment by subfuzion** [comment]
Testing is now blocked on `run/markdown-preview`. See: #3857.
