### ISSUE TITLE
can not connect google @ google-cloud / storage to the project.

### ISSUE THREAD

**Issue by alexsanderkhitev** [GoogleCloudPlatform/nodejs-docs-samples#385]
Hello! I tried to connect google cloud storage to the project as follows.

```
MacBook-Pro:node_modules alexsanderjob$ npm install --save @google-cloud/storage
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
functions@ /Users/alexsanderjob/Desktop/ExampleCloudFunctions/functions
└── @google-cloud/storage@1.1.0 
```
I wrote the following code in index.js

```
// Imports the Google Cloud client library
const Storage = require('@google-cloud/storage');

// Your Google Cloud Platform project ID
const projectId = 'example-example7';

// Instantiates a client
const storageClient = Storage({
  projectId: projectId
});
```

When I open this file through the Visual Studio Code, and when I try to interact with the storage client, nothing happens. My case is the following, I need to delete photos of user cards from Firebase Storage when it deleted my account. Please tell me how it can be done?

**Comment by jmdobry** [comment]
[Delete a single file in a bucket](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/storage/files.js#L141)

Delete all files in a bucket:

```js
const Storage = require('@google-cloud/storage');

// Instantiates a client
const storageClient = Storage({ projectId: 'example-example7' });

// References an existing bucket, e.g. "my-bucket"
const bucket = storageClient.bucket('my-bucket');

// Deletes all files in the bucket
bucket.deleteFiles()
  .then(() => {
    console.log('All files deleted.');
  })
  .catch((err) => {
    console.error('ERROR:', err);
  });
```

[Delete a bucket](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/storage/buckets.js#L64)

**Comment by ace-n** [comment]
Closing due to staleness; @alexsanderkhitev feel free to reopen if you're still having trouble. Thanks!
