### ISSUE TITLE
Client GRPC deadline too short

### ISSUE THREAD

**Issue by Hakim2014** [GoogleCloudPlatform/nodejs-docs-samples#411]
Hi,

I am using microphone for speech service and it works fine for 1 min, after that it throws an error "Client GRPC deadline too short. Should be at least: 3 * audio-duration + 5 seconds. Current deadline is: 186.99880755622871 second(s). Required at least: 188 second(s)" and then speech stops working. What can be done here to sort this out. I am using "node-record-lpcm16" for microphone.

**Comment by fhinkel** [comment]
If the issue still persists, please file it [here](https://github.com/googleapis/nodejs-speech). Thank you.
