### ISSUE TITLE
Unable to run on raspberry pi zero w

### ISSUE THREAD

**Issue by Lezeper** [GoogleCloudPlatform/nodejs-docs-samples#415]
Hello,

I tried to run the example code on raspberry pi zero w, but it shows 'Illegal instruction'. But it works fine when I switch to raspberry pi 3. So is it not support for armv6?

Thanks,
Lewis

**Comment by cache91** [comment]
I am also having the same problem on the Pi zero. Any updates to this ?

**Comment by fhinkel** [comment]
Closed due to inactivity. Feel free to reopen if needed.
