### ISSUE TITLE
sendgrid example memory potential leaks

### ISSUE THREAD

**Issue by uschen** [GoogleCloudPlatform/nodejs-docs-samples#416]
testing the sendgrid example in cloud function. Basically only the web hook function (saving to the storage, not the bigquery) here is the graph:

<img width="1408" alt="screen shot 2017-07-05 at 10 45 57 am" src="https://user-images.githubusercontent.com/1828412/27877365-2b7079ea-616f-11e7-8788-72a2838598dc.png">

`# of calls`:
<img width="1406" alt="screen shot 2017-07-05 at 10 46 43 am" src="https://user-images.githubusercontent.com/1828412/27877389-4345e5fa-616f-11e7-9bd5-9b03287387f2.png">

**Comment by fhinkel** [comment]
Closed due to inactivity. Feel free to reopen if needed.
