### ISSUE TITLE
helloGCS example for Cloud Functions doesn't work as expected

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/nodejs-docs-samples#423]
Cloud Storage doesn't seem to issue a "create" event on upload, but only a metadata change.  [This line](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/functions/helloworld/index.js#L105) in the example is never called

**Comment by fhinkel** [comment]
Closed due to inactivity. Feel free to reopen if needed.
