### ISSUE TITLE
When I try this translate.js,  "Could not load the default credentials" error  occurs

### ISSUE THREAD

**Issue by RecepOzturk** [GoogleCloudPlatform/nodejs-docs-samples#430]
When I try translate.js as are, the problem occurs called "could not load the default credentials Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
I can't run the translate.js or ı can't write  a request for translate api.  is there anyone who help me.

**Comment by ace-n** [comment]
Does [this section](https://developers.google.com/identity/protocols/application-default-credentials#howtheywork) of that page help, in particular the part about `GOOGLE_APPLICATION_CREDENTIALS`?

**Comment by fhinkel** [comment]
If the issue still persists, please file it [here](https://github.com/googleapis/nodejs-translate). Thank you.
