### ISSUE TITLE
unable to do translate image and place text on data bucket

### ISSUE THREAD

**Issue by bryanleekw** [GoogleCloudPlatform/nodejs-docs-samples#449]
I have tried to run the sample code,  but it seems the code could only run Processing images, but unable to do translate image and place text on data bucket. 

D      ocr-extract  138838521095966  2017-08-04 17:18:24.089  Function execution started
I      ocr-extract  138838521095966  2017-08-04 17:18:24.112  Looking for text in image googlelogo.png
D      ocr-extract  138839670257589  2017-08-04 17:18:24.850  Function execution started
I      ocr-extract  138839670257589  2017-08-04 17:18:24.912  Looking for text in image sign.png
I      ocr-extract  138838521095966  2017-08-04 17:18:25.326  Extracted text from image (7 chars)
I      ocr-extract  138838521095966  2017-08-04 17:18:25.717  Detected language "en" for googlelogo.png
I      ocr-extract  138839670257589  2017-08-04 17:18:26.546  Extracted text from image (4 chars)
I      ocr-extract  138839670257589  2017-08-04 17:18:26.836  Detected language "zh-TW" for sign.png
I      ocr-extract  138838521095966  2017-08-04 17:18:29.413  File googlelogo.png processed.
D      ocr-extract  138838521095966  2017-08-04 17:18:29.417  Function execution took 5329 ms, finished with status: 'ok'
I      ocr-extract  138839670257589  2017-08-04 17:18:30.118  File sign.png processed.
D      ocr-extract  138839670257589  2017-08-04 17:18:30.123  Function execution took 5274 ms, finished with status: 'ok'

Can anyone help to answer this?

**Comment by fhinkel** [comment]
If the issue still persists, please file it [here](https://github.com/googleapis/nodejs-translate). Thank you.
