### ISSUE TITLE
Integrating the speech api with audio / video player

### ISSUE THREAD

**Issue by augmen** [GoogleCloudPlatform/nodejs-docs-samples#454]
how to integrate the speech API to audio / video player for SPA nodes application ?

**Comment by S0NM** [comment]
just did an example, share it fo you [nodejs sample](https://github.com/S0NM/discovery/tree/master/google-speech-demo)

**Comment by fhinkel** [comment]
If the issue still persists, please file it [here](https://github.com/googleapis/nodejs-speech). Thank you.
