### ISSUE TITLE
What version does Google speech build?, because Azure is not working

### ISSUE THREAD

**Issue by EduardoMoraesRitter** [GoogleCloudPlatform/nodejs-docs-samples#460]
I'm using the nodejs-docs-samples project for vouls, locally it works perfectly, but when I'm using Azure with this configuration it's the same as my local machine, not builda, Can you help me?

npm version:
{ google: '0.0.1',
  npm: '3.10.8',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.1',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.84',
  zlib: '1.2.8' }

**Comment by fhinkel** [comment]
If the issue still persists, please file it [here](https://github.com/googleapis/nodejs-speech). Thank you.
