### ISSUE TITLE
speech sample should print out all results

### ISSUE THREAD

**Issue by jerjou** [GoogleCloudPlatform/nodejs-docs-samples#465]
There've been at least two people who've started from one of our speech samples, and didn't notice that it only uses the first transcription result, and concluded that the API was only transcribing the first minute of audio, when in fact they were getting transcript for the entire audio file, just in different `result`s.

We should update the samples to use all the results, to make it clear that there can be multiple ones.

**Comment by jmdobry** [comment]
Fixed.
