### ISSUE TITLE
insertData should apply mutations atomically

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/nodejs-docs-samples#488]
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/eaad9af7eb6f90f69a350d1cf1218106f6e09445/spanner/crud.js#L49

Currently the way sample is written it first applies mutations to singers table and then to albums table. Similar sample for other languages apply all the mutations in a single transaction.  I am not sure if there is some convenient method in Node.js client to do this short of starting a proper transaction.

**Comment by fhinkel** [comment]
If the issue still persists, please file it [here](https://github.com/googleapis/nodejs-spanner). Thank you.
