### ISSUE TITLE
Use a port picker to prevent port reuse

### ISSUE THREAD

**Issue by pcostell** [GoogleCloudPlatform/nodejs-docs-samples#49]
When running `npm test`, at least one test appears to hold on to port 8080 causing later tests to fail.

Rather than using port 8080 for all tests a port picker should be used for each test so that they don't interfere with each other.

**Comment by jmdobry** [comment]
What platform are you running the tests on? Also, how fast of a machine? I wonder if it isn't a race condition.

**Comment by jmdobry** [comment]
So I figured it out (and this is why I need to add instructions), but one of the tests attempts to connect to Redis, and another attempts to connect to memcached. Without both of those running, you'll get the `Error: bind EADDRINUSE null:8080` error.
