### ISSUE TITLE
How to catch error in GRPC ( Error: Audio data is being streamed too slowly...)

### ISSUE THREAD

**Issue by bloodcarter** [GoogleCloudPlatform/nodejs-docs-samples#495]
How do I catch the error " Error: Audio data is being streamed too slowly or too quickly. Please stream audio data approximately at real time" ?

I cannot fix it, but at least I need to be able to catch it and restart streamingRecognize. Thanks.

**Comment by fhinkel** [comment]
Closed due to inactivity. Feel free to reopen if needed.
