### ISSUE TITLE
NL Slackbot sample needs to be updated to latest @google-cloud/language

### ISSUE THREAD

**Issue by jmdobry** [GoogleCloudPlatform/nodejs-docs-samples#499]
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/language/slackbot

**Comment by fhinkel** [comment]
Do you know if this was updated?

**Comment by fhinkel** [comment]
If it wasn't updated, please re-file [here](https://github.com/googleapis/nodejs-language)
