### ISSUE TITLE
How can I create audio file that node.js google speech server can recognize??

### ISSUE THREAD

**Issue by geoseong** [GoogleCloudPlatform/nodejs-docs-samples#508]
Hi.

I want to create client side page that hopefully can record their voice at any remote device(no Sarafi for mobile support on mobile : [see Mozilla MediaRecorder API](https://developer.mozilla.org/ko/docs/Web/API/MediaRecorder))

I created recorded audio file and run google speech command but google speech server response of Transcription is nothing.
I run command like `node recognize.js sync ./resources/hello.raw -e LINEAR16 -r 16000`

So I link my code of client side page and please see what's wrong.
I want to know what options work to `16000 sampleRateHertz` and `LINEAR16 Encoding` in Javascript MediaRecorder API.

my code of client side page : [https://gist.github.com/geoseong/d42c24a3bdae9c2bb0d30b7fe7ecbe0a](https://gist.github.com/geoseong/d42c24a3bdae9c2bb0d30b7fe7ecbe0a)

Thanks.

**Comment by fhinkel** [comment]
If the issue still persists, please file it [here](https://github.com/googleapis/nodejs-speech). Thank you.
