### ISSUE TITLE
what does this mean? how do i make it available in my path?

### ISSUE THREAD

**Issue by vlisna789** [GoogleCloudPlatform/nodejs-docs-samples#510]
"Detects speech in a microphone input stream. This command requires that you have SoX
                            installed and available in your $PATH. See
                            https://www.npmjs.com/package/node-record-lpcm16#dependencies"

i downloaded what was in the link, but what does make it available in my path mean?

**Comment by fhinkel** [comment]
If the issue still persists, please file it [here](https://github.com/googleapis/nodejs-speech). Thank you.
