### ISSUE TITLE
Message received in several subscriptions

### ISSUE THREAD

**Issue by mmhiguera** [GoogleCloudPlatform/nodejs-docs-samples#527]
I have a topic with several pull subscriptors, when I publish a message in that topic, all or almost all the subscriptors receive the message at the same time. According to the documentation rarely this situation takes place but in fact this is happening in every test so, how can I solve the problem ? Will I get another result if I use push subscriptors instead of pull subscriptors ? 

Thanks in advance.

**Comment by fhinkel** [comment]
Closed due to inactivity. Feel free to reopen if needed.
