### ISSUE TITLE
Misleading documentation on authentification

### ISSUE THREAD

**Issue by Shahor** [GoogleCloudPlatform/nodejs-docs-samples#530]
According to the comments in [this file](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/auth/auth.js) all the google client libraries accept a config object for authentification. 

It is not the case though for at least the monitoring object, and maybe others (I have only checked this one so far) and seeing different informations on the documentation is super confusing.

Should all the packages now be used with the `GOOGLE_APPLICATION_CREDENTIALS` env variable only?

**Comment by jmdobry** [comment]
Setting `GOOGLE_APPLICATION_CREDENTIALS` should be sufficient for authentication for all official Google Node.js client libraries.

**Comment by Shahor** [comment]
I'm sorry, I was on a new codebase with an old version of the `storage` package and didn't understand fully how the auth worked considering the code I was seeing and the documentation.
