### ISSUE TITLE
Update method for safe search detection

### ISSUE THREAD

**Issue by aliciawilliams** [GoogleCloudPlatform/nodejs-docs-samples#533]
The method for safe search detection has been changed. I made a few changes to the code in order to complete this tutorial: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/functions/imagemagick/index.js. This is my first Github contribution (ever), so let me know if/how to proceed.

1. Added new `const request` immediately after the `const file` declaration.
```javascript
const request = {
    source: {
      imageUri: `gs://${object.bucket}/${file.name}`
    }
  };
```
2. Changed method name in line 44 from `vision.detectSafeSearch(file)` to `vision.safeSearchDetection(request)`
3. Updated the evaluation for determining an inappropriate image to account for new format of JSON response. Now looks for adult and violence outcomes of VERY_LIKELY or LIKELY.
```javascript
.then((results) => {
      const detections = results[0].safeSearchAnnotation;
      if (detections.adult == 'VERY_LIKELY' || detections.adult == 'LIKELY' || detections.violence == 'VERY_LIKELY' || detections.violence == 'LIKELY') {
        console.log(`The image ${file.name} has been detected as inappropriate.`);
        return blurImage(file);
      } else {
        console.log(`The image ${file.name} has been detected as OK.`);
      }
    });
```javascript

**Comment by fhinkel** [comment]
Closed due to inactivity. Feel free to reopen if needed.
