### ISSUE TITLE
Latency / Low confidence of Google Speech API

### ISSUE THREAD

**Issue by cache91** [GoogleCloudPlatform/nodejs-docs-samples#537]
I am having this wierd issue when using google speech api. I am using the `streamingRecognize` feature on a pi. When I use it to detect English , it works perfectly every single time and there is zero lag. But when i try to switch languages , say Spanish , the results are inconsistent. Sometimes it works fast , sometime it takes around 7 seconds for the text to be recognized and the behaviour is very unpredictable. I switched hardwares too and still no clue. Is there something I am missing here ? The Code is from the example in the repo.

**Comment by fhinkel** [comment]
Sorry for the late response, if this is still an issue, please file it [here](https://github.com/googleapis/nodejs-speech).
