### ISSUE TITLE
mqtt client connection closed

### ISSUE THREAD

**Issue by roccomuso** [GoogleCloudPlatform/nodejs-docs-samples#561]
I'm using IoT core with the Node.js mqtt client.

After a successful connection, if I try to publish a message, the connection gets closed. Is it a normal behavior?

Anybody tested the [mqtt_example](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/iot/mqtt_example) ?

I'm publishing to the standard topic `/devices/<DEVICE_ID>/events`

**Comment by fhinkel** [comment]
@gguuss can you have a look at this IoT issue or re-assign please. Thanks.

**Comment by gguuss** [comment]
@roccomuso This issue could occur if the pubsub topic was incorrectly created; try using the state topic instead to see if the issue persists.
