### ISSUE TITLE
Determine what's causing test failures in functions

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/nodejs-docs-samples#572]
I had to set a couple tests to skip on [this PR](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/571) in order to get the tests passing again.  I think there's some flakiness in the Google Cloud Functions test bootstrap. Leaving in issue for now to clean up when you're free.

**Comment by campionfellin** [comment]
Hey @gguuss and @ace-n I took a look at this and got all the tests in functions/helloworld passing locally. It took quite a bit of time just messing with things, but this weekend I can write up a fairly detailed explanation. It seems like the main issue is missing environmental variables. I'm not entirely sure how CircleCI works behind the scenes, but if you think it's helpful, I can show you what I did.

**Comment by fhinkel** [comment]
Closed due to inactivity. Feel free to reopen if needed. @ace-n is working on the functions tets.
