### ISSUE TITLE
[node recognize.js listen] is not recording

### ISSUE THREAD

**Issue by JoYeonJeong** [GoogleCloudPlatform/nodejs-docs-samples#578]
Even if I do not speak, it ends itself. I really want to use the listen option to do STT. 
the sync and stream options are executed. However, the listen option is not executed.
Please let me know what you need to do.

It is result that  command is [node recognize.js listen] 
Start recording and send the microphone input to the Speech API..
Recording with sample rate 16000...
Listening, press Ctrl+C to stop.
End Recording: 1002.741ms

Why not? I don't know!! Never!!!
.
.
Please Help me...

**Comment by fhinkel** [comment]
If the issue still persists, please file it [here](https://github.com/googleapis/nodejs-speech). Thank you.
