### ISSUE TITLE
Typo in AppEngine/Resify Readme

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/nodejs-docs-samples#594]
In nodejs-docs-samples/appengine/restify/README.md, weird note for link:
"[EDIT ON GITHUB  REPORT ISSUE  PAGE HISTORY
Run Restify.js on Google App Engine Flexible Environment](https://cloud.google.com/community/tutorials/run-restifyjs-on-google-app-engine)"

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for the report!  I just took a look, and this appears to be cleaned up :) Please do let us know if you have any problems!
