### ISSUE TITLE
Google Cloud IOT getClient example timeout with no other errors

### ISSUE THREAD

**Issue by nburnett** [GoogleCloudPlatform/nodejs-docs-samples#603]
Any time I try to use the example located here: https://cloud.google.com/iot/docs/how-tos/credentials/authenticating-applications, It will always fail with the following error while running locally through the Function Emulator:

info: Execution took 60000 ms, finished with status: 'timeout'
info: Execution took 60012 ms, finished with status: 'crash'

I'm not sure how to debug this as there is no other information, this part of the example seems to be the issue:

```
// discoveryURL = https://cloudiot.googleapis.com/$discovery/rest?version=v1
google.discoverAPI(discoveryUrl, {}, (err, client) => {
    if (err) {
      console.log('Error during API discovery', err);
      return undefined;
    }
    cb(client);
  });
```

What I'm seeing is the google.discoverAPI() is being called and the callback function is never called and there is no other error other than the timeout. 

Any help would be much appreciated.

**Comment by nburnett** [comment]
I'm currently using googleapis version 28.1.0 and have tried latest with the same results.

**Comment by fhinkel** [comment]
@gguuss can you have a look? Thanks

**Comment by gguuss** [comment]
@nburnett Try looking at the [Device to Device communication tutorial](https://cloud.google.com/community/tutorials/iot-device-to-device) and see if the code there is working for you. The code in the NodeJS repository may be out of date with what's necessary to use Google Cloud Functions.

**Comment by fhinkel** [comment]
Thanks @gguuss . Closing this. @nburnett , please reopen if the issue still persists.
