### ISSUE TITLE
Server Error when running PubSub sample

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/nodejs-docs-samples#607]
I followed the README at https://github.com/GoogleCloudPlatform/nodejs-docs-samples/appengine/pubsub/

After deploying to App Engine standard, I see in the logs:
```
A  Error: `line` is not an integer 
A      at Parser.initBlock (/srv/node_modules/pug-parser/index.js:156:36) 
A      at Parser.emptyBlock (/srv/node_modules/pug-parser/index.js:168:17) 
A      at Parser.parseTag (/srv/node_modules/pug-parser/index.js:1040:19) 
A      at Parser.parseExpr (/srv/node_modules/pug-parser/index.js:208:21) 
A      at Parser.parse (/srv/node_modules/pug-parser/index.js:112:25) 
A      at parse (/srv/node_modules/pug-parser/index.js:12:20) 
A      at Object.parse (/srv/node_modules/pug/lib/index.js:125:22) 
A      at Function.loadString [as string] (/srv/node_modules/pug-load/index.js:45:21) 
A      at compileBody (/srv/node_modules/pug/lib/index.js:86:18) 
A      at Object.exports.compile (/srv/node_modules/pug/lib/index.js:242:16) 
```

**Comment by michaelawyu** [comment]
Hi @steren. It seems to be a compatibility issue. The samples are checked in Feb and on March a routine dependency update (#583 ) bumped the version of package `pug` from 2.0.0-rc3 to 2.0.0. The sample runs just fine with the old version. I will update the code to keep it compatible with `pug` 2.0.0.

**Comment by steren** [comment]
Thanks for investigating.
do you know why our integration tests did not catch this?

**Comment by michaelawyu** [comment]
Seems to be a known bug with pug 2.0.0 (https://github.com/pugjs/pug/issues/2979). Updating to 2.0.1 solves the problem. Sending the PR now.

**Comment by michaelawyu** [comment]
From my understanding there are still some configuration problems with the CircleCI system :( Ace has migrated some tests to Kokoro and Les has asked us to migrate the rest  to Kokoro as well. It shouldn't be a problem soon, I think

**Comment by fhinkel** [comment]
I think this got fixed with @michaelawyu 's PR. Closing, feel free to reopen if still needed.
