### ISSUE TITLE
Incorrect metadata endpoint in GAE standard sample

### ISSUE THREAD

**Issue by ericschmidtatwork** [GoogleCloudPlatform/nodejs-docs-samples#616]
Issue found in the following file:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/appengine/metadata/standard/server.js#L25

According to the [currently documented list of App Engine metadata server endpoints](https://cloud.google.com/appengine/docs/standard/java/accessing-instance-metadata#identifying_which_metadata_endpoint_to_use), the endpoint used in this sample (`/computeMetadata/v1/instance/network-interfaces`) is not available in the App Engine standard environment.

**Comment by michaelawyu** [comment]
I will update this sample to use `project-id` instead `external-ip` :)

**Comment by michaelawyu** [comment]
@ericschmidtatwork PR sent: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/617

I vaguely recall that this sample was updated to use project ID before...

**Comment by michaelawyu** [comment]
PR merged: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/624
