### ISSUE TITLE
Parse-server sample for Google App Engine not recognizing variables in yaml

### ISSUE THREAD

**Issue by maloykr** [GoogleCloudPlatform/nodejs-docs-samples#63]
Parse-server sample for Google App Engine for some reason is not recognizing variables (appid and masterkey) in yaml.  

When you npm start, you get "You must provide an appId and masterKey!" even if they are in the yaml

**Comment by jmdobry** [comment]
`app.yaml` is read by Google App Engine itself, not NPM, and is therefore is only useful for deployment. So when you're running the app locally, you need to set the environment variables yourself, e.g.

    export MASTER_KEY=foo
    npm start

or

    MASTER_KEY=foo npm start

Note: Syntax for setting env vars depends on your environment

**Comment by maloykr** [comment]
got it ...

was following 

https://medium.com/google-cloud/deploying-parse-server-to-google-app-engine-6bc0b7451d50#.o21fdg2g4

and it mentioned you could use npm but that seems erroneous.

thanks.
