### ISSUE TITLE
Wrong Port

### ISSUE THREAD

**Issue by themichael123** [GoogleCloudPlatform/nodejs-docs-samples#64]
Hi Google team, 

the implementation of Parse Server:

app.listen(process.env.PORT || 8080, '0.0.0.0', function()

will lead to sporadic nginx 502 gateway errors. The official parse-server repo uses a different port. 

Thanks.

**Comment by jmdobry** [comment]
Parse-server itself is not actually a server, but middleware that you attach to your actual server. And as middleware, Parse-server doesn't care what port you use–the Parse-server source code doesn't even ever look at the port. The example server shown in the Parse-server README does indeed use a different default port, but like our sample, the Parse-server sample also prefers `process.env.PORT` over the default, so if you have need to use a particular port, just set the `PORT` environment variable to a port of your choosing and you should be good to go.
