### ISSUE TITLE
Hello Worlds provides an AppEngine standard version, which doesn't work (yet)

### ISSUE THREAD

**Issue by lukeschaefer** [GoogleCloudPlatform/nodejs-docs-samples#651]
In appengine/hello-world/standard - it describes how to launch a nodejs app in the standard AppEngine platform. But this doesn't work ("Invalid runtime nodejs8 selected") - and the link to the docs (https://cloud.google.com/appengine/docs/standard/nodejs) 404s. So far, there hasn't been any mention in documentation that nodejs is supported in AppEngine standard.

**Comment by lukeschaefer** [comment]
Welp - appears I was two days early to trying it out!
https://cloudplatform.googleblog.com/2018/06/Now-you-can-deploy-your-Node-js-app-to-App-Engine-standard-environment.html

**Comment by mrwillis** [comment]
Yes this is confusing documentation. I'm using flex and I tried `nodejs8` then I got some obscure error exactly as above.

**Comment by somangshu** [comment]
when i set `runtime: nodejs` the service gets deployed but gives a warning at the beginning that my package.json requires node 8.0

What is the version used by `runtime: nodejs` with `env: flex`

**Comment by CharlieHess** [comment]
>What is the version used by `runtime: nodejs` with `env: flex`

Looks like it uses the version defined in the `engines` field in `package.json`.

**Comment by aneesshameed** [comment]
For flex env, in app.yaml you need following, Do don't specify the version in app.yaml
runtime: nodejs
env: flex

and in package.json you need to specify the version
"engines": {
    "node": "8.x.x"
  },

Here are the list of version 
8.x.x
^8.0.0
~8
>=6

More details: https://cloud.google.com/appengine/docs/standard/nodejs/runtime
