### ISSUE TITLE
Slow "Browser" instance creation w/ Headless Chrome GAE Standard Node.js

### ISSUE THREAD

**Issue by kylewill** [GoogleCloudPlatform/nodejs-docs-samples#671]
I was able to successfully set up the[ example Headless Chrome demo](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/appengine/headless-chrome) on GAE Standard with the new runtime. 

However, I'm seeing 10-40 second latency for screenshots (no changes to the code). In stackdriver, 6-9 seconds of the latency is due to the `puppeteer.launch` call. This is incredibly long. 

Understand the new GAE Standard Node.js runtime is in Beta, logging to keep track of any updates as several projects will be enabled by usability here.

**Comment by kylewill** [comment]
Just deployed the same app to GAE Flex, the `puppeteer.launch` step is 0ms in stackdriver vs 6000-9000ms on GAE Standard

**Comment by steren** [comment]
Thanks for the feedback.
We are aware of a latency issue with Headless Chrome on App Engine standard and are working on improving the underlying infrastructure.

**Comment by fhinkel** [comment]
ping @steren is this still an issue?

**Comment by steren** [comment]
This is being discussed in https://github.com/GoogleChrome/puppeteer/issues/3120. 

Because this is not the sample's fault, I suggest to close this issue in favor of https://github.com/GoogleChrome/puppeteer/issues/3120

**Comment by kylewill** [comment]
@steren will close and watch GoogleChrome/puppeteer#3120
