### ISSUE TITLE
Headless chrome app engine runs locally but not on app engine

### ISSUE THREAD

**Issue by shaunc869** [GoogleCloudPlatform/nodejs-docs-samples#681]
When I pull down the stock example under /appengine/headless chrome and run it locally it works fine. If I upload it to app engine and try to run it I get:

> A  (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
> A  (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) 
> A      at <anonymous> 
> A      at Function.launch (/srv/node_modules/puppeteer/lib/Launcher.js:116:40) 
> A      at Object.exports.spawn (child_process.js:502:9) 
> A      at ChildProcess.spawn (internal/child_process.js:323:11) 
> A      at _errnoException (util.js:992:11) 
> A  (node:6) UnhandledPromiseRejectionWarning: Error: spawn EACCES 
> A  App listening on port 8080 
> A  (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
> A  (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) 
> A      at <anonymous> 
> A      at Function.launch (/srv/node_modules/puppeteer/lib/Launcher.js:116:40) 
> A      at Object.exports.spawn (child_process.js:502:9) 
> A      at ChildProcess.spawn (internal/child_process.js:323:11) 
> A      at _errnoException (util.js:992:11) 
> A  (node:6) UnhandledPromiseRejectionWarning: Error: spawn EACCES 
> A  App listening on port 8080 
> A  (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
> A  (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) 
> A      at <anonymous> 
> A      at Function.launch (/srv/node_modules/puppeteer/lib/Launcher.js:116:40) 
> A      at Object.exports.spawn (child_process.js:502:9) 
> A      at ChildProcess.spawn (internal/child_process.js:323:11) 
> A      at _errnoException (util.js:992:11) 
> A  (node:6) UnhandledPromiseRejectionWarning: Error: spawn EACCES 
> A  App listening on port 8080 

It looks like an access error on the part of Chrome. Thanks for the help!

**Comment by clpacheco90** [comment]
it's not working for me too

**Comment by steren** [comment]
I could not reproduce.
For me, the sample runs without issues:

$ git clone https://github.com/GoogleCloudPlatform/nodejs-docs-samples.git
$ cd nodejs-docs-samples/appengine/headless-chrome/
$ gcloud app deploy app.standard.yaml

Open the deployed URL and add `?url=https://example.com` to it.

Can you confirm it still does not work for you?
Can you provide exact repro steps?
