### ISSUE TITLE
Error [13] Timed out when starting VMs

### ISSUE THREAD

**Issue by otymartin** [GoogleCloudPlatform/nodejs-docs-samples#69]
I've made several attempts to deploy on app engine and i can't get passed this error.

`Beginning teardown of remote build environment (this may take a few seconds).
Updating module [default]...|Deleted [https://www.googleapis.com/compute/v1/projects/##################].
Updating module [default]...failed.
ERROR: (gcloud.preview.app.deploy) Error Response: [13] Timed out when starting VMs.  It's possible that the application code is unhealthy.  (0/2 ready, 2 still deploying). 
My-MacBook-Pro-2:appName-server myMacName$ `

Typing the above URL into the browser I get this
`[{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "required",
    "message": "Login Required",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Login Required"
 }
}]`

**Comment by otymartin** [comment]
Fyi when I created my project in google cloud, I specified "USEast" but when I was deploying, I noticied the URL had `us-central1-f`

**Comment by jmdobry** [comment]
What are you trying to deploy?

**Comment by otymartin** [comment]
@jmdobry Im trying to deploy the Parse-server[ using this tutorial](https://medium.com/google-cloud/deploying-parse-server-to-google-app-engine-6bc0b7451d50)

**Comment by jmdobry** [comment]
From the error message, it looks like the app deployed but failed to start. Have you set the required environment variables in `app.yaml`?

You can go to the Logging view in the Developers Console to see error stack traces that were printed.

**Comment by otymartin** [comment]
@jmdobry Hey thanks you were right. My cloud code destination was misplaced I fixed it

`cloud: __dirname + '/cloud/main.js',`
