### ISSUE TITLE
package.json of our samples are polluted by our maintenance tools

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/nodejs-docs-samples#693]
Take a look at this example: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/appengine/hello-world/standard/package.json

`cloud-repo-tools`, `devDependencies` and most of the `scripts` do not serve the purpose of giving example code to our users, instead, they are data used by our maintenance tools. 

Could they be in a different file that does not interfere with ` package.json` ?

**Comment by steren** [comment]
Because they contain more that what is actually needed and JSON does not support comments, the package.json cannot be embedded in our documentation without confusing users.

**Comment by fhinkel** [comment]
I think we're getting rid of `repo-tools`, cc @JustinBeckwith . That would get rid of one dev-dependency. 

I don't think there's a good solution to making samples short - but also self contained and on the CI 😞

**Comment by JustinBeckwith** [comment]
So yeah, `repo-tools` is on its way out.  @fhinkel is it doing anything important for these samples?

As far as others are concerned - I disagree! Things like `mocha` or `semistandard` are just part of a normal development process. I don't think having them in the devDependencies is hurting anything, and if anything it pushes developers towards good software development process.

**Comment by fhinkel** [comment]
A lot of samples rely on this test setup: 
```
"cloud-repo-tools": {
    "test": {
      "app": {
        "msg": "Hello, world!"
      }
    },
    "requiresKeyFile": true,
    "requiresProjectId": true
  }
```
If we remove the `repo-tools` dependency, we'd need to write those tests ourselves - which I would prefer because no user will be familiar with the `repo-tools` magic.

**Comment by fhinkel** [comment]
Closing this, I think our `package.json`s are fairly standard and not confusing to Node devs.
