### ISSUE TITLE
memcache env vars

### ISSUE THREAD

**Issue by avner-solomon** [GoogleCloudPlatform/nodejs-docs-samples#71]
I copied this code and it took me some uploads to realize why memcache had problems

the env vars are called memcache and not memcached

**Comment by jmdobry** [comment]
> this code

You're referring to the [express-memcached-session](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/appengine/express-memcached-session) sample?

**Comment by avner-solomon** [comment]
Sorry my bad,
I am referring to pure memcached sample since that's the one linked in 
the google docs
nodejs-docs-samples/appengine/memcached/app.js
