### ISSUE TITLE
[GAE-S] can't upload zip files

### ISSUE THREAD

**Issue by VikramTiwari** [GoogleCloudPlatform/nodejs-docs-samples#734]
Using the example [here](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/appengine/storage/standard/app.js) to upload a file works totally fine from local (to gs) but won't work for zip files when deployed to app engine (standard). Only change made to file is to increase the limit to 1 GB on [this line](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/appengine/storage/standard/app.js#L45).

Attached are the sample zip files:

[FL_insurance_sample.csv.zip](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/files/2362753/FL_insurance_sample.csv.zip)
[SampleZIPFile_10mbmb.zip](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/files/2362757/SampleZIPFile_10mbmb.zip)

Not sure what I am doing wrong.

**Comment by VikramTiwari** [comment]
@jasonpolites Any help on this?

**Comment by jasonpolites** [comment]
App Engine has a 32MB file size (POST BODY) limit (https://cloud.google.com/appengine/quotas, search for "Incoming bandwidth").  We have some docs in Cloud Functions for how to do "large" file uploads that should work in App Engine without much re-work https://cloud.google.com/functions/docs/writing/http#file_uploads_using_cloud_storage

**Comment by VikramTiwari** [comment]
Hey @jasonpolites Neither of the attached files are more than 30MB (including the whole POST body). On such files I am getting the proper error `413 Request Entity Too Large`. But for zip files, I am getting the `500 Server Error` even for 10kb zip files.

The code I am using is the same as in the example here: 
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/appengine/storage/standard/app.js

Not sure what I am doing wrong. cc: @jmdobry

**Comment by VikramTiwari** [comment]
Using signed URLs worked fine. If I get time, I will add a PR for the signed-urls sample for app engine too. 
Thanks for all the help @jasonpolites and @jmdobry 👍
