### ISSUE TITLE
Environment variables mislabeled as "cannot be overridden"

### ISSUE THREAD

**Issue by ZackKnopp** [GoogleCloudPlatform/nodejs-docs-samples#747]
Forgive me if this is the wrong place to raise this issue.

Documentation [here](https://cloud.google.com/appengine/docs/standard/nodejs/runtime#environment_variables) states that the environment variable "NODE_ENV" cannot be overridden in google app engine standard environment for Node. However, the following yaml file successfully overrides the variable.

```
runtime: nodejs8
env_variables:
    NODE_ENV: development
```

Am I missing something?

**Comment by fhinkel** [comment]
👋 @ZackKnopp . Thanks for reporting the issue, looks like the docs are wrong, as `NODE_ENV` can be changed. I get this changed internally.
