### ISSUE TITLE
markDone() needs to set the 'done' property to true

### ISSUE THREAD

**Issue by WalterHub** [GoogleCloudPlatform/nodejs-docs-samples#77]
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/datastore/tasks.js#L116 needs true instead of false.

**Comment by jmdobry** [comment]
Fixed by [52ed71](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/commit/52ed71aaf540355869edfd0c38c4441b7d442773)
