### ISSUE TITLE
appengine/analytics got error

### ISSUE THREAD

**Issue by jontore** [GoogleCloudPlatform/nodejs-docs-samples#771]
There is minor bug in the analytics example that stops the request to be posted correctly.

According to the got documentation https://www.npmjs.com/package/got#form, ```form``` is a ```boolean``` and the formdata should be added as the ```body ``` property. 

that means that https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/appengine/analytics/app.js#L50
should be 
```
   return got.post('http://www.google-analytics.com/collect', {
    form: true,
    body: data,
   });
```

not 

```
  return got.post('http://www.google-analytics.com/collect', {
    form: data
  });
```

**Comment by grant** [comment]
This was fixed in #585.
