### ISSUE TITLE
Cannot deploy my app to App Engine after Installing Parse Dashboard

### ISSUE THREAD

**Issue by otymartin** [GoogleCloudPlatform/nodejs-docs-samples#79]
I followed all the steps to get the dashboard up and running, it works.

However, its created a problem for me. `gloud preview app deploy` gives me errors. It fails to deploy.

I installed the dashboard files within the same folder where I have my parse server.
Parse Server Directory: `dev/appName-server/"server files, cloud code, app.yaml e.t.c`
Dashboard Directory: `dev/appname-server/parse-dashboard`

When I run my command to deploy my server code `gcloud preview app deploy` I get this problem

``` terminal
Beginning deployment...

ERROR: (gcloud.preview.app.deploy) There is a Dockerfile in the current directory, and the runtime field in /Users/myUserName/Documents/dev/appName-server/app.yaml is currently set to [runtime: nodejs]. To use your Dockerfile to build a custom runtime, set the runtime field in /Users/myUserName/Documents/dev/appName-server/app.yaml to [runtime: custom]. To continue using the [nodejs] runtime, please omit the Dockerfile from this directory. 
```

Even After removing the DockerFile in my `dev/appName-server/` directory, my deployment gets stuck at 

``` terminal
Verifying that Managed VMs are enabled and ready.
Provisioning remote build service.
Copying certificates for secure access. You may be prompted to create an SSH keypair.
Building and pushing image for module [default]
--- DOCKER BUILD OUTPUT ---
```

Update: I deleted the parse dashboard from my server folder and reinstalled outside of it and the error still persists stopping me from deploying. `gloud preview app deploy` works when I delete the parse dashboard

``` terminal
Beginning deployment...
If this is your first deployment, this may take a while...done.

fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Verifying that Managed VMs are enabled and ready.
Provisioning remote build service.
Copying certificates for secure access. You may be prompted to create an SSH keypair.
ERROR: gcloud crashed (TLSParameterError): Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See http://docs.docker.com/examples/https/ for API details.
```

**Comment by otymartin** [comment]
?

**Comment by JustinBeckwith** [comment]
This was likely a transient issue with App Engine.  We've completely changed the way these deployments happen.  Please let us know if this is still an issue!
