### ISSUE TITLE
OperationError: code=13, message=Error when creating Kubernetes cluster

### ISSUE THREAD

**Issue by sprakash3** [GoogleCloudPlatform/nodejs-docs-samples#80]
Hi,
I'm trying to run the HelloWorld example to trigger an event for a GCS bucket activity. I get the following error. The APIs for container engine has been enabled for the project. 

ERROR: (gcloud.alpha.functions.deploy) OperationError: code=13, message=Error when creating Kubernetes cluster for project <project-id>

Thanks!

**Comment by jmdobry** [comment]
Have you joined the Cloud Functions Alpha? I believe you need to be added to a whitelist.

**Comment by jmdobry** [comment]
@sprakash3 Did you join the Alpha? Did you get it working?

**Comment by sprakash3** [comment]
Yes. Thanks
