### ISSUE TITLE
Slow getClient

### ISSUE THREAD

**Issue by j-blasco** [GoogleCloudPlatform/nodejs-docs-samples#824]
So I want to update my device configuration from a Firebase Cloud Function. 
I've created a JWT service account that allows the firebase functions to manage all the devices. 
The getDevice() function takes 2 seconds before I get the client... 
Is threre a way to speed this up?
Every time I want to call the function I need to wait to get this client. Is there another approach? Or is it not normal that it takes for so long?

**Comment by fhinkel** [comment]
@ace-n, can you route this to the appropriate Cloud Function person please. Thanks

**Comment by ace-n** [comment]
/cc @samtstern

Does [this](https://cloud.google.com/functions/docs/bestpractices/tips#use_global_variables_to_reuse_objects_in_future_invocations) help?

**Comment by fhinkel** [comment]
ping @samstern, please have a look.

**Comment by samtstern** [comment]
Sorry I don't think I am the right person, I don't know about this.

If `getClient()` produces a singleton you can share you can call it outside of the cloud function body though.

**Comment by ace-n** [comment]
Closing this due to a lack of activity. @j-blasco please reply here (or create another issue) if this is still a problem for you (and the suggestions above didn't help) - thanks!
