### ISSUE TITLE
Tracking issue: move samples to their client libraries

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-docs-samples#831]
- [x] Debugger: https://github.com/googleapis/cloud-debug-nodejs/issues/577

- [x] Trace: https://github.com/googleapis/cloud-trace-nodejs/issues/909, https://github.com/googleapis/cloud-trace-nodejs/pull/912

**Comment by fhinkel** [comment]
I think the samples for error-reporting moved there 8 months ago.

**Comment by JCIV-SE** [comment]
Should this issue be closed?
