### ISSUE TITLE
Improve version tags in headless chrome sample

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-docs-samples#834]
@steren can you fix this? 

Per our guidelines: 

> Region tag should use a product prefix, e.g. "vision_".

Where does the code snippet show up in our docs? Our tool can't find it. 

> Update region tag and link to a new or existing tracked sample.
> Import into Devsite or delete.

**Comment by fhinkel** [comment]
ping @steren

**Comment by steren** [comment]
I will not have time for it, and this needs to be synced with docs changes. Please follow up with @llatif

**Comment by fhinkel** [comment]
@llatif Can you please update the region tags for the headless chrome sample to follow our guidelines. Thanks.

**Comment by fhinkel** [comment]
ping @llatif

**Comment by grant** [comment]
See above PR.
