### ISSUE TITLE
A broken link in nodejs endpoints readme

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/nodejs-docs-samples#851]
In [this](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/appengine/endpoints) page, this link is broken:
https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/managed_vms/endpoints

**Comment by fhinkel** [comment]
@engelke The bottom of [this](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/appengine/endpoints) page points to a Python client. Do you know what the updated URL is? Thank you.
