### ISSUE TITLE
Add instructions on how to use http2 with node.js enabled appengine

### ISSUE THREAD

**Issue by kenchris** [GoogleCloudPlatform/nodejs-docs-samples#86]
subject says it all

**Comment by JustinBeckwith** [comment]
We *sorta* have support for HTTP/2.  We terminate HTTP/2 connections at our load balancer, and then forward HTTP/1.1 requests to your application.  We don't quite have HTTP/2 wired the whole way through to your app just yet.

**Comment by kenchris** [comment]
OK, that would be nice, so that I can avoid vulcanizing my resources and do something similar to https://github.com/GoogleChrome/http2push-gae

**Comment by jmdobry** [comment]
Moved to GoogleCloudPlatform/community#226
