### ISSUE TITLE
Problem with the appengine-parse-server package

### ISSUE THREAD

**Issue by otymartin** [GoogleCloudPlatform/nodejs-docs-samples#88]
@jmdobry @JustinBeckwith 
I added the liveQuery code in my server.js and now I can't deploy

```
push: {
      ios: {
        pfx: __dirname  + '/cloud/ParsePushDevelopmentCertificate.p12',
        bundleId: 'com.bundleIdName.appName',
        production: false
      }
    }
  liveQuery: {
    classNames: ['Message'];
  }
});
```

```
// Mount the Parse API server middleware to /parse
app.use(process.env.PARSE_MOUNT_PATH || '/parse', parseServer);
```

``` js
app.get('/', function(req, res) {
  res.status(200).send('Be Real');
});
```

``` js
var server = app.listen(process.env.PORT || 8080, '0.0.0.0', function() {
  console.log('App listening at http://%s:%s', server.address().address,
    server.address().port);
  console.log('Press Ctrl+C to quit.');
});
```

``` js
// Initialize a LiveQuery server instance, app is the express app of your Parse Server
let httpServer = require('http').createServer(app);
httpServer.listen(port);
var parseLiveQueryServer = ParseServer.createLiveQueryServer(httpServer);
```

**ERROR**

`````` npm

WARN

engine
 parse-server@2.2.1: wanted: {"node":">=4.3"} (current: {"node":"4.2.3","npm":"2.14.7"})```

Don't know why I get this even though I put this in my package.json
`"node": "~4.3"`

**ERROR LOG: NPM DEBUG**
```0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.12
3 info using node@v4.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart appengine-parse-server@0.0.1
6 info start appengine-parse-server@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info appengine-parse-server@0.0.1 Failed to exec start script
9 verbose stack Error: appengine-parse-server@0.0.1 start: `node server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid appengine-parse-server@0.0.1
11 verbose cwd /Users/otymartin/Documents/dev/app-server
12 error Darwin 15.3.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.3.1
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error appengine-parse-server@0.0.1 start: `node server.js`
17 error Exit status 1
18 error Failed at the appengine-parse-server@0.0.1 start script 'node server.js'.
18 error This is most likely a problem with the appengine-parse-server package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js
18 error You can get their info via:
18 error     npm owner ls appengine-parse-server
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]```
``````

**Comment by jmdobry** [comment]
Can you post your actual `package.json` file? Where did this logging output come from? Did it come from the Logging tab in the Cloud Console?

**Comment by otymartin** [comment]
**Package.json**
`{
  "name": "appengine-parse-server",
  "description": "Parse-server sample for Google App Engine",
  "version": "0.0.1",
  "private": true,
  "license": "Apache Version 2.0",
  "author": "Google Inc.",
  "engines": {
    "node": "~4.3"
  },
  "scripts": {
    "start": "node server.js",
    "monitor": "nodemon server.js",
    "deploy": "gcloud preview app deploy"
  },
  "dependencies": {
    "express": "^4.13.4",
    "parse-server": "^2.2.1"
  }
}`

gloud preview app deploy
`

**npm.debug.log**
`parse-server@2.2.1: wanted: {"node":">=4.3"} (current: {"node":"4.2.3","npm":"2.14.7"})`

**npm-debug.log**
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'owner',
1 verbose cli   'ls',
1 verbose cli   'appengine-parse-server' ]
2 info using npm@2.14.12
3 info using node@v4.3.1
4 silly mapToRegistry name appengine-parse-server
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry uri https://registry.npmjs.org/appengine-parse-server
8 verbose request uri https://registry.npmjs.org/appengine-parse-server
9 verbose request no auth needed
10 info attempt registry request try #1 at 1:43:20 PM
11 verbose request id 32cb6b902afad2cb
12 http request GET https://registry.npmjs.org/appengine-parse-server
13 http 404 https://registry.npmjs.org/appengine-parse-server
14 verbose headers { 'content-type': 'application/json',
14 verbose headers   'cache-control': 'max-age=0',
14 verbose headers   'content-length': '2',
14 verbose headers   'accept-ranges': 'bytes',
14 verbose headers   date: 'Wed, 23 Mar 2016 17:43:31 GMT',
14 verbose headers   via: '1.1 varnish',
14 verbose headers   age: '0',
14 verbose headers   connection: 'keep-alive',
14 verbose headers   'x-served-by': 'cache-ord1748-ORD',
14 verbose headers   'x-cache': 'MISS',
14 verbose headers   'x-cache-hits': '0',
14 verbose headers   'x-timer': 'S1458755011.026303,VS0,VE151' }
15 silly get cb [ 404,
15 silly get   { 'content-type': 'application/json',
15 silly get     'cache-control': 'max-age=0',
15 silly get     'content-length': '2',
15 silly get     'accept-ranges': 'bytes',
15 silly get     date: 'Wed, 23 Mar 2016 17:43:31 GMT',
15 silly get     via: '1.1 varnish',
15 silly get     age: '0',
15 silly get     connection: 'keep-alive',
15 silly get     'x-served-by': 'cache-ord1748-ORD',
15 silly get     'x-cache': 'MISS',
15 silly get     'x-cache-hits': '0',
15 silly get     'x-timer': 'S1458755011.026303,VS0,VE151' } ]
16 error owner ls Couldn't get owner data appengine-parse-server
17 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/appengine-parse-server
17 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
17 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
17 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
17 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
17 verbose stack     at emitTwo (events.js:87:13)
17 verbose stack     at Request.emit (events.js:172:7)
17 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1082:10)
17 verbose stack     at emitOne (events.js:82:20)
17 verbose stack     at Request.emit (events.js:169:7)
17 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
18 verbose statusCode 404
19 verbose pkgid appengine-parse-server
20 verbose cwd /Users/otymartin/Documents/dev/bars-server
21 error Darwin 15.3.0
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "owner" "ls" "appengine-parse-server"
23 error node v4.3.1
24 error npm  v2.14.12
25 error code E404
26 error 404 Registry returned 404 for GET on https://registry.npmjs.org/appengine-parse-server
26 error 404
26 error 404 'appengine-parse-server' is not in the npm registry.
26 error 404 You should bug the author to publish it (or use the name yourself!)
26 error 404
26 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]`

**Comment by skbhati199** [comment]
**npm-debug.log**

**Comment by skbhati199** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Devendra\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'deploy' ]
2 info using npm@3.9.0
3 info using node@v4.4.4
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle appengine-express@0.0.1~predeploy: appengine-express@0.0.1
6 silly lifecycle appengine-express@0.0.1~predeploy: no script for predeploy, continuing
7 info lifecycle appengine-express@0.0.1~deploy: appengine-express@0.0.1
8 verbose lifecycle appengine-express@0.0.1~deploy: unsafe-perm in lifecycle true
9 verbose lifecycle appengine-express@0.0.1~deploy: PATH: C:\Users\Devendra\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\angularhack\nodejs-docs-samples\appengine\express\node_modules\.bin;C:\Program Files\nodejs;C:\Users\Devendra\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Devendra\AppData\Roaming\npm;
10 verbose lifecycle appengine-express@0.0.1~deploy: CWD: D:\angularhack\nodejs-docs-samples\appengine\express
11 silly lifecycle appengine-express@0.0.1~deploy: Args: [ '/d /s /c', 'gcloud preview app deploy' ]
12 silly lifecycle appengine-express@0.0.1~deploy: Returned: code: 1  signal: null
13 info lifecycle appengine-express@0.0.1~deploy: Failed to exec deploy script
14 verbose stack Error: appengine-express@0.0.1 deploy: `gcloud preview app deploy`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Devendra\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Devendra\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid appengine-express@0.0.1
16 verbose cwd D:\angularhack\nodejs-docs-samples\appengine\express
17 error Windows_NT 6.1.7600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Devendra\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "deploy"
19 error node v4.4.4
20 error npm  v3.9.0
21 error code ELIFECYCLE
22 error appengine-express@0.0.1 deploy: `gcloud preview app deploy`
22 error Exit status 1
23 error Failed at the appengine-express@0.0.1 deploy script 'gcloud preview app deploy'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the appengine-express package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gcloud preview app deploy
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs appengine-express
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls appengine-express
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by JustinBeckwith** [comment]
I recognize this error.  This looks like it may be an old Cloud SDK.  Can you run this?

`gcloud components update`

And then:

`gcloud --version`?

**Comment by ace-n** [comment]
Closing; @otymartin please reopen if this is still a problem.
