### ISSUE TITLE
Blurred image written to bucket isn't blurred

### ISSUE THREAD

**Issue by jwdavis** [GoogleCloudPlatform/nodejs-docs-samples#898]
Steps to repro

-- Set up cloud function as in readme steps 1-4
-- upload zombie picture as in readme step 5

Expected result

-- Offensive content is detected
-- Image is copied locally, blurred, then uploaded as new object
-- Viewing new object shows blurred image

Actual result

-- Offensive content is detected
-- Images is copied locally, acted on, and new object is uploaded
-- Viewing new object shows unblurred copy of original image

**Comment by fhinkel** [comment]
Is this PR addressing the issue? https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/893

**Comment by jwdavis** [comment]
yes - the proposed change does fix the issue.


Thanks,


jwd


--


about.me <https://jwdavis.me/jwd_about>

408-759-4664

calendar <https://jwdavis.me/jwd_gcal>


<https://jwdavis.me/jwd_about>

**Comment by grant** [comment]
Fixed with https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/893.
