### ISSUE TITLE
Google Cloud Functions Cloud Datastore sample error

### ISSUE THREAD

**Issue by jamie-chapman** [GoogleCloudPlatform/nodejs-docs-samples#929]
The tutorial in **https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/functions/datastore**

Example appears to not accept the sample JSON object in the function **"gcloud functions call set --data '{"kind":"Task","key":"sampletask1","value":{"description":"Buy milk"}}'".** 

The error below is given.

**ERROR: (gcloud.functions.call) Invalid value for [--data]: Is not a valid JSON: No JSON object could be decoded**

**Comment by fhinkel** [comment]
Hi 👋 . Thanks for reporting the issue. I can't reproduce the error. Are you using the newest `gcloud` version (Google Cloud SDK 226.0.0)? 

```bash
gcloud functions call set --data '{"kind":"Task","key":"sampletask1","value":{"description":"Buy milk"}}'
executionId: **********
result: Entity Task/sampletask1 saved.
```

**Comment by jamie-chapman** [comment]
Hi! Yes I am using version 226.0.0
`gcloud --version
Google Cloud SDK 226.0.0
alpha 2018.11.09
bq 2.0.38
core 2018.11.16
gsutil 4.34
`

Also using Node version v10.13.0 and Windows 10 version 1709, OS Build 16299.785

**Comment by fhinkel** [comment]
Could you post the full command that you tried? Everything worked fine for me when I copied the instructions. Do you have the API enabled?

**Comment by jamie-chapman** [comment]
Yes the API is enabled, I have since successfully created some Cloud functions that read JSON data and create an entity in Datastore.
Here's a trace of the commands I used for the example:
`\nodejs-docs-samples-master\nodejs-docs-samples-master\functions\datastore`
` gcloud functions deploy get --trigger-http`
' gcloud functions deploy set --trigger-http'
` gcloud functions deploy del --trigger-http`
' gcloud functions call set --data '{"kind":"Task","key":"sampletask1","value":{"description":"Buy milk"}}'

**`ERROR: (gcloud.functions.call) Invalid value for [--data]: Is not a valid JSON: No JSON object could be decoded`**
