### ISSUE TITLE
I can commit directly to master

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/nodejs-docs-samples#97]
Please enable master branch protection!

**Comment by JustinBeckwith** [comment]
@jmdobry turns out I'm not an admin on this repo :)

**Comment by broady** [comment]
I set these settings:
![screen shot 2016-04-08 at 6 33 08 am](https://cloud.githubusercontent.com/assets/24982/14365961/cbd48a74-fd53-11e5-80c1-fca2f0dbd551.png)

Hopefully that doesn't disrupt you. I think the last setting might be a good one to have, too?

**Comment by jmdobry** [comment]
Settings now set to what is shown in your screenshot.
