### ISSUE TITLE
Use async await instead of promises in auth

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-docs-samples#989]
Replace promise chains here https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/auth/auth.js. See this [blueprint](https://github.com/googleapis/nodejs-bigquery/pull/193/files).

**Comment by grant** [comment]
I couldn't find any Promise chains in that file.

It looks like it was fixed here:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/commit/35b51a9e8d3f6cb0e0479b1baf9061b2196a8af1#diff-bf68a1b9862def0546074001efe7bcea
